# P4 HWPX 690 KoE5 Embedding + Retrieval Quick Check

This notebook checks file size and retrieval quality for the P4 HWPX 690 corpus on Colab/GCV L4.

```text
1. Environment check
   - Google Drive mount
   - requirements.txt install
   - CUDA/GPU label

2. P4 HWPX 690 corpus load
   - outputs/parsing_p4_hwpx_690/chunks_v1_690.jsonl  # R0 clean text baseline
   - outputs/parsing_p4_hwpx_690/chunks_v2_690.jsonl  # structured corpus

3. Chroma load
   - v1: clean text chunks
   - v2: text/table/fact_candidates chunks, toc excluded

4. Retrieval quick check
   - R0: v1 + KoE5 dense top5
   - R1: v2 + KoE5 dense top30 -> reranker top5
   - R2: v2 + KoE5 dense top30 + BM25 top30 -> RRF top30 -> reranker top5

5. Evaluation
   - eval_batch_01.csv ~ eval_batch_25.csv only
   - default EVAL_SAMPLE_SIZE=100
   - append results to outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
```

Notes:

- Do not store Chroma DB on Google Drive. This notebook uses local runtime storage by default.
- Do not create `.npy` embedding cache unless there is a specific reason.
- Original RFP files, source evidence, Chroma DB, and embedding cache are not GitHub upload targets.

In [1]:
# ===== Install dependencies in the active kernel =====
# VS Code connected to Colab must install packages inside the Colab runtime.

from pathlib import Path
import importlib.util
import os
import subprocess
import sys


def find_project_root_for_install() -> Path:
    candidates = [
        Path(os.environ.get('RFP_PROJECT_ROOT', '')) if os.environ.get('RFP_PROJECT_ROOT') else None,
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/Colab Notebooks/DB_RAG_Codeit_Project'),
        Path.cwd(),
        *Path.cwd().parents,
    ]
    for base in candidates:
        if base and (base / 'requirements.txt').exists():
            return base.resolve()

    try:
        from google.colab import drive
        drive.mount('/content/drive', force_remount=False)
    except Exception as exc:
        print('Google Drive mount skipped:', exc)

    search_roots = [Path('/content/drive/MyDrive'), Path('/content/drive/Shareddrives'), Path('/content/drive')]
    matches = []
    for root in search_roots:
        if root.exists():
            try:
                matches.extend(root.rglob('requirements.txt'))
            except Exception as exc:
                print(f'skip search root: {root} | {exc}')
    matches = sorted(set(matches), key=lambda p: (0 if 'DB_RAG_Codeit_Project' in str(p) else 1, len(str(p))))
    if matches:
        print('found requirements candidates:')
        for i, p in enumerate(matches[:10]):
            print(f'  [{i}] {p}')
        return matches[0].parent.resolve()

    raise FileNotFoundError('requirements.txt was not found under /content/drive. Check PROJECT_ROOT_OVERRIDE or mount Drive.')


PROJECT_ROOT_FOR_INSTALL = find_project_root_for_install()
REQUIREMENTS_PATH = PROJECT_ROOT_FOR_INSTALL / 'requirements.txt'
print('PROJECT_ROOT_FOR_INSTALL:', PROJECT_ROOT_FOR_INSTALL)
print('REQUIREMENTS_PATH:', REQUIREMENTS_PATH)

REQUIRED_IMPORTS = {
    'chromadb': 'chromadb',
    'rank-bm25': 'rank_bm25',
    'sentence-transformers': 'sentence_transformers',
    'transformers': 'transformers',
    'openpyxl': 'openpyxl',
}
missing = [name for name, module in REQUIRED_IMPORTS.items() if importlib.util.find_spec(module) is None]

if missing:
    print('missing packages:', missing)
    print('installing:', REQUIREMENTS_PATH)
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '-r', str(REQUIREMENTS_PATH)])
    print('dependency install complete. If imports still fail, restart the Colab runtime once and rerun from the top.')
else:
    print('required packages already installed')

Mounted at /content/drive
found requirements candidates:
  [0] /content/drive/MyDrive/DB_RAG_Codeit_Project/requirements.txt
  [1] /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/requirements.txt
PROJECT_ROOT_FOR_INSTALL: /content/drive/MyDrive/DB_RAG_Codeit_Project
REQUIREMENTS_PATH: /content/drive/MyDrive/DB_RAG_Codeit_Project/requirements.txt
missing packages: ['chromadb', 'rank-bm25']
installing: /content/drive/MyDrive/DB_RAG_Codeit_Project/requirements.txt
dependency install complete. If imports still fail, restart the Colab runtime once and rerun from the top.

In [2]:
from __future__ import annotations

import ast
import json
import math
import os
import random
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
import chromadb
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 180)

print("python:", sys.version.split()[0])
print("torch:", torch.__version__)
print("cuda_available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))

python: 3.12.13
torch: 2.10.0+cu128
cuda_available: True
gpu: NVIDIA L4

In [3]:
# ===== User parameters =====
# Quick check default: P4 HWPX 690 corpus + 100 eval questions.

CORPUS_LIMIT = 690
EVAL_SAMPLE_SIZE = 100
EVAL_SAMPLE_SEED = 42

CORPUS_NAME = f"p4_hwpx_{CORPUS_LIMIT}"
CORPUS_COVERAGE = f"p4_hwpx_full_{CORPUS_LIMIT}"
CORPUS_VERSION_V1 = "v1_clean_text"
CORPUS_VERSION_V2 = "v2_hwpx_table_aware"

EMBEDDING_MODEL = "nlpai-lab/KoE5"
RERANKER_MODEL = "BAAI/bge-reranker-v2-m3"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150

EMBEDDING_BATCH_SIZE = 64
CHROMA_ADD_BATCH_SIZE = 512
RERANK_BATCH_SIZE = 32

FINAL_TOP_K = 5
DENSE_TOP_K = 30
BM25_TOP_K = 30
RRF_K = 60

RUN_RERANKER_EXPERIMENTS = True
RECREATE_CHROMA_COLLECTIONS = True
SAVE_EMBEDDING_CACHE = False  # Keep this False to avoid large .npy embedding cache files.

ENABLE_COVERAGE_GATE = True
MIN_TOP1_SCORE_FOR_WEAK_SIGNAL = 0.20
UNVERIFIED_ANSWER = "\ud655\uc778\ub418\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4."

# Google Drive / Colab default. Override with RFP_PROJECT_ROOT if needed.
PROJECT_ROOT_OVERRIDE = "/content/drive/MyDrive/DB_RAG_Codeit_Project"
# GCV VM example. Uncomment on GCV and comment out the Google Drive line above.
# PROJECT_ROOT_OVERRIDE = "/home/USER/DB_RAG_Codeit_Project"

# Keep Chroma outside Google Drive to avoid slow sync and heavy cache issues.
# predictions/csv stay under OUTPUT_DIR on Drive; Chroma uses local runtime storage.
LOCAL_CHROMA_ROOT_OVERRIDE = "/content/chroma_retrieval_eval_p4_hwpx"
# GCV VM example:
# LOCAL_CHROMA_ROOT_OVERRIDE = "/tmp/chroma_retrieval_eval_p4_hwpx"


def _project_root_score(path: Path) -> tuple:
    text = str(path).replace('\\', '/')
    return (
        0 if 'DB_RAG_Codeit_Project' in text else 1,
        0 if (path / 'outputs' / f'parsing_p4_hwpx_{CORPUS_LIMIT}').exists() else 1,
        len(text),
    )


def detect_project_root() -> Path:
    candidates = []
    env_root = os.environ.get('RFP_PROJECT_ROOT')
    if env_root:
        candidates.append(Path(env_root))
    if PROJECT_ROOT_OVERRIDE:
        candidates.append(Path(PROJECT_ROOT_OVERRIDE))
    candidates.extend([
        Path.cwd(),
        *Path.cwd().parents,
        Path('/content/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/Colab Notebooks/DB_RAG_Codeit_Project'),
        Path(r'C:/Users/yoosy/Desktop/codeit/project_2nd'),
    ])
    seen = set()
    for base in candidates:
        key = str(base)
        if key in seen:
            continue
        seen.add(key)
        if (base / 'outputs' / f'parsing_p4_hwpx_{CORPUS_LIMIT}' / f'chunks_v2_{CORPUS_LIMIT}.jsonl').exists():
            return base.resolve()
        if (base / 'notebooks' / 'rag').exists() and (base / 'requirements.txt').exists():
            return base.resolve()

    search_roots = [Path('/content/drive/MyDrive'), Path('/content/drive/Shareddrives'), Path('/content/drive')]
    matches = []
    target = Path('outputs') / f'parsing_p4_hwpx_{CORPUS_LIMIT}' / f'chunks_v2_{CORPUS_LIMIT}.jsonl'
    for root in search_roots:
        if root.exists():
            try:
                matches.extend(root.rglob(str(target)))
            except Exception as exc:
                print(f'skip search root: {root} | {exc}')
    matches = sorted(set(matches), key=lambda p: _project_root_score(p.parents[2]))
    if matches:
        print('found P4 chunks candidates:')
        for i, p in enumerate(matches[:10]):
            print(f'  [{i}] {p}')
        return matches[0].parents[2].resolve()

    return Path.cwd().resolve()


def gpu_label() -> str:
    if not torch.cuda.is_available():
        return "CPU"
    name = torch.cuda.get_device_name(0)
    if "L4" in name.upper():
        return "L4"
    if "4060" in name:
        return "RTX4060"
    return "CUDA"

PROJECT_ROOT = detect_project_root()
P4_DIR = PROJECT_ROOT / "outputs" / f"parsing_p4_hwpx_{CORPUS_LIMIT}"
V1_CHUNKS_PATH = P4_DIR / f"chunks_v1_{CORPUS_LIMIT}.jsonl"
V2_CHUNKS_PATH = P4_DIR / f"chunks_v2_{CORPUS_LIMIT}.jsonl"
EVAL_DIR = PROJECT_ROOT / "data" / "eval"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "retrieval_eval_p4_hwpx"
PREDICTION_DIR = OUTPUT_DIR / "predictions"
if LOCAL_CHROMA_ROOT_OVERRIDE:
    CHROMA_DIR = Path(LOCAL_CHROMA_ROOT_OVERRIDE) / f"p4_hwpx_{CORPUS_LIMIT}"
else:
    CHROMA_DIR = OUTPUT_DIR / "chroma"
EXTENDED_EVAL_SCRIPT = PROJECT_ROOT / "notebooks" / "eval" / "evaluation" / "scripts" / "run_retrieval_eval_extended.py"

EMBEDDING_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
EMBEDDING_DEVICE_LABEL = gpu_label()

for path in [OUTPUT_DIR, PREDICTION_DIR, CHROMA_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("EMBEDDING_DEVICE:", EMBEDDING_DEVICE)
print("EMBEDDING_DEVICE_LABEL:", EMBEDDING_DEVICE_LABEL)
print("V1_CHUNKS_PATH exists:", V1_CHUNKS_PATH.exists(), V1_CHUNKS_PATH)
print("V2_CHUNKS_PATH exists:", V2_CHUNKS_PATH.exists(), V2_CHUNKS_PATH)
print("EVAL_DIR exists:", EVAL_DIR.exists(), EVAL_DIR)
print("EXTENDED_EVAL_SCRIPT exists:", EXTENDED_EVAL_SCRIPT.exists(), EXTENDED_EVAL_SCRIPT)
print("CHROMA_DIR local:", CHROMA_DIR)

PROJECT_ROOT: /content/drive/MyDrive/DB_RAG_Codeit_Project
EMBEDDING_DEVICE: cuda
EMBEDDING_DEVICE_LABEL: L4
V1_CHUNKS_PATH exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_690/chunks_v1_690.jsonl
V2_CHUNKS_PATH exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_690/chunks_v2_690.jsonl
EVAL_DIR exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval
EXTENDED_EVAL_SCRIPT exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py
CHROMA_DIR local: /content/chroma_retrieval_eval_p4_hwpx/p4_hwpx_690

In [4]:
def file_mib(path: Path) -> float:
    return round(path.stat().st_size / 1024 / 1024, 2) if path.exists() else 0.0

file_check_df = pd.DataFrame([
    {"file": "chunks_v1", "path": str(V1_CHUNKS_PATH), "exists": V1_CHUNKS_PATH.exists(), "mib": file_mib(V1_CHUNKS_PATH)},
    {"file": "chunks_v2", "path": str(V2_CHUNKS_PATH), "exists": V2_CHUNKS_PATH.exists(), "mib": file_mib(V2_CHUNKS_PATH)},
])
display(file_check_df)

if not V1_CHUNKS_PATH.exists() or not V2_CHUNKS_PATH.exists():
    raise FileNotFoundError("P4 HWPX chunks_v1/chunks_v2 files are required before running retrieval quick check.")

,file,path,exists,mib
0,chunks_v1,/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_690/chunks_v1_690.jsonl,True,189.18
1,chunks_v2,/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_690/chunks_v2_690.jsonl,True,251.44

In [5]:
def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_chunks(path: Path) -> pd.DataFrame:
    df = pd.DataFrame(read_jsonl(path))
    if "content" not in df.columns:
        raise ValueError("chunks JSONL must include content")
    if "embed_enabled" not in df.columns:
        df["embed_enabled"] = True
    if "chunk_type" not in df.columns:
        df["chunk_type"] = "text"
    df = df.copy()
    df["content"] = df["content"].fillna("").astype(str)
    return df


def select_embedding_chunks(df: pd.DataFrame) -> pd.DataFrame:
    selected = df[df["embed_enabled"].fillna(True).astype(bool)].copy()
    selected = selected[selected["chunk_type"].astype(str).ne("toc")].copy()
    selected = selected[selected["content"].str.strip().ne("")].copy()
    selected = selected.drop_duplicates(subset=["chunk_id"]).reset_index(drop=True)
    return selected

chunks_v1_raw = load_chunks(V1_CHUNKS_PATH)
chunks_v2_raw = load_chunks(V2_CHUNKS_PATH)
chunks_v1 = select_embedding_chunks(chunks_v1_raw)
chunks_v2 = select_embedding_chunks(chunks_v2_raw)

summary = pd.DataFrame([
    {"version": "v1", "raw_rows": len(chunks_v1_raw), "selected_rows": len(chunks_v1), "unique_docs": chunks_v1["doc_key"].nunique(), "duplicate_chunk_id": int(chunks_v1["chunk_id"].duplicated().sum()), "chunk_types": dict(chunks_v1_raw["chunk_type"].value_counts())},
    {"version": "v2", "raw_rows": len(chunks_v2_raw), "selected_rows": len(chunks_v2), "unique_docs": chunks_v2["doc_key"].nunique(), "duplicate_chunk_id": int(chunks_v2["chunk_id"].duplicated().sum()), "chunk_types": dict(chunks_v2_raw["chunk_type"].value_counts())},
])
display(summary)
display(chunks_v1[["chunk_id", "source_file", "chunk_type", "content"]].head(2))
display(chunks_v2[["chunk_id", "source_file", "chunk_type", "content"]].head(2))

,version,raw_rows,selected_rows,unique_docs,duplicate_chunk_id,chunk_types
0,v1,75912,75638,685,0,"{'text': 75638, 'toc': 274}"
1,v2,124740,124472,685,0,"{'table': 97278, 'text': 26506, 'fact_candidates': 691, 'toc': 265}"

,chunk_id,source_file,chunk_type,content
0,doc_c6761a6fb2b7_text_text_0001_part_001_9972157211c2,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n-1-\n제 안 요 청 서\n고려대학교\n차세대 포털·학사 정보시스템 구축 사업
1,doc_c6761a6fb2b7_text_text_0002_part_001_468c8342bef7,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,"[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n※ 본 자료는 제안내용의 설명을 위한 배포자료로, 이외 목적으로 무단복제, 전달 및 사용하는 행위를 금함.\n-2-"

,chunk_id,source_file,chunk_type,content
0,doc_c6761a6fb2b7_text_text_0001_part_001_9972157211c2,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n-1-\n제 안 요 청 서\n고려대학교\n차세대 포털·학사 정보시스템 구축 사업
1,doc_c6761a6fb2b7_text_text_0002_part_001_468c8342bef7,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,"[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n※ 본 자료는 제안내용의 설명을 위한 배포자료로, 이외 목적으로 무단복제, 전달 및 사용하는 행위를 금함.\n-2-"

In [6]:
def parse_list_cell(value) -> list[str]:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return []
    if isinstance(value, list):
        return value
    text = str(value).strip()
    if not text:
        return []
    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return [str(x) for x in parsed]
        return [str(parsed)]
    except Exception:
        if "|" in text:
            return [x.strip() for x in text.split("|") if x.strip()]
        return [text]


def load_eval_questions(eval_dir: Path, canonical_only: bool = True) -> pd.DataFrame:
    if canonical_only:
        csv_paths = [eval_dir / f"eval_batch_{idx:02d}.csv" for idx in range(1, 26)]
        missing = [str(path) for path in csv_paths if not path.exists()]
        if missing:
            raise FileNotFoundError(f"Missing canonical eval CSV files: {missing}")
    else:
        csv_paths = sorted(eval_dir.glob("eval_batch_*.csv"))
        if not csv_paths:
            raise FileNotFoundError(f"No eval CSV files under {eval_dir}")
    frames = []
    for csv_path in csv_paths:
        frame = pd.read_csv(csv_path)
        frame["source_eval_file"] = csv_path.name
        frames.append(frame)
    df = pd.concat(frames, ignore_index=True)
    required = ["id", "type", "difficulty", "question", "ground_truth_answer", "ground_truth_docs"]
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(f"Missing eval columns: {missing}")
    df["ground_truth_doc_list"] = df["ground_truth_docs"].apply(parse_list_cell)
    df["gt_doc_count"] = df["ground_truth_doc_list"].apply(len)
    return df

eval_df_all = load_eval_questions(EVAL_DIR, canonical_only=True)
if EVAL_SAMPLE_SIZE and EVAL_SAMPLE_SIZE > 0:
    eval_df = eval_df_all.sample(n=min(EVAL_SAMPLE_SIZE, len(eval_df_all)), random_state=EVAL_SAMPLE_SEED).sort_values(["source_eval_file", "id"]).reset_index(drop=True)
else:
    eval_df = eval_df_all.reset_index(drop=True)

print("eval all rows:", len(eval_df_all))
print("eval selected rows:", len(eval_df))
display(eval_df["gt_doc_count"].value_counts().sort_index().rename_axis("gt_doc_count").reset_index(name="rows"))
display(eval_df[["source_eval_file", "id", "question", "gt_doc_count", "ground_truth_doc_list"]].head(5))

eval all rows: 500
eval selected rows: 100

   gt_doc_count  rows
0             1    61
1             2    31
2             3     7
3             4     1

,source_eval_file,id,question,gt_doc_count,ground_truth_doc_list
0,eval_batch_01.csv,Q001,한국가스공사의 '차세대 통합정보시스템(ERP) 구축' 사업 예산 규모는 얼마입니까?,1,[한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp]
1,eval_batch_01.csv,Q003,코이카(KOICA) 전자조달의 '우즈베키스탄 열린 의정활동 상하원 국회 방송시스템 구축 및 지역의회 연계 개선 PMC 용역' 예산 규모는 어떻게 됩니까?,1,[KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp]
2,eval_batch_01.csv,Q010,국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다. 두 기관 중 어느 곳의 예산이 더 많이 배정되었나요?,2,"[국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp, 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp]"
3,eval_batch_01.csv,Q012,나노종합기술원의 스마트 팹 서비스 관련 설비온라인 사업과 부산국제영화제의 BIFF & ACFM 온라인서비스 재개발 사업의 추진 목적 및 예상되는 기대효과를 대비해서 요약해 주세요.,2,"[나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp, (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp]"
4,eval_batch_01.csv,Q016,"그렇다면 1단계와 2단계로 진행되는 이 용수공급사업의 전체 예산 중에서, 약 30%를 올해 기초 조사 및 기반 설계에 사용한다고 가정할 때 해당 금액은 총 얼마입니까?",1,[한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp]

In [7]:
embedding_model = SentenceTransformer(EMBEDDING_MODEL, device=EMBEDDING_DEVICE)
print("loaded embedding model:", EMBEDDING_MODEL)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/165 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/741 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

loaded embedding model: nlpai-lab/KoE5

In [8]:
def prefixed_passages(texts: list[str]) -> list[str]:
    return [f"passage: {text}" for text in texts]


def prefixed_queries(texts: list[str]) -> list[str]:
    return [f"query: {text}" for text in texts]


def encode_passages(texts: list[str], batch_size: int = EMBEDDING_BATCH_SIZE) -> np.ndarray:
    return embedding_model.encode(prefixed_passages(texts), batch_size=batch_size, normalize_embeddings=True, show_progress_bar=True, convert_to_numpy=True)


def encode_queries(texts: list[str], batch_size: int = EMBEDDING_BATCH_SIZE) -> np.ndarray:
    return embedding_model.encode(prefixed_queries(texts), batch_size=batch_size, normalize_embeddings=True, show_progress_bar=False, convert_to_numpy=True)


def metadata_value(value):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return ""
    if isinstance(value, (list, tuple, set)):
        return " > ".join(map(str, value))
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def make_chroma_metadata(row: pd.Series) -> dict[str, str]:
    base = {}
    meta = row.get("metadata", {})
    if isinstance(meta, dict):
        base.update(meta)
    source_ref = row.get("source_ref", {})
    if isinstance(source_ref, dict):
        for key in ["source_store_id", "block_id", "part_index", "content_hash"]:
            if key in source_ref:
                base[key] = source_ref.get(key, "")
    for key in ["doc_id", "doc_key", "source_file", "source_format", "chunk_id", "chunk_type", "fact_type", "fact_status", "fact_confidence"]:
        if key in row.index:
            base[key] = row.get(key, "")
    return {key: metadata_value(value) for key, value in base.items()}


def reset_collection(client, collection_name: str):
    if RECREATE_CHROMA_COLLECTIONS:
        try:
            client.delete_collection(collection_name)
            print("deleted existing collection:", collection_name)
        except Exception:
            pass
    return client.get_or_create_collection(name=collection_name, metadata={"hnsw:space": "cosine"})


def build_or_load_collection_streaming(df: pd.DataFrame, collection_name: str):
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    collection = reset_collection(client, collection_name)
    if collection.count() == len(df) and not RECREATE_CHROMA_COLLECTIONS:
        print("reuse existing collection:", collection_name, collection.count())
        return collection
    ids = df["chunk_id"].astype(str).tolist()
    docs = df["content"].astype(str).tolist()
    total = len(ids)
    for start in tqdm(range(0, total, CHROMA_ADD_BATCH_SIZE), desc=f"encode+chroma add {collection_name}"):
        end = min(start + CHROMA_ADD_BATCH_SIZE, total)
        batch_df = df.iloc[start:end]
        batch_docs = docs[start:end]
        batch_embeddings = encode_passages(batch_docs, batch_size=EMBEDDING_BATCH_SIZE)
        batch_metadatas = [make_chroma_metadata(row) for _, row in batch_df.iterrows()]
        collection.add(ids=ids[start:end], documents=batch_docs, embeddings=batch_embeddings.tolist(), metadatas=batch_metadatas)
    print("collection count:", collection_name, collection.count())
    return collection

collection_v1_name = f"rfp_p4_hwpx_{CORPUS_LIMIT}_v1_koe5"
collection_v2_name = f"rfp_p4_hwpx_{CORPUS_LIMIT}_v2_koe5"
collection_v1 = build_or_load_collection_streaming(chunks_v1, collection_v1_name)
collection_v2 = build_or_load_collection_streaming(chunks_v2, collection_v2_name)

encode+chroma add rfp_p4_hwpx_690_v1_koe5:   0%|          | 0/148 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

collection count: rfp_p4_hwpx_690_v1_koe5 75638

encode+chroma add rfp_p4_hwpx_690_v2_koe5:   0%|          | 0/244 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

collection count: rfp_p4_hwpx_690_v2_koe5 124472

In [9]:
def normalize_doc_name(value: str) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"\.(hwp|hwpx|pdf|json)$", "", text)
    text = re.sub(r"\s+", "", text)
    return text


def result_from_chroma_item(rank: int, doc: str, metadata: dict, distance: float, embedding=None) -> dict[str, Any]:
    score = 1.0 - float(distance) if distance is not None else math.nan
    return {"rank": rank, "filename": metadata.get("source_file", ""), "doc_id": metadata.get("doc_id", ""), "chunk_id": metadata.get("chunk_id", ""), "score": score, "text": doc, "metadata": metadata, "_embedding": embedding}


def dense_candidates(collection, question: str, n_results: int) -> tuple[list[dict[str, Any]], np.ndarray, float]:
    t0 = time.perf_counter()
    q_emb = encode_queries([question])[0]
    res = collection.query(query_embeddings=[q_emb.tolist()], n_results=n_results, include=["documents", "metadatas", "distances"])
    docs = res.get("documents", [[]])[0]
    metadatas = res.get("metadatas", [[]])[0]
    distances = res.get("distances", [[]])[0]
    embs = []
    items = []
    for idx, (doc, meta, dist) in enumerate(zip(docs, metadatas, distances), start=1):
        emb = embs[idx - 1] if len(embs) >= idx else None
        items.append(result_from_chroma_item(idx, doc, meta or {}, dist, emb))
    elapsed_ms = (time.perf_counter() - t0) * 1000
    return items, q_emb, elapsed_ms


def dedupe_by_doc(candidates: list[dict[str, Any]], k: int = FINAL_TOP_K) -> list[dict[str, Any]]:
    selected = []
    seen = set()
    for item in candidates:
        doc_key = normalize_doc_name(item.get("filename") or item.get("doc_id"))
        if not doc_key:
            doc_key = str(item.get("doc_id") or item.get("chunk_id"))
        if doc_key in seen:
            continue
        seen.add(doc_key)
        item = dict(item)
        item["rank"] = len(selected) + 1
        selected.append(item)
        if len(selected) >= k:
            break
    return selected


def bm25_tokenize(text: str) -> list[str]:
    terms = re.findall(r"[가-힣A-Za-z0-9]+", str(text).lower())
    tokens = []
    for term in terms:
        tokens.append(term)
        if re.search(r"[가-힣]", term) and len(term) >= 2:
            tokens.extend(term[i:i+2] for i in range(len(term)-1))
    return tokens


class BM25Index:
    def __init__(self, df: pd.DataFrame):
        self.df = df.reset_index(drop=True)
        tokenized = [bm25_tokenize(text) for text in tqdm(self.df["content"].astype(str).tolist(), desc="bm25 tokenize")]
        self.index = BM25Okapi(tokenized)

    def search(self, question: str, top_k: int) -> list[dict[str, Any]]:
        scores = self.index.get_scores(bm25_tokenize(question))
        order = np.argsort(scores)[::-1][:top_k]
        items = []
        for rank, idx in enumerate(order, start=1):
            row = self.df.iloc[int(idx)]
            items.append({"rank": rank, "filename": row.get("source_file", ""), "doc_id": row.get("doc_id", ""), "chunk_id": row.get("chunk_id", ""), "score": float(scores[idx]), "text": row.get("content", ""), "metadata": make_chroma_metadata(row)})
        return items


def rrf_fuse(result_lists: list[list[dict[str, Any]]], rrf_k: int = RRF_K, top_k: int = FINAL_TOP_K) -> list[dict[str, Any]]:
    by_chunk = {}
    for result_list in result_lists:
        for rank, item in enumerate(result_list, start=1):
            chunk_id = item.get("chunk_id")
            if not chunk_id:
                continue
            if chunk_id not in by_chunk:
                by_chunk[chunk_id] = dict(item)
                by_chunk[chunk_id]["rrf_score"] = 0.0
            by_chunk[chunk_id]["rrf_score"] += 1.0 / (rrf_k + rank)
    fused = sorted(by_chunk.values(), key=lambda item: item.get("rrf_score", 0.0), reverse=True)[:top_k]
    for rank, item in enumerate(fused, start=1):
        item["rank"] = rank
        item["score"] = float(item.get("rrf_score", item.get("score", 0.0)))
    return fused


def clean_contexts_for_json(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    clean = []
    for rank, item in enumerate(items, start=1):
        clean.append({"rank": rank, "filename": item.get("filename", ""), "doc_id": item.get("doc_id", ""), "chunk_id": item.get("chunk_id", ""), "score": float(item.get("score", 0.0)) if item.get("score") is not None else None, "text": item.get("text", ""), "metadata": item.get("metadata", {})})
    return clean


def context_signal_summary(contexts: list[dict[str, Any]]) -> dict[str, Any]:
    clean_contexts = clean_contexts_for_json(contexts)
    unique_docs = {normalize_doc_name(item.get("filename") or item.get("doc_id")) for item in clean_contexts if item.get("filename") or item.get("doc_id")}
    top1_score = clean_contexts[0].get("score") if clean_contexts else None
    return {"top1_score": top1_score, "top5_doc_count": len(unique_docs)}


def infer_retrieval_status(signal: dict[str, Any]) -> tuple[str, str]:
    if signal.get("top5_doc_count", 0) == 0:
        return "insufficient_context", "no_retrieved_context"
    top1_score = signal.get("top1_score")
    if ENABLE_COVERAGE_GATE and top1_score is not None and top1_score < MIN_TOP1_SCORE_FOR_WEAK_SIGNAL:
        return "weak_signal", "top1_score_below_threshold"
    return "sufficient_context", "retrieval_signal_passed"

bm25_v2 = BM25Index(chunks_v2)

bm25 tokenize:   0%|          | 0/124472 [00:00<?, ?it/s]

In [10]:
reranker = None
if RUN_RERANKER_EXPERIMENTS:
    reranker = CrossEncoder(RERANKER_MODEL, device=EMBEDDING_DEVICE)
    print("loaded reranker:", RERANKER_MODEL)
else:
    print("reranker disabled")


def rerank(question: str, candidates: list[dict[str, Any]], top_k: int = FINAL_TOP_K) -> tuple[list[dict[str, Any]], float]:
    if reranker is None:
        return candidates[:top_k], 0.0
    if not candidates:
        return [], 0.0
    t0 = time.perf_counter()
    pairs = [(question, item.get("text", "")) for item in candidates]
    scores = reranker.predict(pairs, batch_size=RERANK_BATCH_SIZE, show_progress_bar=False)
    reranked = []
    for item, score in zip(candidates, scores):
        updated = dict(item)
        updated["score"] = float(score)
        updated["rerank_score"] = float(score)
        reranked.append(updated)
    reranked = sorted(reranked, key=lambda item: item.get("rerank_score", 0.0), reverse=True)
    elapsed_ms = (time.perf_counter() - t0) * 1000
    for rank, item in enumerate(reranked[:top_k], start=1):
        item["rank"] = rank
    return reranked[:top_k], elapsed_ms

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

loaded reranker: BAAI/bge-reranker-v2-m3

In [11]:
@dataclass
class RetrievalExperiment:
    experiment_id: str
    corpus_name: str
    corpus_version: str
    retrieval_method: str
    collection: Any
    chunks_df: pd.DataFrame
    bm25: Any = None
    collection_name: str = ""
    dense_top_k: int = DENSE_TOP_K
    bm25_top_k: int = 0
    fetch_k: int = FINAL_TOP_K
    rrf_k: int = RRF_K
    reranker_model: str = ""
    rerank_top_k: int = 0
    final_top_k: int = FINAL_TOP_K
    use_hybrid: bool = False
    use_reranker: bool = False

experiments = [
    RetrievalExperiment(f"R0_p4_hwpx_{CORPUS_LIMIT}_v1_dense_top5", CORPUS_NAME, CORPUS_VERSION_V1, "dense", collection_v1, chunks_v1, collection_name=collection_v1_name, dense_top_k=FINAL_TOP_K, fetch_k=FINAL_TOP_K),
    RetrievalExperiment(f"R1_p4_hwpx_{CORPUS_LIMIT}_v2_dense_rerank_top5", CORPUS_NAME, CORPUS_VERSION_V2, "dense_rerank", collection_v2, chunks_v2, bm25=bm25_v2, collection_name=collection_v2_name, dense_top_k=DENSE_TOP_K, fetch_k=DENSE_TOP_K, use_reranker=True, reranker_model=RERANKER_MODEL, rerank_top_k=FINAL_TOP_K),
    RetrievalExperiment(f"R2_p4_hwpx_{CORPUS_LIMIT}_v2_hybrid_rrf_rerank_top5", CORPUS_NAME, CORPUS_VERSION_V2, "hybrid_rrf_rerank", collection_v2, chunks_v2, bm25=bm25_v2, collection_name=collection_v2_name, dense_top_k=DENSE_TOP_K, bm25_top_k=BM25_TOP_K, fetch_k=DENSE_TOP_K, use_hybrid=True, use_reranker=True, reranker_model=RERANKER_MODEL, rerank_top_k=FINAL_TOP_K),
]
if not RUN_RERANKER_EXPERIMENTS:
    experiments = [exp for exp in experiments if not exp.use_reranker]

pd.DataFrame([{"experiment_id": exp.experiment_id, "corpus_version": exp.corpus_version, "retrieval_method": exp.retrieval_method, "collection": exp.collection_name, "chunks": len(exp.chunks_df), "dense_top_k": exp.dense_top_k, "bm25_top_k": exp.bm25_top_k, "reranker": exp.use_reranker} for exp in experiments])

,experiment_id,corpus_version,retrieval_method,collection,chunks,dense_top_k,bm25_top_k,reranker
0,R0_p4_hwpx_690_v1_dense_top5,v1_clean_text,dense,rfp_p4_hwpx_690_v1_koe5,75638,5,0,False
1,R1_p4_hwpx_690_v2_dense_rerank_top5,v2_hwpx_table_aware,dense_rerank,rfp_p4_hwpx_690_v2_koe5,124472,30,0,True
2,R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5,v2_hwpx_table_aware,hybrid_rrf_rerank,rfp_p4_hwpx_690_v2_koe5,124472,30,30,True

In [12]:
def retrieve_one(question: str, exp: RetrievalExperiment) -> tuple[list[dict[str, Any]], float, float, float]:
    retrieval_start = time.perf_counter()
    rerank_ms = 0.0
    dense_items, q_emb, dense_ms = dense_candidates(exp.collection, question, n_results=exp.fetch_k)
    if exp.use_hybrid:
        bm25_items = exp.bm25.search(question, top_k=exp.bm25_top_k) if exp.bm25 is not None else []
        rrf_top_k = exp.fetch_k if exp.use_reranker else exp.final_top_k
        candidates = rrf_fuse([dense_items, bm25_items], rrf_k=exp.rrf_k, top_k=rrf_top_k)
    else:
        candidates = dense_items[:exp.fetch_k]
    if exp.use_reranker:
        candidates, rerank_ms = rerank(question, candidates, top_k=exp.final_top_k)
    final_contexts = dedupe_by_doc(candidates, k=exp.final_top_k)
    total_ms = (time.perf_counter() - retrieval_start) * 1000
    retrieval_ms = total_ms - rerank_ms
    return final_contexts, retrieval_ms, rerank_ms, total_ms


def retriever_config(exp: RetrievalExperiment) -> dict[str, Any]:
    return {
        "experiment_id": exp.experiment_id, "corpus_name": exp.corpus_name, "corpus_version": exp.corpus_version, "corpus_coverage": CORPUS_COVERAGE,
        "embedding_model": EMBEDDING_MODEL, "embedding_device": EMBEDDING_DEVICE_LABEL, "vector_db": "chroma", "collection_name": exp.collection_name,
        "retrieval_method": exp.retrieval_method, "retriever_type": exp.retrieval_method, "dense_top_k": exp.dense_top_k, "bm25_top_k": exp.bm25_top_k,
        "fetch_k": exp.fetch_k, "rrf_k": exp.rrf_k if exp.use_hybrid else "", "reranker": bool(exp.use_reranker), "reranker_model": exp.reranker_model,
        "rerank_top_k": exp.rerank_top_k, "final_top_k": exp.final_top_k, "chunk_size": CHUNK_SIZE, "chunk_overlap": CHUNK_OVERLAP,
        "toc_policy": "excluded_from_embedding", "metadata_boost": False, "doc_dedup": True, "coverage_gate_enabled": ENABLE_COVERAGE_GATE,
        "min_top1_score_for_weak_signal": MIN_TOP1_SCORE_FOR_WEAK_SIGNAL, "unverified_answer": UNVERIFIED_ANSWER,
        "eval_sample_size": EVAL_SAMPLE_SIZE, "eval_sample_seed": EVAL_SAMPLE_SEED, "save_embedding_cache": SAVE_EMBEDDING_CACHE,
    }


def write_predictions(exp: RetrievalExperiment, eval_df: pd.DataFrame) -> Path:
    pred_path = PREDICTION_DIR / f"{exp.experiment_id}_predictions.jsonl"
    config = retriever_config(exp)
    with pred_path.open("w", encoding="utf-8") as f:
        for _, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc=exp.experiment_id):
            contexts, retrieval_ms, rerank_ms, total_ms = retrieve_one(row["question"], exp)
            signal = context_signal_summary(contexts)
            retrieval_status, coverage_reason = infer_retrieval_status(signal)
            record = {"id": row["id"], "source_eval_file": row.get("source_eval_file", ""), "question": row["question"], "answer": "", "retrieved_contexts": clean_contexts_for_json(contexts), "corpus_coverage": CORPUS_COVERAGE, "retrieval_status": retrieval_status, "coverage_reason": coverage_reason, "top1_score": signal["top1_score"], "top5_doc_count": signal["top5_doc_count"], "latency_ms": total_ms, "retrieval_ms": retrieval_ms, "rerank_ms": rerank_ms, "model_name": "retrieval_only", "embedding_model": EMBEDDING_MODEL, "retriever_config": config}
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    return pred_path

prediction_paths = []
for exp in experiments:
    path = write_predictions(exp, eval_df)
    prediction_paths.append((exp, path))
    print(exp.experiment_id, path)

R0_p4_hwpx_690_v1_dense_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R0_p4_hwpx_690_v1_dense_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_690_v1_dense_top5_predictions.jsonl

R1_p4_hwpx_690_v2_dense_rerank_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R1_p4_hwpx_690_v2_dense_rerank_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_690_v2_dense_rerank_top5_predictions.jsonl

R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5_predictions.jsonl

In [13]:
def run_extended_eval(exp: RetrievalExperiment, pred_path: Path):
    if not EXTENDED_EVAL_SCRIPT.exists():
        raise FileNotFoundError(EXTENDED_EVAL_SCRIPT)
    cmd = [sys.executable, str(EXTENDED_EVAL_SCRIPT), "--project-root", str(PROJECT_ROOT), "--eval-dir", str(EVAL_DIR), "--predictions", str(pred_path), "--output-dir", str(OUTPUT_DIR), "--prediction-ids-only", "--top-k", str(exp.final_top_k), "--experiment-id", exp.experiment_id, "--experiment-name", exp.retrieval_method, "--eval-scope", "sample" if EVAL_SAMPLE_SIZE else "canonical_01_25", "--notes", f"P4 HWPX quickcheck; corpus={exp.corpus_name}/{exp.corpus_version}; eval_batch_01_25; sample_size={EVAL_SAMPLE_SIZE}"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(" ".join(cmd))
    print(result.stdout[-2500:])
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(f"extended eval failed: {exp.experiment_id}")

for exp, pred_path in prediction_paths:
    run_extended_eval(exp, pred_path)

summary_log = OUTPUT_DIR / "experiment_logs" / "retrieval_experiments.csv"
summary_df = pd.read_csv(summary_log)
current = summary_df[summary_df["experiment_id"].isin([exp.experiment_id for exp in experiments])].tail(len(experiments))
metric_cols = ["experiment_id", "num_eval_questions", "hit_at_5_any", "mrr_at_5", "ndcg_at_5", "doc_recall_at_5", "single_doc_mrr_at_5", "multi_doc_ndcg_at_5", "retrieval_ms_p95", "rerank_ms_avg", "total_retrieval_ms_avg"]
display(current[metric_cols])

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_690_v1_dense_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R0_p4_hwpx_690_v1_dense_top5 --experiment-name dense --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_690/v1_clean_text; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R0_p4_hwpx_690_v1_dense_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R0_p4_hwpx_690_v1_dense_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R0_p4_hwpx_690_v1_dense_top5",
  "experiment_name": "dense",
  "run_datetime": "2026-05-19T12:56:04",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_690/v1_clean_text; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_690_v1_dense_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 99,
  "num_weak_signal": 1,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_690",
  "corpus_version": "v1_clean_text",
  "corpus_coverage": "p4_hwpx_full_690",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_690_v1_koe5",
  "retrieval_method": "dense",
  "dense_top_k": 5,
  "bm25_top_k": 0,
  "fetch_k": 5,
  "rrf_k": "",
  "reranker": false,
  "reranker_model": "",
  "rerank_top_k": 0,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.86,
  "all_gold_docs_hit_at_5": 0.64,
  "mrr_at_5": 0.7986666666666666,
  "ndcg_at_5": 0.7259486764573243,
  "doc_recall_at_5": 0.7441666666666668,
  "single_doc_mrr_at_5": 0.7491803278688525,
  "multi_doc_ndcg_at_5": 0.6688410824412361,
  "multi_doc_recall_at_5": 0.6517094017094016,
  "retrieval_ms_avg": 24.543042339983003,
  "retrieval_ms_p95": 25.444765049451235,
  "rerank_ms_avg": 0.0,
  "total_retrieval_ms_avg": 24.543042339983003
}

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_690_v2_dense_rerank_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R1_p4_hwpx_690_v2_dense_rerank_top5 --experiment-name dense_rerank --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_690/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R1_p4_hwpx_690_v2_dense_rerank_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R1_p4_hwpx_690_v2_dense_rerank_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R1_p4_hwpx_690_v2_dense_rerank_top5",
  "experiment_name": "dense_rerank",
  "run_datetime": "2026-05-19T12:56:05",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_690/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_690_v2_dense_rerank_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 92,
  "num_weak_signal": 8,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_690",
  "corpus_version": "v2_hwpx_table_aware",
  "corpus_coverage": "p4_hwpx_full_690",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_690_v2_koe5",
  "retrieval_method": "dense_rerank",
  "dense_top_k": 30,
  "bm25_top_k": 0,
  "fetch_k": 30,
  "rrf_k": "",
  "reranker": true,
  "reranker_model": "BAAI/bge-reranker-v2-m3",
  "rerank_top_k": 5,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.95,
  "all_gold_docs_hit_at_5": 0.75,
  "mrr_at_5": 0.9283333333333332,
  "ndcg_at_5": 0.8528758340674087,
  "doc_recall_at_5": 0.8483333333333333,
  "single_doc_mrr_at_5": 0.8989071038251365,
  "multi_doc_ndcg_at_5": 0.766533183231449,
  "multi_doc_recall_at_5": 0.7136752136752137,
  "retrieval_ms_avg": 31.142896920091516,
  "retrieval_ms_p95": 34.16333715063047,
  "rerank_ms_avg": 1623.6353619099464,
  "total_retrieval_ms_avg": 1654.7782588300379
}

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 --experiment-name hybrid_rrf_rerank --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_690/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5",
  "experiment_name": "hybrid_rrf_rerank",
  "run_datetime": "2026-05-19T12:56:06",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_690/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 94,
  "num_weak_signal": 6,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_690",
  "corpus_version": "v2_hwpx_table_aware",
  "corpus_coverage": "p4_hwpx_full_690",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_690_v2_koe5",
  "retrieval_method": "hybrid_rrf_rerank",
  "dense_top_k": 30,
  "bm25_top_k": 30,
  "fetch_k": 30,
  "rrf_k": 60,
  "reranker": true,
  "reranker_model": "BAAI/bge-reranker-v2-m3",
  "rerank_top_k": 5,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.99,
  "all_gold_docs_hit_at_5": 0.78,
  "mrr_at_5": 0.9558333333333334,
  "ndcg_at_5": 0.8884833552486536,
  "doc_recall_at_5": 0.8916666666666666,
  "single_doc_mrr_at_5": 0.9275956284153006,
  "multi_doc_ndcg_at_5": 0.8049728192950292,
  "multi_doc_recall_at_5": 0.7478632478632478,
  "retrieval_ms_avg": 4349.095299950031,
  "retrieval_ms_p95": 7879.963771350366,
  "rerank_ms_avg": 1598.1543822599997,
  "total_retrieval_ms_avg": 5947.249682210031
}

,experiment_id,num_eval_questions,hit_at_5_any,mrr_at_5,ndcg_at_5,doc_recall_at_5,single_doc_mrr_at_5,multi_doc_ndcg_at_5,retrieval_ms_p95,rerank_ms_avg,total_retrieval_ms_avg
3,R0_p4_hwpx_690_v1_dense_top5,100,0.86,0.798667,0.725949,0.744167,0.749180,0.668841,25.444765,0.000000,24.543042
4,R1_p4_hwpx_690_v2_dense_rerank_top5,100,0.95,0.928333,0.852876,0.848333,0.898907,0.766533,34.163337,1623.635362,1654.778259
5,R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5,100,0.99,0.955833,0.888483,0.891667,0.927596,0.804973,7879.963771,1598.154382,5947.249682

In [14]:
# ===== Qualitative preview: 5 questions x R0/R1/R2 =====
PREVIEW_N_QUESTIONS = 5
MAX_TEXT_CHARS = 500

pred_cache = {}
for exp, pred_path in prediction_paths:
    with pred_path.open("r", encoding="utf-8") as f:
        pred_cache[exp.experiment_id] = [json.loads(line) for line in f if line.strip()]
selected_keys = []
for row in pred_cache[experiments[0].experiment_id][:PREVIEW_N_QUESTIONS]:
    selected_keys.append((row.get("source_eval_file", ""), str(row.get("id", ""))))
for source_eval_file, qid in selected_keys:
    base_row = next((r for r in pred_cache[experiments[0].experiment_id] if r.get("source_eval_file", "") == source_eval_file and str(r.get("id", "")) == qid), None)
    if not base_row:
        continue
    print("\n" + "=" * 100)
    print(f"[{source_eval_file} / {qid}] {base_row.get('question')}")
    gt = eval_df[(eval_df["source_eval_file"].astype(str) == source_eval_file) & (eval_df["id"].astype(str) == qid)]
    if not gt.empty:
        print("GT docs:", gt.iloc[0].get("ground_truth_doc_list"))
    for exp in experiments:
        rows = [r for r in pred_cache[exp.experiment_id] if r.get("source_eval_file", "") == source_eval_file and str(r.get("id", "")) == qid]
        if not rows:
            continue
        rec = rows[0]
        print("\n---", exp.experiment_id, "---")
        for ctx in rec.get("retrieved_contexts", [])[:FINAL_TOP_K]:
            text = str(ctx.get("text", "")).replace("\n", " ")
            if len(text) > MAX_TEXT_CHARS:
                text = text[:MAX_TEXT_CHARS].rstrip() + " ..."
            print(f"#{ctx.get('rank')} score={ctx.get('score'):.4f} file={ctx.get('filename')} chunk={ctx.get('chunk_id')}")
            print(text)

====================================================================================================
[eval_batch_01.csv / Q001] 한국가스공사의 '차세대 통합정보시스템(ERP) 구축' 사업 예산 규모는 얼마입니까?
GT docs: ['한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp']

--- R0_p4_hwpx_690_v1_dense_top5 ---
#1 score=0.7065 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_35ceab976987
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 [표 | 섹션: Ⅲ. 일반사항 | rows: 1 | cols: 3] 컬럼: Ⅰ | col_2 | 개요 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐 ...

--- R1_p4_hwpx_690_v2_dense_rerank_top5 ---
#1 score=0.9116 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_48fffb407f32
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐색‧활용 간소화로 사용자 편의 및 데이터 기반의 업무환경 마련 * KOGAS 디지털 전환 전략 수립 설 ...

--- R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9116 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_48fffb407f32
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐색‧활용 간소화로 사용자 편의 및 데이터 기반의 업무환경 마련 * KOGAS 디지털 전환 전략 수립 설 ...

====================================================================================================
[eval_batch_01.csv / Q003] 코이카(KOICA) 전자조달의 '우즈베키스탄 열린 의정활동 상하원 국회 방송시스템 구축 및 지역의회 연계 개선 PMC 용역' 예산 규모는 어떻게 됩니까?
GT docs: ['KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp']

--- R0_p4_hwpx_690_v1_dense_top5 ---
#1 score=0.7420 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0002_part_003_1999c2e64aef
위한 정보시스템 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 열린 의정활동을 위한 상하원 국회 방송시스템 구축 및 지역의회와의 연계 기반 개선사업 PMC 용역 ㅇ (영문명) PMC Service for the System for the Project on Increasing the Openness of the Senate and LCOM in Uzbekistan through the Implementation of Parliament Broadcasting System and Improvement of Connection with Regional and Local Councils 나. 용역기간 : 계약체결일로부터 2027년 9월 30일까지 다. 대 상 지 : 우즈베키스탄 타슈켄트시, 12개 주(州) 및 카라칼팍스탄 공화국
#2 score=0.6447 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp chunk=doc_bf8e796b625c_text_text_0004_part_001_7181a9affcb0
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] 약어: WAS | 영어 표기: Web Application Server | 한글 명칭: 웹 어플리케이션 서버 약어: WEB | 영어 표기: World Wide Web | 한글 명칭: 월드와이드웹(인터넷) 약어: WUA | 영어 표기: Water User Association | 한글 명칭: 물 사용자 협의체 약어: XML | 영어 표기: eXtensible Markup Language | 한글 명칭: W3C에서 개발된 이기종 데이터 연동 마크업 언어 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 ...

--- R1_p4_hwpx_690_v2_dense_rerank_top5 ---
#1 score=0.9997 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0003_part_001_9fa9ea7f65e7
[문서: KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp | 사업명: [긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] - 2025년: 3,189,242,057원($2,453,263/1$=1,300원, 2024년 기준환율) - 2026년: 1,784,664,718원($1,372,819/1$=1,300원, 2024년 기준환율) ※ 부가가치세 등 제반 비용 포함하는 사업임. 마. 용역범위 ㅇ 국회 방송시스템 및 지역의회간 연계 기반 구축을 위한 기자재 조달업체 선정 및 운영지원 ㅇ 대국민 국회방송을 위한 응용시스템 개발 ㅇ 시스템 구축을 위한 기반 설비 구축(수원기관 분담) 지원 ㅇ 국회 구성원에 대한 역량강화 ㅇ 사업관리 및 성과관리 2. 기본방향 가. 사업목표 ㅇ (장기) 우즈베키스탄 국회의 투명성 강화 및 참여 민주주의 구현 ㅇ (중기) 우즈베키스탄 국회 ...
#2 score=0.9057 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp chunk=doc_bf8e796b625c_table_table_0001_part_001_ae9cafc976da
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 2 | cols: 1] 컬럼: col_1 그룹: 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 수립 및 시설기반강화 시범사업 사후관리 PMC 용역 / (2023-2024/64만불) 그룹: 제안요청서

--- R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9997 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0003_part_001_9fa9ea7f65e7
[문서: KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp | 사업명: [긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] - 2025년: 3,189,242,057원($2,453,263/1$=1,300원, 2024년 기준환율) - 2026년: 1,784,664,718원($1,372,819/1$=1,300원, 2024년 기준환율) ※ 부가가치세 등 제반 비용 포함하는 사업임. 마. 용역범위 ㅇ 국회 방송시스템 및 지역의회간 연계 기반 구축을 위한 기자재 조달업체 선정 및 운영지원 ㅇ 대국민 국회방송을 위한 응용시스템 개발 ㅇ 시스템 구축을 위한 기반 설비 구축(수원기관 분담) 지원 ㅇ 국회 구성원에 대한 역량강화 ㅇ 사업관리 및 성과관리 2. 기본방향 가. 사업목표 ㅇ (장기) 우즈베키스탄 국회의 투명성 강화 및 참여 민주주의 구현 ㅇ (중기) 우즈베키스탄 국회 ...
#2 score=0.9057 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp chunk=doc_bf8e796b625c_table_table_0001_part_001_ae9cafc976da
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 2 | cols: 1] 컬럼: col_1 그룹: 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 수립 및 시설기반강화 시범사업 사후관리 PMC 용역 / (2023-2024/64만불) 그룹: 제안요청서

====================================================================================================
[eval_batch_01.csv / Q010] 국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다. 두 기관 중 어느 곳의 예산이 더 많이 배정되었나요?
GT docs: ['국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp', '한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp']

--- R0_p4_hwpx_690_v1_dense_top5 ---
#1 score=0.6247 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_caa26f6adb1a
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 [표 | 섹션: Ⅰ. 사업 개요 | rows: 1 | cols: 4] 컬럼: 1 | col_2 | 사업 안내 | col_4 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 [표 | 섹션: Ⅰ. 사업 개요 | rows: 1 | cols: 4] 컬럼: 2 | col_2 | 추진배경 및 필요성 | col_4 가. 응급의료는 국민의 생명과 직결되는 대표적인 필 ...

--- R1_p4_hwpx_690_v2_dense_rerank_top5 ---
#1 score=0.6838 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_a0203e4c12a5
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 가. 응급의료는 국민의 생명과 직결되는 대표적인 필수의료 분야이나 최근 응급실 뺑뺑이 사건 등 병원 전 단계에서 치료 가능한 응급실 섭외 지연 문제 발생 나. 병원간 이송(이하 “전원”)이 현 응급의료에서 가장 취약한 영역 - 응급실로 내원 중증환자(KTAS 1,2)의 13.5%(‘22년 기준)가 전원을 ...

--- R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.6838 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_a0203e4c12a5
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 가. 응급의료는 국민의 생명과 직결되는 대표적인 필수의료 분야이나 최근 응급실 뺑뺑이 사건 등 병원 전 단계에서 치료 가능한 응급실 섭외 지연 문제 발생 나. 병원간 이송(이하 “전원”)이 현 응급의료에서 가장 취약한 영역 - 응급실로 내원 중증환자(KTAS 1,2)의 13.5%(‘22년 기준)가 전원을 ...

====================================================================================================
[eval_batch_01.csv / Q012] 나노종합기술원의 스마트 팹 서비스 관련 설비온라인 사업과 부산국제영화제의 BIFF & ACFM 온라인서비스 재개발 사업의 추진 목적 및 예상되는 기대효과를 대비해서 요약해 주세요.
GT docs: ['나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp', '(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp']

--- R0_p4_hwpx_690_v1_dense_top5 ---
#1 score=0.6013 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0002_part_001_674f23b54cb6
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] ○ 행사 지원시스템에 대하여, 행사 진행 공간의 유동성을 위해 요청에 따라 모바일 웹 또는 앱 형태로 제공하여 휴대성과 편의성을 제고한다. ○ 영화제 임박기간 전문 인력을 파견하여, 생성되는 각종 콘텐츠와 페이지 제작 업무를 진행하며, 발생하는 다양한 변수를 신속하고 안정적으로 해결한다. ○ 개발 및 제공하는 모든 사이트의 사용자 수, 이벤트 수, 페이지뷰 수 등의 접속 통계 자료를 제공한다. ○ 각종 웹사이트와 시스템 기획 및 개발, 디자인 요청 등의 다양한 전산요청을 위해 상태 체크(전체, 접수, 진행, 완료) 및 파일 첨부가 가능한 온라인 헬프데스크를 공급, 운영하여 부서별 발생하는 요청사항을 빠르고 효과적으로 처리한다. 3 ...
#2 score=0.5686 file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp chunk=doc_7ce4da44d9e9_text_text_0003_part_003_d1f05205c2d8
신뢰성 및 양산 적합성 검증·인정 등 제 [표 | 섹션: 문서 시작 | rows: 1 | cols: 1] 컬럼: col_1 그룹: 출처 : 제5기 나노기술종합발전계획 [ 나노융합 현장수요기반 실증지원 ] [표 | 섹션: 문서 시작 | rows: 3 | cols: 1] 컬럼: col_1 그룹: 2 그룹: 사업 추진계획 2.1. 추진목표 [표 | 섹션: 문서 시작 | rows: 1 | cols: 1] 컬럼: col_1 col_1: ○ 기술원 FAB 스마트 팹 서비스 활용체계 구축관련 설비 온라인 시스템 구축 용역으로 설비 데이터 수집체계 마련 및 LoT Tracking 구현을 통해 Lot 관리의 정보화 수준 향상

--- R1_p4_hwpx_690_v2_dense_rerank_top5 ---
#1 score=0.9941 file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp chunk=doc_7ce4da44d9e9_text_text_0003_part_001_af2b317da780
[문서: 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp | 사업명: 스마트 팹 서비스 활용체계 구축관련 설비온라인 시스 | 발주기관: 나노종합기술원 | 섹션: 문서 시작 | 유형: text] ○ 공정 설비(장비)의 특성 진단 및 문제점 도출과 데이터 취합을 위한 개선 방향 제시 ○ 추진 각 단계별 범위 정의와 구축 이행 방안 및 소요예산 산정 제시 ○ 단계별 이행을 통해 예상되는 기대효과 제시 1.5. 시스템 구성현황 □ 新공정관리시스템 구성 현황 ○ H/W 및 S/W 구성현황 1.6. 기대효과 □ 기술적 측면 ○ 연구개발 소요시간 및 비용 단축(축적 데이터 활용, 실패 감소, 불량률 감소 등)에 따라, 산학연 기술개발 조기 사업화 및 성공률 제고 기여 - 빅데이터 기반의 나노팹 서비스 내재화를 통한 연구 개발 소요시간 감축을 통한 Time-to-Market 실현으로 반도체 기업 기술개발 경쟁력 제고 기여 - 데이터 사이언스에 입각한 장비 및 시설 관리체계 ...
#2 score=0.9478 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0001_part_001_46acae61579e
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] 2024. 6. 1. 사업개요 가. 사 업 명 : BIFF&ACFM 온라인서비스 재개발 및 행사지원시스템 공급 사업 나. 기 간 : 계약체결일 ~ 2025. 05. 31. 다. 사업예산 : 금243,000,000원(금이억사천삼백만 원) (VAT 포함) 라. 입찰방식 : 제한 경쟁입찰(지역 제한) 마. 계약방법 : 협상에 의한 계약 2. 사업목표 ○ 웹 표준, 웹 접근성 및 웹 UI에 대한 기능개선으로 사용자 중심의 웹서비스를 제공한다. ○ BIFF, ACFM에서 운영 중인 웹사이트에 대하여, 당해 연도의 독창적인 디자인 UI 적용, 최신 트렌트를 반영하여 브랜드 가치 제고. ○ BIFF, ACFM 각종 접수 및 참가 시스템을 당해 ...

--- R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9941 file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp chunk=doc_7ce4da44d9e9_text_text_0003_part_001_af2b317da780
[문서: 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp | 사업명: 스마트 팹 서비스 활용체계 구축관련 설비온라인 시스 | 발주기관: 나노종합기술원 | 섹션: 문서 시작 | 유형: text] ○ 공정 설비(장비)의 특성 진단 및 문제점 도출과 데이터 취합을 위한 개선 방향 제시 ○ 추진 각 단계별 범위 정의와 구축 이행 방안 및 소요예산 산정 제시 ○ 단계별 이행을 통해 예상되는 기대효과 제시 1.5. 시스템 구성현황 □ 新공정관리시스템 구성 현황 ○ H/W 및 S/W 구성현황 1.6. 기대효과 □ 기술적 측면 ○ 연구개발 소요시간 및 비용 단축(축적 데이터 활용, 실패 감소, 불량률 감소 등)에 따라, 산학연 기술개발 조기 사업화 및 성공률 제고 기여 - 빅데이터 기반의 나노팹 서비스 내재화를 통한 연구 개발 소요시간 감축을 통한 Time-to-Market 실현으로 반도체 기업 기술개발 경쟁력 제고 기여 - 데이터 사이언스에 입각한 장비 및 시설 관리체계 ...
#2 score=0.9478 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0001_part_001_46acae61579e
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] 2024. 6. 1. 사업개요 가. 사 업 명 : BIFF&ACFM 온라인서비스 재개발 및 행사지원시스템 공급 사업 나. 기 간 : 계약체결일 ~ 2025. 05. 31. 다. 사업예산 : 금243,000,000원(금이억사천삼백만 원) (VAT 포함) 라. 입찰방식 : 제한 경쟁입찰(지역 제한) 마. 계약방법 : 협상에 의한 계약 2. 사업목표 ○ 웹 표준, 웹 접근성 및 웹 UI에 대한 기능개선으로 사용자 중심의 웹서비스를 제공한다. ○ BIFF, ACFM에서 운영 중인 웹사이트에 대하여, 당해 연도의 독창적인 디자인 UI 적용, 최신 트렌트를 반영하여 브랜드 가치 제고. ○ BIFF, ACFM 각종 접수 및 참가 시스템을 당해 ...

====================================================================================================
[eval_batch_01.csv / Q016] 그렇다면 1단계와 2단계로 진행되는 이 용수공급사업의 전체 예산 중에서, 약 30%를 올해 기초 조사 및 기반 설계에 사용한다고 가정할 때 해당 금액은 총 얼마입니까?
GT docs: ['한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp']

--- R0_p4_hwpx_690_v1_dense_top5 ---
#1 score=0.5346 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_text_text_0023_part_001_63ec5dd86128
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: text] (4) 기본계획(안) 수립 ① 계약상대자는 동 과업과 관련된 관계 법령에서 정하는 기본계획 작성을 위한 기초 조사를 수행하여 기본계획 협의자료 및 협의에 필요한 각종 인․허가 자료를 감독원과 사전 협의하여 작성․제출하여야 하며, 용인 첨단 시스템반도체 국가산단 용수공급사업 추진관련 된 타 조사 및 용역의 검토 내용을 충실히 반영하여 종합적인 검토가 될 수 있도록 하여야 한다. ② 기본계획 작성 시는 관련규정에 의거 시행하여야 하는 제반 검토 사항에 대하여 감독원과 협의하여 검토 반영하고 관련기관 및 지역주민 등과의 협의과정에서 제시된 사항에 대하여도 추가 검토하여 반영하여야 하며, 다음 각 호의 사항은 반드시 포함되어야 한다. 가. 사업의 목표 및 기본 방향 나. 사업 ...

--- R1_p4_hwpx_690_v2_dense_rerank_top5 ---
#1 score=0.2690 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_table_table_0004_part_001_de2e2d9e8830
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 6 | cols: 6] 컬럼: 구 분 | col_2 | 전 체 | 1단계 | 2단계 | 비 고 구 분: 공 급 량 | 전 체: 80만㎥/일 | 1단계: 20만㎥/일 | 2단계: 60만㎥/일 | 비 고: - 구 분: 사업기간 | 전 체: ’24년~`34년 | 1단계: ’24년~’30년 | 2단계: ’24년~`34년 구 분: 시설 | col_2: 취수장 | 전 체: 취수장 1개소 | 1단계: - | 2단계: 취수장 1개소 col_2: 가압장 | 전 체: 가압장 4개소 | 1단계: 가압장 2개소 | 2단계: 가압장 2개소 col_2: 관 로 | 전 체: D1,500mm, L=34.5km / / D2,200mm, L=48.4km | ...

--- R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.2690 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_table_table_0004_part_001_de2e2d9e8830
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 6 | cols: 6] 컬럼: 구 분 | col_2 | 전 체 | 1단계 | 2단계 | 비 고 구 분: 공 급 량 | 전 체: 80만㎥/일 | 1단계: 20만㎥/일 | 2단계: 60만㎥/일 | 비 고: - 구 분: 사업기간 | 전 체: ’24년~`34년 | 1단계: ’24년~’30년 | 2단계: ’24년~`34년 구 분: 시설 | col_2: 취수장 | 전 체: 취수장 1개소 | 1단계: - | 2단계: 취수장 1개소 col_2: 가압장 | 전 체: 가압장 4개소 | 1단계: 가압장 2개소 | 2단계: 가압장 2개소 col_2: 관 로 | 전 체: D1,500mm, L=34.5km / / D2,200mm, L=48.4km | ...

## 해석 기준

- `R0`: 구조화하지 않은 clean text baseline입니다. v2가 의미 있는지 비교하는 기준선입니다.
- `R1`: dense 검색 결과 30개를 reranker로 재정렬합니다. 이전 실험의 R4 조건입니다.
- `R2`: dense + BM25를 RRF로 합친 뒤 reranker를 적용합니다. 이전 실험의 R6 조건입니다.
- eval은 기본 100개 sample입니다. 전체 500문항을 보려면 `EVAL_SAMPLE_SIZE = 0`으로 바꿔서 다시 실행하면 됩니다.

## Failure Analysis

To keep notebook output readable, this section uses compact summaries first and full details only through selected CASE_ID values. Full analysis rows are saved as CSV.

In [15]:
# ===== Failure Analysis: build data and compact summaries =====
from pathlib import Path
import json
import re
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 12)
pd.set_option("display.max_colwidth", 70)
pd.set_option("display.width", 140)


def _normalize_doc_name_for_analysis(value: str) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"\.(hwp|hwpx|pdf|json)$", "", text)
    text = re.sub(r"\s+", "", text)
    return text


def _load_prediction_jsonl(path: Path) -> pd.DataFrame:
    rows = []
    with Path(path).open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return pd.DataFrame(rows)


def _safe_contexts(value):
    return value if isinstance(value, list) else []


def _context_doc_names(contexts):
    docs = []
    for ctx in _safe_contexts(contexts):
        filename = ctx.get("filename") or ctx.get("metadata", {}).get("source_file") or ctx.get("doc_id", "")
        docs.append(str(filename))
    return docs


def _context_chunk_types(contexts):
    chunk_types = []
    for ctx in _safe_contexts(contexts):
        meta = ctx.get("metadata") or {}
        chunk_types.append(str(meta.get("chunk_type", ctx.get("chunk_type", ""))))
    return chunk_types


def _hit_any_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    return int(bool(pred_norm & gt_norm))


def _all_gold_docs_hit_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    if not gt_norm:
        return 0
    return int(gt_norm.issubset(pred_norm))


def _doc_recall_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    if not gt_norm:
        return np.nan
    return len(pred_norm & gt_norm) / len(gt_norm)


def _rank_first_gold(pred_docs, gt_docs, k=5):
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    for idx, doc in enumerate(pred_docs[:k], start=1):
        if _normalize_doc_name_for_analysis(doc) in gt_norm:
            return idx
    return None


def _short(value, max_chars=70):
    if isinstance(value, (list, tuple, set)):
        text = " | ".join(map(str, value))
    else:
        text = str(value)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= max_chars else text[:max_chars].rstrip() + " ..."


def _display_title(title):
    print()
    print("=" * 100)
    print(title)

try:
    _prediction_paths = prediction_paths
except NameError:
    _prediction_paths = []

if not _prediction_paths:
    pred_dir = PREDICTION_DIR if "PREDICTION_DIR" in globals() else Path(PROJECT_ROOT) / "outputs" / "retrieval_eval_p4_hwpx" / "predictions"
    pred_files = sorted(Path(pred_dir).glob("R*_p4_hwpx_*_predictions.jsonl"))
    _prediction_paths = []
    for pred_path in pred_files:
        exp_id = pred_path.name.replace("_predictions.jsonl", "")
        dummy_exp = type("ExperimentRef", (), {"experiment_id": exp_id, "retrieval_method": exp_id})()
        _prediction_paths.append((dummy_exp, pred_path))

if not _prediction_paths:
    raise FileNotFoundError("prediction_paths is missing and no predictions JSONL files were found.")

_eval_lookup = eval_df.copy()
_eval_lookup["_source_eval_file_str"] = _eval_lookup["source_eval_file"].astype(str)
_eval_lookup["_id_str"] = _eval_lookup["id"].astype(str)

analysis_rows = []
for exp, pred_path in _prediction_paths:
    pred_df = _load_prediction_jsonl(Path(pred_path))
    for _, row in pred_df.iterrows():
        source_eval_file = str(row.get("source_eval_file", ""))
        qid = str(row.get("id", ""))
        gt_match = _eval_lookup[(_eval_lookup["_source_eval_file_str"] == source_eval_file) & (_eval_lookup["_id_str"] == qid)]
        if gt_match.empty:
            continue
        gt_row = gt_match.iloc[0]
        gt_docs = gt_row.get("ground_truth_doc_list", [])
        contexts = _safe_contexts(row.get("retrieved_contexts", []))
        pred_docs = _context_doc_names(contexts)
        chunk_types = _context_chunk_types(contexts)
        first_rank = _rank_first_gold(pred_docs, gt_docs, k=FINAL_TOP_K)
        top1_score = row.get("top1_score", None)
        if top1_score is None and contexts:
            top1_score = contexts[0].get("score")
        analysis_rows.append({
            "experiment_id": getattr(exp, "experiment_id", str(exp)),
            "retrieval_method": getattr(exp, "retrieval_method", ""),
            "source_eval_file": source_eval_file,
            "id": qid,
            "question": row.get("question", ""),
            "type": gt_row.get("type", ""),
            "difficulty": gt_row.get("difficulty", ""),
            "gt_doc_count": len(gt_docs),
            "hit_at_5": _hit_any_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "all_gold_docs_hit_at_5": _all_gold_docs_hit_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "doc_recall_at_5": _doc_recall_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "first_gold_rank": first_rank,
            "gt_docs": gt_docs,
            "retrieved_docs": pred_docs[:FINAL_TOP_K],
            "retrieved_chunk_types": chunk_types[:FINAL_TOP_K],
            "top1_score": top1_score,
            "retrieval_status": row.get("retrieval_status", ""),
            "coverage_reason": row.get("coverage_reason", ""),
        })

failure_df = pd.DataFrame(analysis_rows)
failure_df["question_short"] = failure_df["question"].apply(lambda x: _short(x, 70))
failure_df["gt_docs_short"] = failure_df["gt_docs"].apply(lambda x: _short(x, 80))
failure_df["retrieved_docs_short"] = failure_df["retrieved_docs"].apply(lambda x: _short(x, 95))
failure_df["retrieved_chunk_types_short"] = failure_df["retrieved_chunk_types"].apply(lambda x: _short(x, 70))
failure_df["top1_score_round"] = pd.to_numeric(failure_df["top1_score"], errors="coerce").round(4)

analysis_dir = OUTPUT_DIR / "analysis"
analysis_dir.mkdir(parents=True, exist_ok=True)
failure_csv_path = analysis_dir / f"failure_analysis_p4_hwpx_{CORPUS_LIMIT}_sample{EVAL_SAMPLE_SIZE or 'all'}.csv"
failure_export = failure_df.copy()
for col in ["gt_docs", "retrieved_docs", "retrieved_chunk_types"]:
    failure_export[col] = failure_export[col].apply(lambda x: json.dumps(x, ensure_ascii=False))
failure_export.to_csv(failure_csv_path, index=False, encoding="utf-8-sig")

print("analysis rows:", len(failure_df))
print("experiments:", sorted(failure_df["experiment_id"].unique()))
print("saved full failure analysis:", failure_csv_path)

_display_title("1) Hit/Miss count by experiment")
display(
    failure_df
    .groupby(["experiment_id", "hit_at_5"])
    .size()
    .reset_index(name="count")
    .sort_values(["experiment_id", "hit_at_5"])
)

_display_title("2) Miss count by type/difficulty/gt_doc_count")
display(
    failure_df[failure_df["hit_at_5"] == 0]
    .groupby(["experiment_id", "type", "difficulty", "gt_doc_count"])
    .size()
    .reset_index(name="miss_count")
    .sort_values(["experiment_id", "miss_count"], ascending=[True, False])
    .head(40)
)

_display_title("3) Miss count by retrieved chunk type mix")
chunk_mix = failure_df[failure_df["hit_at_5"] == 0].copy()
chunk_mix["retrieved_chunk_type_mix"] = chunk_mix["retrieved_chunk_types"].apply(lambda xs: " | ".join([x for x in xs if x]))
display(
    chunk_mix
    .groupby(["experiment_id", "retrieved_chunk_type_mix"])
    .size()
    .reset_index(name="miss_count")
    .sort_values(["experiment_id", "miss_count"], ascending=[True, False])
    .head(20)
)

analysis rows: 300
experiments: ['R0_p4_hwpx_690_v1_dense_top5', 'R1_p4_hwpx_690_v2_dense_rerank_top5', 'R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5']
saved full failure analysis: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/analysis/failure_analysis_p4_hwpx_690_sample100.csv

====================================================================================================
1) Hit/Miss count by experiment

                              experiment_id  hit_at_5  count
0              R0_p4_hwpx_690_v1_dense_top5         0     14
1              R0_p4_hwpx_690_v1_dense_top5         1     86
2       R1_p4_hwpx_690_v2_dense_rerank_top5         0      5
3       R1_p4_hwpx_690_v2_dense_rerank_top5         1     95
4  R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5         0      1
5  R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5         1     99

====================================================================================================
2) Miss count by type/difficulty/gt_doc_count

                               experiment_id type difficulty  gt_doc_count  miss_count
8               R0_p4_hwpx_690_v1_dense_top5    E          하             1           3
1               R0_p4_hwpx_690_v1_dense_top5    B          중             2           2
3               R0_p4_hwpx_690_v1_dense_top5    C          중             1           2
5               R0_p4_hwpx_690_v1_dense_top5    D          중             1           2
0               R0_p4_hwpx_690_v1_dense_top5    A          하             1           1
2               R0_p4_hwpx_690_v1_dense_top5    C          상             1           1
4               R0_p4_hwpx_690_v1_dense_top5    C          하             1           1
6               R0_p4_hwpx_690_v1_dense_top5    D          하             1           1
7               R0_p4_hwpx_690_v1_dense_top5    E          중             1           1
9        R1_p4_hwpx_690_v2_dense_rerank_top5    A          중             1           1
10       R1_p4_hwpx_690_v2_dense_rerank_top5    A          하             1           1
11       R1_p4_hwpx_690_v2_dense_rerank_top5    B          중             2           1
12       R1_p4_hwpx_690_v2_dense_rerank_top5    E          중             1           1
13       R1_p4_hwpx_690_v2_dense_rerank_top5    E          하             1           1
14  R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5    E          하             1           1

====================================================================================================
3) Miss count by retrieved chunk type mix

                              experiment_id               retrieved_chunk_type_mix  miss_count
2              R0_p4_hwpx_690_v1_dense_top5       text | text | text | text | text           7
1              R0_p4_hwpx_690_v1_dense_top5              text | text | text | text           4
0              R0_p4_hwpx_690_v1_dense_top5                     text | text | text           3
3       R1_p4_hwpx_690_v2_dense_rerank_top5                                  table           1
4       R1_p4_hwpx_690_v2_dense_rerank_top5  table | table | table | table | table           1
5       R1_p4_hwpx_690_v2_dense_rerank_top5                    text | table | text           1
6       R1_p4_hwpx_690_v2_dense_rerank_top5             text | table | text | text           1
7       R1_p4_hwpx_690_v2_dense_rerank_top5      text | text | table | text | text           1
8  R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5     text | text | table | text | table           1

In [16]:
# ===== Compact R0/R1/R2 hit pattern summary =====
pivot_cols = ["source_eval_file", "id", "question", "type", "difficulty", "gt_doc_count"]
hit_pivot = failure_df.pivot_table(
    index=pivot_cols,
    columns="experiment_id",
    values="hit_at_5",
    aggfunc="max",
    fill_value=0,
).reset_index()

experiment_cols = [c for c in hit_pivot.columns if str(c).startswith("R")]
alias_map = {col: str(col).split("_", 1)[0] for col in experiment_cols}
print("experiment aliases:")
for col in experiment_cols:
    print(f"  {alias_map[col]} = {col}")

hit_pivot["question_short"] = hit_pivot["question"].apply(lambda x: _short(x, 70))

if len(experiment_cols) >= 2:
    base_col = experiment_cols[0]
    best_col = experiment_cols[-1]
    hit_pivot["pattern"] = hit_pivot[experiment_cols].astype(str).agg("".join, axis=1)
    view_cols = ["source_eval_file", "id", "type", "difficulty", "gt_doc_count", "question_short"] + experiment_cols

    _display_title("4) Hit pattern summary")
    display(hit_pivot["pattern"].value_counts().rename_axis("hit_pattern").reset_index(name="questions"))

    def _compact_pattern_view(df, max_rows=12):
        out = df[view_cols].copy().rename(columns=alias_map)
        return out.head(max_rows)

    _display_title("5) Final experiment improved over baseline")
    improved = hit_pivot[(hit_pivot[base_col] == 0) & (hit_pivot[best_col] == 1)]
    display(_compact_pattern_view(improved, 12))

    _display_title("6) Baseline hit but final experiment missed")
    regressed = hit_pivot[(hit_pivot[base_col] == 1) & (hit_pivot[best_col] == 0)]
    display(_compact_pattern_view(regressed, 12))

    _display_title("7) All experiments missed")
    all_missed = hit_pivot[hit_pivot[experiment_cols].sum(axis=1) == 0]
    display(_compact_pattern_view(all_missed, 12))
else:
    print("Not enough experiment columns to compare.")

experiment aliases:
  R0 = R0_p4_hwpx_690_v1_dense_top5
  R1 = R1_p4_hwpx_690_v2_dense_rerank_top5
  R2 = R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5

====================================================================================================
4) Hit pattern summary

  hit_pattern  questions
0         111         84
1         011         11
2         001          2
3         101          2
4         000          1

====================================================================================================
5) Final experiment improved over baseline

experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,question_short,R0,R1,R2
9,eval_batch_02.csv,Q040,E,중,1,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...,0,0,1
11,eval_batch_03.csv,Q056,C,중,1,"그렇다면 이 예산 하에서, 언급하신 주요 대학 구축 시스템 중 내부 기초 데이터 기반의 경영 구조 관련 부분은 어느 부...",0,1,1
20,eval_batch_04.csv,Q078,D,중,1,나노종합기술원이 발주한 23.4억여 원의 '스마트 팹 서비스 설비온라인 사업' 관련 제안서에 규정된 개발진의 야근 및 ...,0,1,1
21,eval_batch_04.csv,Q079,E,하,1,쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?,0,1,1
22,eval_batch_04.csv,Q080,E,하,1,그래드코뤼아레져가 올해 스톼트하는 그룹વે어 메신져 통함 쁠젝의 젼체 뻐젯은 정확히 어떻게 잡혔능가요.,0,1,1
48,eval_batch_14.csv,Q278,D,중,1,"을지대학교 비교과시스템 개발 용역 지침에서, 학생 심리상담 예약 연동 모듈을 개발할 때 우울증 고위험군 재학생들에게 대...",0,1,1
65,eval_batch_18.csv,Q357,D,하,1,"을지대학교 비교과시스템 개발 지시서에서, 마일리지 성적이 우수한 상위 동아리 학생 대표 5명에게 지급해야 하는 해외 유...",0,1,1
67,eval_batch_19.csv,Q363,A,하,1,광주과학기술원(GIST)의 통합연구비관리망은 외부의 산업통상자원부 산하 어떤 메가 국가 결제 시스템과 연계하는 것을 목...,0,1,1
74,eval_batch_20.csv,Q392,B,중,2,케빈랩 평택시 관내 AI 영상감시망과 한국교육과정평가원의 국가교육과정 NCIC 운영망은 모두 '비상시(재난 및 장애시)...,0,0,1
87,eval_batch_23.csv,Q456,C,중,1,그렇다면 부산 쪽의 또 다른 공공기관인 부산관광공사의 경영정보망 개선 용역을 봅시다. 내부 임직원용 그룹웨어를 통합 구...,0,1,1
95,eval_batch_25.csv,Q491,B,중,2,고양도시관리공사 다목적구장 예매망과 부산국제영화제의 행사 예약 포털은 시민들의 예약 트래픽을 처리하는 시스템입니다. 이...,0,1,1
97,eval_batch_25.csv,Q495,C,하,1,이어서 한국철도공사(코레일) 운행정보기록 자동분석 시스템 보충 질문입니다. 블랙박스 기록을 빼서 그걸 코레일 본사 서버...,0,1,1

====================================================================================================
6) Baseline hit but final experiment missed

Empty DataFrame
Columns: [source_eval_file, id, type, difficulty, gt_doc_count, question_short, R0, R1, R2]
Index: []

====================================================================================================
7) All experiments missed

experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,question_short,R0,R1,R2
45,eval_batch_12.csv,Q239,E,하,1,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?,0,0,0

In [17]:
# ===== Compact failure case list =====
# Pick a CASE_ID from this compact table, then run the next cell to inspect it in plain text.

DETAIL_ROWS = 25
FAIL_CASES = failure_df[failure_df["hit_at_5"] == 0].copy().reset_index(drop=True)
FAIL_CASES["case_id"] = FAIL_CASES.index
FAIL_CASES = FAIL_CASES.sort_values(["experiment_id", "top1_score_round"], ascending=[True, True], na_position="last").reset_index(drop=True)
FAIL_CASES["case_id"] = FAIL_CASES.index

compact_case_cols = [
    "case_id",
    "experiment_id",
    "source_eval_file",
    "id",
    "type",
    "difficulty",
    "gt_doc_count",
    "top1_score_round",
    "question_short",
]

print("full detail csv:", failure_csv_path)
print("total miss cases:", len(FAIL_CASES))
display(FAIL_CASES[compact_case_cols].head(DETAIL_ROWS))

full detail csv: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/analysis/failure_analysis_p4_hwpx_690_sample100.csv
total miss cases: 20

,case_id,experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,top1_score_round,question_short
0,0,R0_p4_hwpx_690_v1_dense_top5,eval_batch_04.csv,Q080,E,하,1,0.1618,그래드코뤼아레져가 올해 스톼트하는 그룹વે어 메신져 통함 쁠젝의 젼체 뻐젯은 정확히 어떻게 잡혔능가요.
1,1,R0_p4_hwpx_690_v1_dense_top5,eval_batch_04.csv,Q079,E,하,1,0.3298,쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?
2,2,R0_p4_hwpx_690_v1_dense_top5,eval_batch_02.csv,Q040,E,중,1,0.4001,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...
3,3,R0_p4_hwpx_690_v1_dense_top5,eval_batch_12.csv,Q239,E,하,1,0.4051,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
4,4,R0_p4_hwpx_690_v1_dense_top5,eval_batch_25.csv,Q491,B,중,2,0.4374,고양도시관리공사 다목적구장 예매망과 부산국제영화제의 행사 예약 포털은 시민들의 예약 트래픽을 처리하는 시스템입니다. 이...
5,5,R0_p4_hwpx_690_v1_dense_top5,eval_batch_14.csv,Q278,D,중,1,0.4499,"을지대학교 비교과시스템 개발 용역 지침에서, 학생 심리상담 예약 연동 모듈을 개발할 때 우울증 고위험군 재학생들에게 대..."
6,6,R0_p4_hwpx_690_v1_dense_top5,eval_batch_04.csv,Q078,D,중,1,0.4510,나노종합기술원이 발주한 23.4억여 원의 '스마트 팹 서비스 설비온라인 사업' 관련 제안서에 규정된 개발진의 야근 및 ...
7,7,R0_p4_hwpx_690_v1_dense_top5,eval_batch_18.csv,Q357,D,하,1,0.4528,"을지대학교 비교과시스템 개발 지시서에서, 마일리지 성적이 우수한 상위 동아리 학생 대표 5명에게 지급해야 하는 해외 유..."
8,8,R0_p4_hwpx_690_v1_dense_top5,eval_batch_25.csv,Q496,C,상,1,0.4773,그렇군요. 비슷한 맥락으로 경영 정보를 현대화하는 부산관광공사 시스템 개선을 여쭤보죠. 과거엔 모바일 지원이 안 돼서 ...
9,9,R0_p4_hwpx_690_v1_dense_top5,eval_batch_20.csv,Q392,B,중,2,0.5092,케빈랩 평택시 관내 AI 영상감시망과 한국교육과정평가원의 국가교육과정 NCIC 운영망은 모두 '비상시(재난 및 장애시)...
10,10,R0_p4_hwpx_690_v1_dense_top5,eval_batch_23.csv,Q456,C,중,1,0.5243,그렇다면 부산 쪽의 또 다른 공공기관인 부산관광공사의 경영정보망 개선 용역을 봅시다. 내부 임직원용 그룹웨어를 통합 구...
11,11,R0_p4_hwpx_690_v1_dense_top5,eval_batch_19.csv,Q363,A,하,1,0.5544,광주과학기술원(GIST)의 통합연구비관리망은 외부의 산업통상자원부 산하 어떤 메가 국가 결제 시스템과 연계하는 것을 목...
12,12,R0_p4_hwpx_690_v1_dense_top5,eval_batch_25.csv,Q495,C,하,1,0.5561,이어서 한국철도공사(코레일) 운행정보기록 자동분석 시스템 보충 질문입니다. 블랙박스 기록을 빼서 그걸 코레일 본사 서버...
13,13,R0_p4_hwpx_690_v1_dense_top5,eval_batch_03.csv,Q056,C,중,1,0.5652,"그렇다면 이 예산 하에서, 언급하신 주요 대학 구축 시스템 중 내부 기초 데이터 기반의 경영 구조 관련 부분은 어느 부..."
14,14,R1_p4_hwpx_690_v2_dense_rerank_top5,eval_batch_02.csv,Q040,E,중,1,0.0092,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...
15,15,R1_p4_hwpx_690_v2_dense_rerank_top5,eval_batch_20.csv,Q392,B,중,2,0.0101,케빈랩 평택시 관내 AI 영상감시망과 한국교육과정평가원의 국가교육과정 NCIC 운영망은 모두 '비상시(재난 및 장애시)...
16,16,R1_p4_hwpx_690_v2_dense_rerank_top5,eval_batch_12.csv,Q239,E,하,1,0.0112,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
17,17,R1_p4_hwpx_690_v2_dense_rerank_top5,eval_batch_24.csv,Q462,A,하,1,0.0118,(사)부산국제영화제의 행사지원시스템 공급을 총괄하는 본 용역 사업에 편성된 공식 추정 예산은 수치로 어떻게 되나요?
18,18,R1_p4_hwpx_690_v2_dense_rerank_top5,eval_batch_20.csv,Q385,A,중,1,0.5767,"한국원자력연구원이 선량평가시스템 기능 고도화를 진행할 때, 방사능 관련 핵심 민감 데이터가 유출되는 사고를 무효화시키기..."
19,19,R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5,eval_batch_12.csv,Q239,E,하,1,0.0112,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?

In [33]:
# ===== Failure CASE_ID detail viewer =====
# Change CASE_IDS and rerun only this cell.
# Examples: CASE_IDS = [0] or CASE_IDS = [0, 1, 2, 3, 4]

CASE_IDS = [0, 1, 2, 3, 4]
MAX_TEXT_CHARS = 900


def show_failure_case(case_id: int):
    if "FAIL_CASES" not in globals() or FAIL_CASES.empty:
        print("FAIL_CASES is empty. Run the compact failure case list cell first.")
        return
    matches = FAIL_CASES[FAIL_CASES["case_id"] == case_id]
    if matches.empty:
        print("Unknown CASE_ID:", case_id)
        return
    miss = matches.iloc[0]
    print("=" * 120)
    print(f"CASE_ID: {case_id}")
    print(f"EXPERIMENT: {miss['experiment_id']}")
    print(f"EVAL: {miss['source_eval_file']} / {miss['id']}")
    print(f"TYPE: {miss['type']} | DIFFICULTY: {miss['difficulty']} | GT_DOC_COUNT: {miss['gt_doc_count']} | TOP1: {miss.get('top1_score_round')}")
    print()
    print("QUESTION:")
    print(miss["question"])
    print()
    print("GT_DOCS:")
    for doc in miss["gt_docs"]:
        print("-", doc)
    print()
    print("RETRIEVED_DOCS:")
    for doc, chunk_type in zip(miss["retrieved_docs"], miss["retrieved_chunk_types"]):
        print(f"- [{chunk_type}] {doc}")

    pred_path = None
    for exp, path in _prediction_paths:
        if getattr(exp, "experiment_id", str(exp)) == miss["experiment_id"]:
            pred_path = Path(path)
            break
    if pred_path is None:
        return

    pred_df = _load_prediction_jsonl(pred_path)
    recs = pred_df[(pred_df["source_eval_file"].astype(str) == str(miss["source_eval_file"])) & (pred_df["id"].astype(str) == str(miss["id"]))]
    if recs.empty:
        return

    print()
    print("RETRIEVED CONTEXTS:")
    contexts = recs.iloc[0].get("retrieved_contexts", [])
    for ctx in _safe_contexts(contexts)[:FINAL_TOP_K]:
        text = str(ctx.get("text", "")).replace("\n", " ")
        if len(text) > MAX_TEXT_CHARS:
            text = text[:MAX_TEXT_CHARS].rstrip() + " ..."
        meta = ctx.get("metadata") or {}
        print("-" * 100)
        print(f"rank={ctx.get('rank')} score={ctx.get('score')} file={ctx.get('filename')}")
        print(f"chunk_type={meta.get('chunk_type')} chunk_id={ctx.get('chunk_id')}")
        print(text)


for case_id in CASE_IDS:
    show_failure_case(case_id)

========================================================================================================================
CASE_ID: 0
EXPERIMENT: R0_p4_hwpx_690_v1_dense_top5
EVAL: eval_batch_04.csv / Q080
TYPE: E | DIFFICULTY: 하 | GT_DOC_COUNT: 1 | TOP1: 0.1618

QUESTION:
그래드코뤼아레져가 올해 스톼트하는 그룹વે어 메신져 통함 쁠젝의 젼체 뻐젯은 정확히 어떻게 잡혔능가요.

GT_DOCS:
- 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp

RETRIEVED_DOCS:
- [text] 국가철도공단_철도산업정보센터 정보시스템 G-클라우드 1차 전환 용역.hwp
- [text] 전북특별자치도 정읍시_정읍체육트레이닝센터 통합운영관리시스템 구.hwp
- [text] 서울에너지공사_그룹웨어시스템 고도화 용역.hwp
- [text] 국립공원공단_2024년 자원통합관리시스템 운영관리.hwp
- [text] 한국수자원공사_수도사업장 통합 사고분석솔루션 시범구축 용역.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.16183727979660034 file=국가철도공단_철도산업정보센터 정보시스템 G-클라우드 1차 전환 용역.hwp
chunk_type=text chunk_id=doc_6f4fab3c51ed_text_text_0061_part_001_0bae99e78d5e
[문서: 국가철도공단_철도산업정보센터 정보시스템 G-클라우드 1차 전환 용역.hwp | 사업명: 철도산업정보센터 정보시스템 G-클라우드 1차 전환 용역 | 발주기관: 국가철도공단 | 섹션: Ⅳ. 기타 | 유형: text] 그룹: 비밀번호는 정보보안담당관이 별도로 기록·관리하고 수시로 해당 계정에 접속하여 자정된 자료와 작업이력 확인 row_group: 비밀번호는 정보보안담당관이 별도로 기록·관리하고 수시로 해당 계정에 접속하여 자정된 자료와 작업이력 확인 | 구분: 전산장비 / 및 / 휴대용 / 저장매체 / 보안대책 | 보안대책: 용역업체 전산장비는 정보보안담당관 인가 후 반입·반출 / * 반출 시 정보보안담당관 통제 하에 저장자료 완전 삭제 그룹: 전산장비 반입·반출 시마다 악성코드 감염여부 점검 및 자료 무단 반출입 여부 확인 그룹: 업무망 접속용 전산장비와 인터넷망 접속용 전산장비를 구분하여 활용 및 망간 혼용 금지 그룹: 용역업체 노트북PC, 휴대용 저장매체 정기 보안점검 그룹: 용역업체 휴대용 저장매체의 정보보안담당관 승인 여부 그룹: 노트북·PC, 휴대용 저장매체는 시건장치가 있는 보관함에 보관 그룹: 인터넷망 접속이 필요한 전산장비 사전 지정 및 보안조치 여부 그룹: 업무에 필요한 사이트에만 접속토록 방화벽 등을 통해 통제 / * P2P, 웹하드, 메신저 등 인터넷 자료공유사이트 활용 원천차단 그룹: 인터넷 접속허용 전산장비에 업무 수행 및 업무자료 저장 금지 그룹: 최신 백신 프로그램 설치 및 주기적인 전체 파일 검사 여부 그룹: 비밀번호·화면보호기 설정 그룹: 비인가 저장매체·통신기기 접속 통제 / * 매체제어 미설치 전산장비는 외부기기 연결단자 보안스티커 부착 그룹: 사업 완료 시 용역업체 전산장비는 정보보안담당관 통제 하에 저장자료를 완전 삭제 3. 용역사업 완료 ...
----------------------------------------------------------------------------------------------------
rank=2 score=0.15050077438354492 file=전북특별자치도 정읍시_정읍체육트레이닝센터 통합운영관리시스템 구.hwp
chunk_type=text chunk_id=doc_8bb4ffcd35c3_text_text_0029_part_001_4a5df773268d
[문서: 전북특별자치도 정읍시_정읍체육트레이닝센터 통합운영관리시스템 구.hwp | 사업명: 정읍체육트레이닝센터 통합운영관리시스템 구 | 발주기관: 전북특별자치도 정읍시 | 섹션: 문서 시작 | 유형: text] 다. 발주기관은 사업자에게 제공한 사무실에 대해 수시로 보안점검을 할 수 있다. 라. 사업 관련 자료를 보관한 PC로 인터넷에 접속하면 안 된다. 마. USB메모리 등 휴대용 저장매체는 사용을 금지하되 불가피한 경우 발주기관의 승인 후 사용할 수 있다. 바. 사업자 PC 및 휴대용 저장매체에 정보시스템 접속정보(ID, 비밀번호)를 저장하면 안 된다. 사. 사업 참여인원의 개인 휴대폰은 발주기관의 통제 하에 카메라 및 충전포트에 보안스티커를 부착해야 한다. 아. 사업자가 사용하는 노트북PC, 휴대용 저장매체 등은 퇴근·휴가 시와 같이 일정기간 사용하지 않을 경우 분실 방지를 위해 시건장치가 있는 보관함에 보관해야 한다. 2-3. 내·외부망 접근시 보안관리 가. 사업자 사용 통신망은 발주기관 행정통신망(내부망)과 분리하여 구성해야 한다. 단, 업무상 필요한 경우 발주기관의 승인 후 해당 서버에만 제한적으로 접근해야 한다. 나. 사업 참여인원의 사용자 계정(ID)은 하나의 그룹으로 등록해야 한다. 다. 계정별 정보시스템 접근권한을 차등 부여하되 내부문서 접근은 금지한다. 라. 사업 참여인원이 ‘root’ 계정 등 정보시스템에 중대한 영향을 끼칠 수 있는 계정에 대한 단독 접근은 불허하며, 필요할 경우 발주기관의 승인을 받아야 한다. 마. 계정별 부여된 접근권한은 불필요 시 곧바로 권한을 해지하거나 계정을 폐기해야 한다. 바. 발주기관은 사용자별로 부여한 계정에 접속하여 저장된 자료와 작업이력을 확인할 수 있다. 사. PM은 사업 참여인원이 접근한 서버 및 네트워크 장비에 대한로깅 기 ...
----------------------------------------------------------------------------------------------------
rank=3 score=0.1478193998336792 file=서울에너지공사_그룹웨어시스템 고도화 용역.hwp
chunk_type=text chunk_id=doc_6b9955656361_text_text_0022_part_003_c35513b94f5f
계정에 대한 단독 접근은 불허하며, 필요할 경우 발주기관의 승인을 받아야 한다. 마. 계정별 부여된 접근권한은 불필요 시 곧바로 권한을 해지하거나 계정을 폐기해야 한다. 바. 발주기관은 사용자별로 부여한 계정에 접속하여 저장된 자료와 작업 이력을 확인할 수 있다. 사. 용역업체 PM은 사업 참여인원이 접근한 서버 및 네트워크 장비에 대한 로깅 기록을 매일 확인하고 이상 유무를 발주기관에 보고해야 한다. 아. 용역업체에서 사용하는 PC는 인터넷 연결을 금지하되, 사업수행을 위해 부득이한 경우 필요한 보안조치를 시행하고 발주기관의 승인 후 사용해야 한다. 자. 발주기관 내부에서 비인가 무선 AP(무선공유기, 스마트폰 핫스팟 등) 설정을 금지하며, 시스템 개발PC와 연결은 금지한다.
----------------------------------------------------------------------------------------------------
rank=4 score=0.14313995838165283 file=국립공원공단_2024년 자원통합관리시스템 운영관리.hwp
chunk_type=text chunk_id=doc_0a3537fd8f01_text_text_0034_part_001_5de85ccd9897
[문서: 국립공원공단_2024년 자원통합관리시스템 운영관리.hwp | 사업명: 2024년 자원통합관리시스템 운영관리 | 발주기관: 국립공원공단 | 섹션: Ⅳ. 기타 | 유형: text] 그룹: CCTV･잠금장치 등 비인가 출입통제 대책이 마련된 사무실 사용 여부 그룹: CCTV 등 통제장치의 관리상태(작동여부, 사각지대 보완 등) 및 기록 확인 그룹: 용역사업 참여인원의 신상변동(휴가 및 해외여행 포함)에 대한 대책 마련 [표 | 섹션: Ⅳ. 기타 | rows: 19 | cols: 5] 컬럼: 구분 | 보 안 대 책 | 양호 | 미흡 | 비고 구분: 내･외부 / 전산망 / 접근 시 / 보안관리 | 보 안 대 책: 용역업체 정보통신망은 방화벽 등을 활용하여 발주기관 업무망 및 기관 인터넷망과 분리하고 업무상 필요한 서버에만 제한적 접근 허용 그룹: 용역업체 PC의 인터넷 연결 차단 여부 및 인터넷 접속허용 PC에 대한 보안조치 그룹: 비인가 무선 AP(무선공유기 등)을 설정을 금지하고 휴대형 무선모뎀(WiFi 등) 반입 통제 그룹: 스마트폰･휴대폰을 무선 모뎀으로 활용하지 못하도록 통제수단 강구(PC에 비인가 통신기기 접속차단 S/W 설치, 스마트폰 접속단자 봉인조치 등) 그룹: 노트북PC 반입 시 무선통신 기능 불능화 조치(드라이버 삭제 등) 시행 그룹: 기관 외부에서 기관 내부의 시스템 개발PC 및 기관 시스템에 원격접속 금지 그룹: 용역업체 직업의 계정은 하나의 그룹으로 등록하고 계정별로 정보시스템 접근권한을 부여하되 기관 내부문서 접근 금지 그룹: 용역업체 직업의 ‘root’ 계정 등 시스템에 중대한 영향을 끼칠 수 있는 계정에 대한 접근 불허 그룹: 계정별로 부여된 권한은 불필요시 곧바로 해지하거나 계정 폐기 그룹: 용역업체 직원의 작업내용 확인을 위해 작업이력 로깅기능 구축 ...
----------------------------------------------------------------------------------------------------
rank=5 score=0.1394740343093872 file=한국수자원공사_수도사업장 통합 사고분석솔루션 시범구축 용역.hwp
chunk_type=text chunk_id=doc_5717c4ab4d37_text_text_0022_part_004_6dd1fa8abf82
시 접속이 제한된 사이트 및 인터넷 파일공유사이트 등에 접속할 수 없으며, 사업수행 관련 자료는 웹하드 등 인터넷 자료공유 사이트 및 개인 메일함 저장 금지 / □ 사업수행으로 생산되는 산출물 및 기록은 발주부서장의 허가 없이 무단 제공･대여･열람 금지 / □ 용역 수행 장소는 잠금장치가 있어 통제 가능한 사무실을 사용 / □ 반입된 노트북･PC는 사업 종료 시까지 반출 금지, 다만 고장 등 부득이하게 외부반출이 필요한 경우 발주부서의 ‘용역업체용 장비 반출입대장’에 기록하고 보안 조치 후 반출 / □ 참여 인원의 노트북･PC에 최신 백신 등 자체 PC 보안프로그램과 발주부서에서 제공하는 자료 유출 방지 등 보안프로그램 설치 / □ 계약상대자는 노트북･PC에 CMOS 및 윈도우즈 로그인 패스워드, 화면 보호기(10분 간격) 패스워드를 영문자 및 숫자가 조합된 9글자 이상으로 설정
========================================================================================================================
CASE_ID: 1
EXPERIMENT: R0_p4_hwpx_690_v1_dense_top5
EVAL: eval_batch_04.csv / Q079
TYPE: E | DIFFICULTY: 하 | GT_DOC_COUNT: 1 | TOP1: 0.3298

QUESTION:
쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?

GT_DOCS:
- 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp

RETRIEVED_DOCS:
- [text] 수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
- [text] 한국농어촌공사_라오스 댐안전관리 시스템 구축사업 PMC용역.hwp
- [text] 국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
- [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
- [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.32984447479248047 file=수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
chunk_type=text chunk_id=doc_000cc725bf29_text_text_0031_part_003_cf8cafd9fc79
자 : (직인) / 수산업협동조합중앙회 귀중 ※ 제안금액은 한글로 기재하고 아라비아 숫자를 병기 ※ 인감날인 후 입찰보증금, 가격산출내역서 및 기타 증빙과 같이 밀봉하여 제출 〈서식 제11호〉 가 격 산 출 내 역 서 □ 총사업비 : 일금 원 (￦ ) (단위 : 원) [표 | 섹션: 별지서식 | rows: 20 | cols: 8] 컬럼: 항 목 | col_2 | col_3 | 단 위 | 산출 내역 | col_6 | 구 성 비 | 비 고 그룹: 수 량 / 금 액 row_group: 수 량 / 금 액 | 항 목: 순 / 용 / 역 / 원 / 가 | col_2: ① / 노 / 무 / 비 | 단 위: 식 | 구 성 비: %
----------------------------------------------------------------------------------------------------
rank=2 score=0.3113071918487549 file=한국농어촌공사_라오스 댐안전관리 시스템 구축사업 PMC용역.hwp
chunk_type=text chunk_id=doc_9586084f3cc6_text_text_0002_part_002_535002d082a7
Management System Project in Lao P.D.R 나. 용역기간 : 2024년 ~ 2028년(5개년) ○ 1차년도 : 계약체결일로부터 2024.12.20일까지 다. 용역금액 : 4,555,441,000원 (영세율, 손해배상보험(공제)료 포함) 라. 대상지 : (마스터 플랜) 라오스 전역 농업용 댐 비엔티안 캐피탈 싸이타니구 동막카이마을 * 용역 수행 시 수원국 및 발주처의 요청에 따라 변동될 수 있음 마. 용역범위 [표 | 섹션: 문서 시작 | rows: 9 | cols: 2] 컬럼: 구 분 | 사업내용 구 분: 사업관리 | 사업내용: ㅇ사업총괄 관리 / - 사업진도보고(착수신고, 월간공정보고, 연차별 실적보고, 최종결과 보고) / ㅇ사업수행계획서(액션플랜) 수립 및 관리 / - 사업범위, 추진일정, 방법 등 계획수립 / ㅇ전문가 파견관리 / - 전문가 파견계획서 및 귀국 보고서 / ㅇ착수/중간/종료보고회 실시 구 분: 마스터플랜 / 수립 | 사업내용: ◦안전진단 마스터플랜 수립 / ◦안전관리 모니터링 마스터플랜 수립 구 분: 법/제도 / 가이드라인 | 사업내용: ◦법제도화 가이드라인 / - 안전진단제도⋅법 사례분석을 통한 법 제정 가이드라인 / ◦기술제도화를 위한 가이드라인 / - 댐 안전진단 실무지침 구 분: 안전관리 / 모니터링 / 시스템구축 | 사업내용: ◦사무실 신축, 진단장비 보관창고 구축 / ◦시설 구축 (4개 저수지 대상) / - CCTV, 중앙서버, 통신 네트워크, 비상전원장치, 디스플레이 구성 등 구 분: 안전진단 / 시범사업 | 사업내용: ◦안전진단 시범사업 실시(8개소) / - 정밀안전진단실시, 시범지구 진단보고서 작성, 교육교재 작성 등 / - 현지전문가 역량강화 : 실무교육, 현장교육 구 분: 전문가 / 파견 | 사업내용: ◦총 132개월 ...
----------------------------------------------------------------------------------------------------
rank=3 score=0.3081318140029907 file=국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
chunk_type=text chunk_id=doc_e06c24ba624f_text_text_0041_part_003_aeb102686739
함): 69,090,909 | 수량: 1 품 목: HPE nimble HF20 dual contraller storage raw 126T, usable 101, 11.52Tb cache -> 100테라 | 제품단가(부가세 미포함): 131,818,182 | 수량: 1 구분: L2 스위치 - 암데이터 관리기반 2차 | 품 목: Catalyst 2960-X 48 GigE, 2 x 10G SFP+, LAN Base | 제품단가(부가세 미포함): 7,727,273 | 수량: 2 구분: L4 스위치 - 암데이터 관리기반 2차 | 품 목: PAS-K 3200X | 제품단가(부가세 미포함): 57,727,273 | 수량: 2 구분: 스토리지 유지보수 - 암데이터 관리기반 3차 | 품 목: NetApp FAS8300 | 제품단가(부가세 미포함): 410,727,273 | 수량: 1
----------------------------------------------------------------------------------------------------
rank=4 score=0.2941545248031616 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
chunk_type=text chunk_id=doc_bf8e796b625c_text_text_0004_part_001_7181a9affcb0
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] 약어: WAS | 영어 표기: Web Application Server | 한글 명칭: 웹 어플리케이션 서버 약어: WEB | 영어 표기: World Wide Web | 한글 명칭: 월드와이드웹(인터넷) 약어: WUA | 영어 표기: Water User Association | 한글 명칭: 물 사용자 협의체 약어: XML | 영어 표기: eXtensible Markup Language | 한글 명칭: W3C에서 개발된 이기종 데이터 연동 마크업 언어 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 수립 및 시설기반강화 시범사업 사후관리 PMC 용역 나. 용역기간 : 계약체결일로부터 2024.12.31.까지 다. 대 상 지 : 우즈베키스탄 라. 집행 한도액 : 830,301,769원($643,645/1$=1,290원, 2023년 기준환율) (부가가치세 등 제반 비용 포함) ㅇ 1차연도(2024) : 830,301,769원 마. 용역범위 ㅇ 우즈베키스탄 수자원정보시스템 시스템 개선 - 기초정보 관리시스템 개선 - 실시간 모니터링 시스템 개선 - 장비관리 시스템 개선 - 물관리 의사결정지원 시스템 개선 * 시스템 개선 방안은 우즈벡 수자원부에서 시스템 상세사항을 준비하여 제공 예정(시스템 각 세부 메뉴 제공) ㅇ KOICA 구축 미수신 수위관측소 기자재 설치 및 유지보수 - 미수신 수위관측소의 유지관리를 ...
----------------------------------------------------------------------------------------------------
rank=5 score=0.2848691940307617 file=사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
chunk_type=text chunk_id=doc_5b75765779be_text_text_0007_part_001_06931c010a3d
[문서: 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp | 사업명: 우즈벡-키르기즈스탄 기후변화대응 스 | 발주기관: 사단법인아시아물위원회사무국 | 섹션: Ⅵ. 서식 | 유형: text] 1. 용역 개요 가. 용역명 ❍ (국문) 우즈벡-키르기즈스탄 기후변화대응 스마트 관개시스템 구축사업 ❍ (영문) Strengthening Climate Resilience through Introduction of Innovative Smart Techniques in Flood and Drought Management in Ozbekistan-Kyrgyzstan 나. 용역기간 : 계약체결일로부터 2027년 12월 31일 까지 다. 용역금액 : 5,031,000,000원 (손해배상보험(공제)료 포함) 라. 대 상 지 : 키르기스스탄(Talas-Alatau 및 Ferghana 산맥), 우즈베키스탄(Ferghana) 마. 용역범위 [표 | 섹션: Ⅵ. 서식 | rows: 5 | cols: 2] 컬럼: 구 분 | 주 요 내 용 구 분: 시설구축 | 주 요 내 용: ◦ 양수장 1개소 설치 1식, 부대공 등 / ◦ 수문 1개소 설치 1식, 부대공 등 구 분: 기자재 지원 | 주 요 내 용: ◦ 차량 : SUV 1대 / ◦ 사무용품 : 데스크탑, 노트북, 프린터 등 구 분: 전문가 파견 | 주 요 내 용: ◦ 9개 분야 총 61개월(국내 9개월, 국외 52개월) : PM, 수자원1(DPM), 수자원2, 토질, 구조, 토목, 기계, 전기, 건축 구 분: 사업관리 | 주 요 내 용: ◦ 사업 총괄관리 / - 사업 진도보고(착수신고, 월간공정보고, 연차별 실적보고, 최종결과 보고 등) / - 사업수행계획서, 액션플랜 수립 및 관리 / ◦ 전문가 파견관리 / - 전문가 파견계획서 및 귀국 보고서 ...
========================================================================================================================
CASE_ID: 2
EXPERIMENT: R0_p4_hwpx_690_v1_dense_top5
EVAL: eval_batch_02.csv / Q040
TYPE: E | DIFFICULTY: 중 | GT_DOC_COUNT: 1 | TOP1: 0.4001

QUESTION:
고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해서 간략히 요약좀 해줄래?

GT_DOCS:
- 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf

RETRIEVED_DOCS:
- [text] 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
- [text] 국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
- [text] 국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.4001351594924927 file=한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
chunk_type=text chunk_id=doc_8858323e67ab_text_text_0007_part_001_684d383762c7
[문서: 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp | 사업명: 차세대 ERP 통합업무포털시스템 구축 용역 | 발주기관: 한국농어촌공사 | 섹션: 문서 시작 | 유형: text] Level 2: 예산관리 | Level 3: 6 | Level 4: 29 Level 2: 구매자재 | Level 3: 5 | Level 4: 24 Level 2: 인사관리 | Level 3: 12 | Level 4: 59 Level 2: 사업관리 | Level 3: 5 | Level 4: 18 Level 2: 자산관리 | Level 3: 10 | Level 4: 63 Level 2: 임대관리 | Level 3: 3 | Level 4: 14 Level 2: 합계 | Level 3: 64개 | Level 4: 334개 ④ ERP 연계 활용 Legacy 시스템 업그레이드 1) SAP ERP 전환에 따른 암호화, 리포팅, 서버 OS, Solution Manager 등 기존 활용 솔루션이 S/4HANA로 전환 시 시스템 문제가 없도록 업그레이드 2) SAP 및 Non-SAP 솔루션의 연계 테스트를 통한 시스템 안정성 확보 [표 | 섹션: 문서 시작 | rows: 2 | cols: 3] 컬럼: col_1 | col_2 | col_3 그룹: 사용자 맞춤형 업무 포털 구축 ⑤ 개인 업무 맞춤형 정보 제공 포털 개발 [표 | 섹션: 문서 시작 | rows: 2 | cols: 4] 컬럼: 구분 | 방식 | 대상 | 수량 구분: 1 | 방식: 객체지향적 웹 업무포털 | 대상: 현 ERP대상(전사 플랫폼 고려) | 수량: 2 1) 표준화된 ERP 업무 프로세스의 운영기준(R&R, 산출물, 활동정보별 노하우, Policy, 업무별, 개인별 필요 화면 등)을 반영한 개인화 업무 포털 구축
----------------------------------------------------------------------------------------------------
rank=2 score=0.3681602478027344 file=국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
chunk_type=text chunk_id=doc_06c3935c7388_text_text_0002_part_003_8b4fcd6cd565
기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3, JavaScript)을 기반으로 시스템 전면 재구축 - 교수, 직원 등 다양한 사용자 그룹의 요구를 반영한 사용자 친화적 인터페이스를 구현하여, 사용자가 시스템을 쉽게 접근하고 학사·행정 업무를 처리
----------------------------------------------------------------------------------------------------
rank=3 score=0.3681602478027344 file=국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
chunk_type=text chunk_id=doc_3210483c98d2_text_text_0002_part_003_8b4fcd6cd565
기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3, JavaScript)을 기반으로 시스템 전면 재구축 - 교수, 직원 등 다양한 사용자 그룹의 요구를 반영한 사용자 친화적 인터페이스를 구현하여, 사용자가 시스템을 쉽게 접근하고 학사·행정 업무를 처리
========================================================================================================================
CASE_ID: 3
EXPERIMENT: R0_p4_hwpx_690_v1_dense_top5
EVAL: eval_batch_12.csv / Q239
TYPE: E | DIFFICULTY: 하 | GT_DOC_COUNT: 1 | TOP1: 0.4051

QUESTION:
그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?

GT_DOCS:
- 사단법인 보험개발원_실손보험 청구 전산화 시스템 구축 사업.hwp

RETRIEVED_DOCS:
- [text] 해외건설협회_에티오피아 부동산 대량평가 시범시스템 구축 및 전국 확.hwp
- [text] 해외건설협회_K-스마트 도로관리시스템 기반 몽골 국가도로 디지털 도로.hwp
- [text] 해외건설협회_하노이시 기성시가지의 효율적 정비와 개선을 위한 도시.hwp
- [text] 수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.4050712585449219 file=해외건설협회_에티오피아 부동산 대량평가 시범시스템 구축 및 전국 확.hwp
chunk_type=text chunk_id=doc_befa06b51b66_text_text_0044_part_003_becd70b70fe8
ls: 5] 컬럼: 구 분 | col_2 | 금 액 | col_4 | col_5 그룹: 합 계 ※ ㅇㅇㅇ를 준용하여 작성 ※ ㅇㅇㅇ는 'ㅇㅇㅇ'를 준용하여 작성 2. 항목별 소요예산 가. 전체 항목별 소요 예산 (단위 : 천원 / 부가가치세 포함) [표 | 섹션: Ⅱ. 가·감점 평가항목별 세부평가기준 | rows: 7 | cols: 9] 컬럼: 단위업무명 / (대기능) | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | 합계 나. 세부항목별 소요예산 총괄표 (단위 : 천원 / 부가가치세 포함) [표 | 섹션: Ⅱ. 가·감점 평가항목별 세부평가기준 | rows: 7 | cols: 9]
----------------------------------------------------------------------------------------------------
rank=2 score=0.38621485233306885 file=해외건설협회_K-스마트 도로관리시스템 기반 몽골 국가도로 디지털 도로.hwp
chunk_type=text chunk_id=doc_793af911b58f_text_text_0046_part_003_88d3e4a3cd45
/ 부가가치세 포함) [표 | 섹션: Ⅱ. 가·감점 평가항목별 세부평가기준 | rows: 10 | cols: 5] 컬럼: 구 분 | col_2 | 금 액 | col_4 | col_5 그룹: 합 계 ※ ㅇㅇㅇ를 준용하여 작성 ※ ㅇㅇㅇ는 'ㅇㅇㅇ'를 준용하여 작성 2. 항목별 소요예산 가. 전체 항목별 소요 예산 (단위 : 천원 / 부가가치세 포함) [표 | 섹션: Ⅱ. 가·감점 평가항목별 세부평가기준 | rows: 7 | cols: 9] 컬럼: 단위업무명 / (대기능) | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | 합계
----------------------------------------------------------------------------------------------------
rank=3 score=0.36570024490356445 file=해외건설협회_하노이시 기성시가지의 효율적 정비와 개선을 위한 도시.hwp
chunk_type=text chunk_id=doc_4174d9ad7fd6_text_text_0049_part_002_3ba13adafe47
ws: 10 | cols: 5] 컬럼: 구 분 | col_2 | 금 액 | col_4 | col_5 그룹: 합 계 ※ ㅇㅇㅇ를 준용하여 작성 ※ ㅇㅇㅇ는 'ㅇㅇㅇ'를 준용하여 작성 2. 항목별 소요예산 가. 전체 항목별 소요 예산 (단위 : 천원 / 부가가치세 포함) [표 | 섹션: 별첨: 검토자료 및 변경 사업수행계획서, 과업지시서 등 | rows: 7 | cols: 9] 컬럼: 단위업무명 / (대기능) | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | 합계 나. 세부항목별 소요예산 총괄표 (단위 : 천원 / 부가가치세 포함) [표 | 섹션: 별첨: 검토자료 및 변경 사업수행계획서, 과업지시서 등 | rows: 7 | cols: 9] 컬럼: 단위업무명 / (대기능) | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | 합계 3. 세부 산출 근거 1) AAA 가) AAA (단위 : 원) [표 | 섹션: 별첨: 검토자료 및 변경 사업수행계획서, 과업지시서 등 | rows: 7 | cols: 4] 컬럼: 구 분 | 산 출 내 역 | 금 액 | 비 고 그룹: 상세내역은 개발원가 산출내역 참조 그룹: 개발원가 x ( )% 그룹: 소 계 그룹: 부가가치세 그룹: 합 계 <ㅇㅇ원가 산출내역> ※사업특성에 따라 서식을 수정하여 작성가능 o [표 | 섹션: 별첨: 검토자료 및 변경 사업수행계획서, 과업지시서 등 | rows: 8 | cols: 6] 컬럼: col_1 | col_2 | col_3 | col_4 | col_5 | col_6 그룹: 총합계 [표 | 섹션: 별첨: 검토자료 및 변경 사업수행계획서, 과업지시서 등 | rows: 25 | cols: 11] 컬럼: 사업 / 내용 | 계약명 | ...
----------------------------------------------------------------------------------------------------
rank=4 score=0.3586331009864807 file=수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
chunk_type=text chunk_id=doc_000cc725bf29_text_text_0031_part_003_cf8cafd9fc79
자 : (직인) / 수산업협동조합중앙회 귀중 ※ 제안금액은 한글로 기재하고 아라비아 숫자를 병기 ※ 인감날인 후 입찰보증금, 가격산출내역서 및 기타 증빙과 같이 밀봉하여 제출 〈서식 제11호〉 가 격 산 출 내 역 서 □ 총사업비 : 일금 원 (￦ ) (단위 : 원) [표 | 섹션: 별지서식 | rows: 20 | cols: 8] 컬럼: 항 목 | col_2 | col_3 | 단 위 | 산출 내역 | col_6 | 구 성 비 | 비 고 그룹: 수 량 / 금 액 row_group: 수 량 / 금 액 | 항 목: 순 / 용 / 역 / 원 / 가 | col_2: ① / 노 / 무 / 비 | 단 위: 식 | 구 성 비: %
========================================================================================================================
CASE_ID: 4
EXPERIMENT: R0_p4_hwpx_690_v1_dense_top5
EVAL: eval_batch_25.csv / Q491
TYPE: B | DIFFICULTY: 중 | GT_DOC_COUNT: 2 | TOP1: 0.4374

QUESTION:
고양도시관리공사 다목적구장 예매망과 부산국제영화제의 행사 예약 포털은 시민들의 예약 트래픽을 처리하는 시스템입니다. 이들 시스템에서 사용자가 좌석이나 날짜를 고르고 신용카드 결제 버튼을 누른 후 PG사 통신 중에 '실수(혹은 에러)로 브라우저 뒤로 가기(Back)'를 누르는 트랜잭션 사고 유발 시, 데이터베이스 레이어에서 결제 중단(Rollback)을 수행해야 할 때 '독점 자원의 시간적 해제 속도' 민감도는 서로 어떻게 분기되나요?

GT_DOCS:
- 고양도시관리공사_관산근린공원 다목적구장 홈페이지 및 회원 통합운영.hwp
- (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp

RETRIEVED_DOCS:
- [text] 경상남도 사천시_사천시 문화체육시설 통합예약시스템 구축 사업(협상.hwp
- [text] 한국철도공사 (용역)_예약발매시스템 개량 ISMP 용역.hwp
- [text] 한국관광공사_2024 두루누비 시스템 고도화 및 통합유지운영.hwp
- [text] 수원도시공사_차세대 문화스포츠 시스템 구축 사업.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.43743860721588135 file=경상남도 사천시_사천시 문화체육시설 통합예약시스템 구축 사업(협상.hwp
chunk_type=text chunk_id=doc_c69c88b77b9d_text_text_0002_part_002_6b2ab72048df
약시스템 구축 - 최신 웹 트렌드 반영 및 사용자 중심의 콘텐츠 구성 - 편리한 정보 접근성을 위한 직관적인 메뉴 체계 구축 - 다양한 기기에 최적화된 화면을 제공하는“반응형 웹”구축 - 웹 접근성·호환성 등 웹사이트 구축 관련 법률 준수 나. 예약신청 프로그램 구축 - 문화체육시설별 사용자 예약신청 프로그램 구축(시설선택→일시선택→신청서 작성→(관리자승인)→마이페이지→결제) - 예약신청은 선착순 접수를 기본으로 구축하도록 함 - 기관 내 SMS 서비스 연동이 가능할 경우, 예약 흐름에 따른 문자발송이 가능하도록 문자발송시스템 구축 - 사천시민 여부를 확인하기 위한 비대면 자격확인서비스 연동 - 시설별 이용 금액에 대한 온라인결제 시스템 구축 - 법정요금감면 대상자가 온라인으로 대상자 확인이 될 수 있도록 서비스 연동 다. 예약신청 관리기능 구축 - 시설구분 및 신청 가능한 문화체육시설 등록 및 관리기능 - 각 시설별 예약 및 이용안내 정보 등록 및 관리기능 - 각 시설별 사용가능 부대시설 등록 및 관리기능 - 신청 가능한 사용자 우선순위 등록 및 관리기능 - 시설별 휴관일 관리기능 - 시설별 신청자 관리기능 - 사용시간, 사용료, 전용사용료, 예약가능일 관리 등 예약정보관리기능 - 사용료 감면정보관리기능 - 시설물 안내 및 유의사항 등 첨부파일 업로드 라. 사용자 중심의 화면 UI 기능 - 원하는 시설을 쉽고 빠르게 예약할 수 있는 ‘빠른예약서비스’ 구축 - 예약시설의 GIS기반 실시간 연동, 시설 위치정보 제공 - 모집별 상태정보(대기중, 접수중, 접수마감 등) 제공 마. 콘텐츠관리시스템(CMS) 구축 - 관리자 등록 및 권한 관리(전체관리자, 시설관리자 등) - 사이트, 메뉴, 콘텐츠 관리 - 프로그램 및 디자인관리 - 작업이력 및 접속로그 관리 - 통합게시판 및 프로그램 관리 ...
----------------------------------------------------------------------------------------------------
rank=2 score=0.4304025173187256 file=한국철도공사 (용역)_예약발매시스템 개량 ISMP 용역.hwp
chunk_type=text chunk_id=doc_2e602b107100_text_text_0002_part_002_ffcdf76aa945

## Diagnostic Deep Dive

Plain-text analysis for comparing P2/P4, reviewing failure and success cases, and deciding the next improvement direction. Run these cells after the existing evaluation and failure-analysis cells.

In [34]:
# ===== Plain-text diagnostic helpers =====
import sys
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

from collections import Counter
import math

DIAG_CONTEXT_CHARS = 700
DIAG_CASE_LIMIT = 8


def _diag_line(char="-", n=110):
    print(char * n)


def _diag_title(title):
    print("\n" + "=" * 110)
    print(title)
    print("=" * 110)


def _fmt_float(value, digits=4):
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
        return f"{float(value):.{digits}f}"
    except Exception:
        return str(value)


def _clean_text(value, max_chars=120):
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    return text if len(text) <= max_chars else text[:max_chars].rstrip() + " ..."


def _norm_docs(values):
    return [_normalize_doc_name_for_analysis(v) for v in values if str(v).strip()]


def _missing_gold_docs(pred_docs, gt_docs):
    pred = set(_norm_docs(pred_docs[:FINAL_TOP_K]))
    missing = []
    for doc in gt_docs:
        if _normalize_doc_name_for_analysis(doc) not in pred:
            missing.append(doc)
    return missing


def _context_precision(pred_docs, gt_docs, k=5):
    pred_norm = _norm_docs(pred_docs[:k])
    gt_norm = set(_norm_docs(gt_docs))
    if not pred_norm:
        return 0.0
    return sum(1 for doc in pred_norm if doc in gt_norm) / len(pred_norm)


def _duplicate_doc_rate(pred_docs, k=5):
    docs = [d for d in pred_docs[:k] if str(d).strip()]
    if not docs:
        return 0.0
    return 1 - (len(set(_norm_docs(docs))) / len(docs))


def _get_exp_cols():
    if "experiment_cols" in globals() and experiment_cols:
        return list(experiment_cols)
    return sorted(failure_df["experiment_id"].unique())


def _exp_alias(exp_id):
    return str(exp_id).split("_", 1)[0]


def _get_pred_record(exp_id, source_eval_file, qid):
    if "_DIAG_PRED_RECORDS" not in globals():
        return None
    return _DIAG_PRED_RECORDS.get(exp_id, {}).get((str(source_eval_file), str(qid)))


_DIAG_PRED_RECORDS = {}
for exp, pred_path in _prediction_paths:
    exp_id = getattr(exp, "experiment_id", str(exp))
    pred_df = _load_prediction_jsonl(Path(pred_path))
    lookup = {}
    for _, row in pred_df.iterrows():
        lookup[(str(row.get("source_eval_file", "")), str(row.get("id", "")))] = row.to_dict()
    _DIAG_PRED_RECORDS[exp_id] = lookup

_DIAG_EXPERIMENTS = _get_exp_cols()
_DIAG_BASE_EXP = _DIAG_EXPERIMENTS[0]
_DIAG_FINAL_EXP = _DIAG_EXPERIMENTS[-1]
print("diagnostic experiments:")
for exp_id in _DIAG_EXPERIMENTS:
    print(f"  {_exp_alias(exp_id)} = {exp_id}")

diagnostic experiments:
  R0 = R0_p4_hwpx_690_v1_dense_top5
  R1 = R1_p4_hwpx_690_v2_dense_rerank_top5
  R2 = R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5

In [35]:
# ===== Metric supplements: ranking, precision, duplicates =====
_diag_title("A) Supplemental retrieval metrics")
print("These metrics help explain why nDCG / recall changed even when Hit@5 is high.")
print()
header = f"{'EXP':<4} {'top1_hit':>9} {'avg_rank*':>9} {'median_rank*':>12} {'context_precision@5':>20} {'duplicate_doc_rate@5':>21} {'multi_recall@5':>15}"
print(header)
print("-" * len(header))
for exp_id in _DIAG_EXPERIMENTS:
    part = failure_df[failure_df["experiment_id"] == exp_id].copy()
    top1_hit = (part["first_gold_rank"] == 1).mean()
    penalized_rank = part["first_gold_rank"].fillna(FINAL_TOP_K + 1).astype(float)
    context_precision = part.apply(lambda r: _context_precision(r["retrieved_docs"], r["gt_docs"], FINAL_TOP_K), axis=1).mean()
    duplicate_rate = part.apply(lambda r: _duplicate_doc_rate(r["retrieved_docs"], FINAL_TOP_K), axis=1).mean()
    multi = part[part["gt_doc_count"] > 1]
    multi_recall = multi["doc_recall_at_5"].mean() if len(multi) else float("nan")
    print(
        f"{_exp_alias(exp_id):<4} "
        f"{top1_hit:>9.3f} "
        f"{penalized_rank.mean():>9.3f} "
        f"{penalized_rank.median():>12.3f} "
        f"{context_precision:>20.3f} "
        f"{duplicate_rate:>21.3f} "
        f"{multi_recall:>15.3f}"
    )
print()
print("* avg_rank/median_rank use 6 as penalty for a miss outside top5.")

_diag_title("B) Chunk type mix in final experiment")
final_part = failure_df[failure_df["experiment_id"] == _DIAG_FINAL_EXP].copy()
for hit_value, label in [(1, "HIT"), (0, "MISS")]:
    subset = final_part[final_part["hit_at_5"] == hit_value]
    counter = Counter()
    for xs in subset["retrieved_chunk_types"]:
        counter.update([x or "unknown" for x in xs])
    print(f"{label}: questions={len(subset)} chunk_type_counts={dict(counter)}")

==============================================================================================================
A) Supplemental retrieval metrics
==============================================================================================================
These metrics help explain why nDCG / recall changed even when Hit@5 is high.

EXP   top1_hit avg_rank* median_rank*  context_precision@5  duplicate_doc_rate@5  multi_recall@5
------------------------------------------------------------------------------------------------
R0       0.760     1.890        1.000                0.483                 0.000           0.652
R1       0.910     1.300        1.000                0.769                 0.000           0.714
R2       0.930     1.140        1.000                0.822                 0.000           0.748

* avg_rank/median_rank use 6 as penalty for a miss outside top5.

==============================================================================================================
B) Chunk type mix in final experiment
==============================================================================================================
HIT: questions=99 chunk_type_counts={'text': 131, 'table': 37, 'fact_candidates': 2}
MISS: questions=1 chunk_type_counts={'text': 3, 'table': 2}

In [36]:
# ===== Case review: recovered, regressed, all-missed, and multi-doc loss =====
# Important: hit_pivot is used only to SELECT cases.
# GT docs are always reloaded from eval_df by (source_eval_file, id).
# Retrieved contexts are always reloaded from prediction JSONL records.

def _print_docs(title, docs, max_items=5):
    print(title)
    docs = list(docs or [])
    if not docs:
        print("  - none")
        return
    for doc in docs[:max_items]:
        print("  -", doc)


def _eval_case_lookup(source_eval_file, qid):
    source_eval_file = str(source_eval_file)
    qid = str(qid)
    matches = eval_df[
        (eval_df["source_eval_file"].astype(str) == source_eval_file)
        & (eval_df["id"].astype(str) == qid)
    ]
    if matches.empty:
        return None
    row = matches.iloc[0]
    gt_docs = row.get("ground_truth_doc_list", [])
    if not isinstance(gt_docs, list):
        gt_docs = []
    return {
        "source_eval_file": source_eval_file,
        "id": qid,
        "question": row.get("question", ""),
        "type": row.get("type", ""),
        "difficulty": row.get("difficulty", ""),
        "gt_docs": gt_docs,
        "gt_doc_count": len(gt_docs),
    }


def _case_from_any_row(row):
    source_eval_file = str(row.get("source_eval_file", ""))
    qid = str(row.get("id", ""))
    case = _eval_case_lookup(source_eval_file, qid)
    if case is None:
        print("WARNING: GT docs not found for", source_eval_file, qid)
        return {
            "source_eval_file": source_eval_file,
            "id": qid,
            "question": row.get("question", ""),
            "type": row.get("type", ""),
            "difficulty": row.get("difficulty", ""),
            "gt_docs": [],
            "gt_doc_count": row.get("gt_doc_count", ""),
        }
    return case


def _print_case_summary(row, show_all_exp=False, context_chars=DIAG_CONTEXT_CHARS):
    case = _case_from_any_row(row)
    source_eval_file = case["source_eval_file"]
    qid = case["id"]
    gt_docs = case["gt_docs"]

    print("\n" + "-" * 110)
    print(
        f"CASE: {source_eval_file} / {qid} | "
        f"type={case.get('type')} | difficulty={case.get('difficulty')} | gt_doc_count={case.get('gt_doc_count')}"
    )
    print("QUESTION:", _clean_text(case.get("question", ""), 260))
    _print_docs("GT_DOCS:", gt_docs, 8)

    if not gt_docs:
        print("WARNING: empty GT docs. Treat this as an analysis-data issue before interpreting the case.")

    exp_ids = _DIAG_EXPERIMENTS if show_all_exp else [_DIAG_FINAL_EXP]
    for exp_id in exp_ids:
        rec = _get_pred_record(exp_id, source_eval_file, qid)
        if not rec:
            print(f"\n[{_exp_alias(exp_id)}] WARNING: prediction record not found")
            continue
        contexts = _safe_contexts(rec.get("retrieved_contexts", []))
        pred_docs = _context_doc_names(contexts)
        missing = _missing_gold_docs(pred_docs, gt_docs)
        hit = _hit_any_at_k(pred_docs, gt_docs, FINAL_TOP_K)
        recall = _doc_recall_at_k(pred_docs, gt_docs, FINAL_TOP_K)
        first_rank = _rank_first_gold(pred_docs, gt_docs, FINAL_TOP_K)
        precision = _context_precision(pred_docs, gt_docs, FINAL_TOP_K)
        dup_rate = _duplicate_doc_rate(pred_docs, FINAL_TOP_K)

        print(
            f"\n[{_exp_alias(exp_id)}] "
            f"hit={hit} recall={_fmt_float(recall)} precision={_fmt_float(precision)} "
            f"first_gold_rank={first_rank} missing_gold={len(missing)} dup_doc_rate={_fmt_float(dup_rate)}"
        )
        _print_docs("retrieved_docs:", pred_docs, FINAL_TOP_K)
        if missing:
            _print_docs("missing_gold_docs:", missing, 8)
        print("contexts:")
        for ctx in contexts[:FINAL_TOP_K]:
            meta = ctx.get("metadata") or {}
            text = _clean_text(str(ctx.get("text", "")).replace("\n", " "), context_chars)
            print(f"  #{ctx.get('rank')} score={_fmt_float(ctx.get('score'))} type={meta.get('chunk_type')} file={ctx.get('filename')}")
            print("   ", text)


def _print_case_list(title, rows, show_all_exp, context_chars, limit=DIAG_CASE_LIMIT):
    _diag_title(title)
    print(f"count={len(rows)}")
    if len(rows) == 0:
        return
    for _, row in rows.head(limit).iterrows():
        _print_case_summary(row, show_all_exp=show_all_exp, context_chars=context_chars)


if "hit_pivot" not in globals():
    raise RuntimeError("hit_pivot is missing. Run the previous failure analysis cells first.")

recovered = hit_pivot[(hit_pivot[_DIAG_BASE_EXP] == 0) & (hit_pivot[_DIAG_FINAL_EXP] == 1)].copy()
_print_case_list("C) Cases recovered by final R2 over baseline R0", recovered, show_all_exp=True, context_chars=360)

final_missed = hit_pivot[hit_pivot[_DIAG_FINAL_EXP] == 0].copy()
_print_case_list("D) Cases missed by final R2", final_missed, show_all_exp=True, context_chars=500)

final_rows = failure_df[failure_df["experiment_id"] == _DIAG_FINAL_EXP].copy()
multi_loss = final_rows[(final_rows["gt_doc_count"] > 1) & (final_rows["doc_recall_at_5"] < 1)].copy()
multi_loss = multi_loss.sort_values(["doc_recall_at_5", "first_gold_rank"], ascending=[True, True], na_position="last")
_print_case_list("E) Multi-doc cases where final R2 did not retrieve all gold docs", multi_loss, show_all_exp=False, context_chars=420)

==============================================================================================================
C) Cases recovered by final R2 over baseline R0
==============================================================================================================
count=13

--------------------------------------------------------------------------------------------------------------
CASE: eval_batch_02.csv / Q040 | type=E | difficulty=중 | gt_doc_count=1
QUESTION: 고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해서 간략히 요약좀 해줄래?
GT_DOCS:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf

[R0] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
  - 국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
  - 국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
missing_gold_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
contexts:
  #1 score=0.4001 type=text file=한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
    [문서: 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp | 사업명: 차세대 ERP 통합업무포털시스템 구축 용역 | 발주기관: 한국농어촌공사 | 섹션: 문서 시작 | 유형: text] Level 2: 예산관리 | Level 3: 6 | Level 4: 29 Level 2: 구매자재 | Level 3: 5 | Level 4: 24 Level 2: 인사관리 | Level 3: 12 | Level 4: 59 Level 2: 사업관리 | Level 3: 5 | Level 4: 18 Level 2: 자산관리 | Level 3: 10 | Level 4: 63 Level 2: 임대관리 | Level 3: 3 | Level 4: 14 ...
  #2 score=0.3682 type=text file=국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
    기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3 ...
  #3 score=0.3682 type=text file=국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
    기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3 ...

[R1] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
missing_gold_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
contexts:
  #1 score=0.0092 type=table file=한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp
    [문서: 한국농어촌공사_차세대 ERP 통합업무포털시스템 구축 용역.hwp | 사업명: 차세대 ERP 통합업무포털시스템 구축 용역 | 발주기관: 한국농어촌공사 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 7 | cols: 7] 컬럼: 비전 | col_2 | 변화에 대응하고 미래를 선도하는 차세대 ERP 구축 | col_4 | col_5 | col_6 | col_7 비전: 목표 | 변화에 대응하고 미래를 선도하는 차세대 ERP 구축: 효율적 경영자원 관리로 실시간 의사결정 체계 구축 비전: 추진 / 과제 | 변화에 대응하고 미래를 선도하는 차세대 ERP 구축: 최신 ERP 업그레이드 | col_5: ...

[R2] hit=1 recall=1.0000 precision=0.5000 first_gold_rank=2 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
contexts:
  #1 score=0.1739 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf | 사업명: 차세대 포털·학사 정보시스템 구축 사업 재공고 | 발주기관: 고려대학교 | 섹션: Ⅳ 제안요청 내용 | 유형: text] 요구사항 번호 SFR-포털-004 요구사항 명칭 사용자메인 요구 사항 상세 설명 정의 사용자메인 기능 정의 세부 내용 ❍ 포털 서비스 개인화 - 메인화면에서 고정영역과 변동영역을 구분하여 변동영역은 개인화가 가능하여야 함 - 사용자를 업무 역할 단위로 구분하여 서비스 및 콘텐츠를 차별화하여 제공 - 디자인 테마에 의한 계절별, 교내 중요행사별 등 포털 디자인 변경이 가능한 디자인 테마 기능 제공 -73- - 다중 신분자의 경우 포털 ...
  #2 score=0.0986 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: Ⅳ 제안요청 내용 | 유형: text] • 신분별 제공 서비스 관리 • 포털 서비스 관리 • 개인맞춤형 설정관리 • 캘린더관리 ❍ 통계관리 - 포털 서비스 이용 통계를 조회/확인/다운르도 할 수 있는 기능 구현 • 사용자 통계 • 방문 통계 • 콘텐츠 이용 / 서비스(메뉴) 이용 통계 등 ❍ 매뉴얼 관리 - 시스템 사용자 지침서 등록 및 변경 관리 기능 구현 -76- ❍ 관리자관리 - 포털 시스템 관리자 등록 및 변경 관리 기능 구현 • 관리자 통합계정관리(통합정보시스템 공통기능) • 관리 ...

--------------------------------------------------------------------------------------------------------------
CASE: eval_batch_03.csv / Q056 | type=C | difficulty=중 | gt_doc_count=1
QUESTION: 그렇다면 이 예산 하에서, 언급하신 주요 대학 구축 시스템 중 내부 기초 데이터 기반의 경영 구조 관련 부분은 어느 부문을 정확히 무엇을 도모하기 위해 전사 개선하고자 합니까?
GT_DOCS:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf

[R0] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
  - 국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
  - 성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
  - 서영대학교 산학협력단_전문대학 혁신지원사업 서영대학교 차세대 교육.hwp
missing_gold_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
contexts:
  #1 score=0.5652 type=text file=국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
    ws: 1 | cols: 3] 컬럼: 3 | col_2 | 사업 범위 가. 구축 범위 ○ 학사·행정 시스템 개발 - 학사·행정 시스템 개발 및 최적화 [표 | 섹션: 문서 시작 | rows: 33 | cols: 4] 컬럼: 구분 | 내 용 | col_3 | col_4 구분: 필수사항 | 내 용: ․ 유연한 학사제도 운영 가능(학기유연제, 비교과과정 등) / ․ 데이터 보안 및 개인정보 보호 강화 / ․ 통합 데이터 관리(데이터의 일관성, 정확성) / ․ 자동화 기능 및 프로세스 간소화 / ․ 운영자 모든 행위 로그 관리 / ․ 학교에 맞는 최적의 컨설팅 및 교육 제공 / ․ 대학정보공시, 교육기본통계조사 지침 통계자료 제공 col_3: ...
  #2 score=0.5652 type=text file=국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
    ws: 1 | cols: 3] 컬럼: 3 | col_2 | 사업 범위 가. 구축 범위 ○ 학사·행정 시스템 개발 - 학사·행정 시스템 개발 및 최적화 [표 | 섹션: 문서 시작 | rows: 33 | cols: 4] 컬럼: 구분 | 내 용 | col_3 | col_4 구분: 필수사항 | 내 용: ․ 유연한 학사제도 운영 가능(학기유연제, 비교과과정 등) / ․ 데이터 보안 및 개인정보 보호 강화 / ․ 통합 데이터 관리(데이터의 일관성, 정확성) / ․ 자동화 기능 및 프로세스 간소화 / ․ 운영자 모든 행위 로그 관리 / ․ 학교에 맞는 최적의 컨설팅 및 교육 제공 / ․ 대학정보공시, 교육기본통계조사 지침 통계자료 제공 col_3: ...
  #3 score=0.5434 type=text file=성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
    대응할 수 있는 반응형 웹 기반의 대학 홈페이지 구축 필요 3. 추진배경 가. 우리 대학 비전인“(Life 4.0 Plus) 보다 나은 미래를 공유하는 대학” 목표 달성을 위한 기반 마련 나. 데이터 기반의 정책 수립 필요성과 업무 처리를 위한 다양한 정보서비스 수요 증가에 따라 신속한 의사 결정 체계 마련 및 교육환경 변화에 유연한 대응을 위해 차세대 통합정보시스템 구축 추진 4. 사업범위 가. 정보시스템 구축  통합정보시스템 고도화 - 학생성공을 위한 학생의 각종 비교과 활동, 경력, 상담, 학과 및 학생인증체계 등의 데이터를 효과적으로 관리 및 연계하는 학사정보시스템 구축 - 1차년도에 납품/설치된 솔루션 기준으로 진행한 갭분석 ...
  #4 score=0.5409 type=text file=서영대학교 산학협력단_전문대학 혁신지원사업 서영대학교 차세대 교육.hwp
    실용교육선도대학” 목표 달성을 위한 기반 마련  데이터 기반의 정책 수립 필요성과 업무 처리를 위한 다양한 정보서비스 수요 증가에 따라 신속한 의사 결정 체계 마련 및 교육환경 변화에 유연한 대응을 위해 차세대 교육혁신지원시스템 구축 3단계 사업 추진 나. 사업목적  산재된 정보를 체계적으로 집중화시켜 사용자(학생/교원/직원 등) 중심의 정보서비스 제공  업무 프로세스 재설계 및 개선을 통한 효율적인 시스템 구축  정보시스템 기반 업무 처리로 고효율의 행정서비스 지원  다양한 스마트 기기 접속을 지원하는 구성원별 모바일 서비스 제공  PC 및 모바일 환경의 일관성 유지를 위한 HTML5 기반 표준 UI/UX 체계 구축  효율 ...

[R1] hit=1 recall=1.0000 precision=0.2000 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - 목포가톨릭대학교_목포가톨릭대학교 성과관리시스템(IR 센터) 구축 용역.pdf
  - 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - 성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
  - 대한소방공제회_회원지원시스템 고도화 및 내부구조 개선.hwp
contexts:
  #1 score=0.1519 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text] [별첨] ················································································································ 248~297 -4- I 사업 개요 1. 사업개요 가. 사업명: 고려대학교 차세대 포털·학사 정보시스템 구축 사업 나. 사업기간: 계약일로부터 24개월 이내 다. 무상유지보수기간 : 사업종료일로부터 12개월 라. 사업예산 : 11,270,000,000 ...
  #2 score=0.1051 type=text file=목포가톨릭대학교_목포가톨릭대학교 성과관리시스템(IR 센터) 구축 용역.pdf
    권한관리: 예시) 관리자, 운영 주체(부서, 학과), 교직원 - 각 평가 요소별 관리자 및 전체관리자 지정 기능 ◦ 연계/연동 - 로그인 시 SSO 연동 - 학사행정시스템의 조직정보, 교직원 및 사용자정보 연계 - 시스템에 사용되는 각종 증빙자료들 관리 - 9 - 나. 시스템 구축의 주요 기능 관련 요구사항 ◦ 대학경영 성과측정·관리 - 학교의 중장기 발전계획, 기관인증평가에 대한 사업의 등록과 관리방안 제공 - 중심이 되는 성과관리를 위한 핵심지표와 공유되어야 하며 이를 각 부서별 목표로 관리될 수 있어야 함 - 과제와 목표를 도식화해서 표현하고 이에 대한 현황정보 표현 - 대학의 변화에 따라 신규 과제나 목표를 등록하고 이를 기존의 ...
  #3 score=0.1042 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf | 사업명: 차세대 포털·학사 정보시스템 구축 사업 재공고 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text] [별첨] ················································································································ 248~297 -4- I 사업 개요 1. 사업개요 가. 사업명: 고려대학교 차세대 포털·학사 정보시스템 구축 사업 나. 사업기간: 계약일로부터 24개월 이내 다. 무상유지보수기간 : 사업종료일로부터 12개월 라. 사업예산 : 11,2 ...
  #4 score=0.0367 type=text file=성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
    대응할 수 있는 반응형 웹 기반의 대학 홈페이지 구축 필요 3. 추진배경 가. 우리 대학 비전인“(Life 4.0 Plus) 보다 나은 미래를 공유하는 대학” 목표 달성을 위한 기반 마련 나. 데이터 기반의 정책 수립 필요성과 업무 처리를 위한 다양한 정보서비스 수요 증가에 따라 신속한 의사 결정 체계 마련 및 교육환경 변화에 유연한 대응을 위해 차세대 통합정보시스템 구축 추진 4. 사업범위 가. 정보시스템 구축  통합정보시스템 고도화 - 학생성공을 위한 학생의 각종 비교과 활동, 경력, 상담, 학과 및 학생인증체계 등의 데이터를 효과적으로 관리 및 연계하는 학사정보시스템 구축 - 1차년도에 납품/설치된 솔루션 기준으로 진행한 갭분석 ...
  #5 score=0.0224 type=text file=대한소방공제회_회원지원시스템 고도화 및 내부구조 개선.hwp
    성 강화 o (회원 DB 재설계 및 구축) 데이터 표준관리 체계에 적합한 회원 DB 재설계 결과를 기반으로 시스템 개발을 통한 데이터 품질 향상 6. 정보시스템 현황 1. 추진 목표 o 내부 구조 및 기능 개선으로 효율적인 업무 수행과 데이터 기반 의사결정 환경 조성 o (데이터기반 의사결정체계 구축) 효율적인 데이터기반 분석을 위한 DM(데이터 마트) 설계 및 구축하여 직관적인 대시보드를 제공 o (데이터 표준관리 체계 구축) 전체 데이터베이스에 데이터 표준 적용과 구조 반영 변경을 통해 운영 효율화 및 생산성 향상 o (회원 시스템 구조 개선) 업무 규정 및 환경변화로 인한 프로세스 개선 및 시스템 고도화

[R2] hit=1 recall=1.0000 precision=0.2500 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - 성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
  - 대한소방공제회_회원지원시스템 고도화 및 내부구조 개선.hwp
contexts:
  #1 score=0.1519 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text] [별첨] ················································································································ 248~297 -4- I 사업 개요 1. 사업개요 가. 사업명: 고려대학교 차세대 포털·학사 정보시스템 구축 사업 나. 사업기간: 계약일로부터 24개월 이내 다. 무상유지보수기간 : 사업종료일로부터 12개월 라. 사업예산 : 11,270,000,000 ...
  #2 score=0.1042 type=text file=고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
    [문서: 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf | 사업명: 차세대 포털·학사 정보시스템 구축 사업 재공고 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text] [별첨] ················································································································ 248~297 -4- I 사업 개요 1. 사업개요 가. 사업명: 고려대학교 차세대 포털·학사 정보시스템 구축 사업 나. 사업기간: 계약일로부터 24개월 이내 다. 무상유지보수기간 : 사업종료일로부터 12개월 라. 사업예산 : 11,2 ...
  #3 score=0.0367 type=text file=성운대학교 산학협력단_「2024년 전문대학 혁신지원사업」차세대 통합정.hwp
    대응할 수 있는 반응형 웹 기반의 대학 홈페이지 구축 필요 3. 추진배경 가. 우리 대학 비전인“(Life 4.0 Plus) 보다 나은 미래를 공유하는 대학” 목표 달성을 위한 기반 마련 나. 데이터 기반의 정책 수립 필요성과 업무 처리를 위한 다양한 정보서비스 수요 증가에 따라 신속한 의사 결정 체계 마련 및 교육환경 변화에 유연한 대응을 위해 차세대 통합정보시스템 구축 추진 4. 사업범위 가. 정보시스템 구축  통합정보시스템 고도화 - 학생성공을 위한 학생의 각종 비교과 활동, 경력, 상담, 학과 및 학생인증체계 등의 데이터를 효과적으로 관리 및 연계하는 학사정보시스템 구축 - 1차년도에 납품/설치된 솔루션 기준으로 진행한 갭분석 ...
  #4 score=0.0224 type=text file=대한소방공제회_회원지원시스템 고도화 및 내부구조 개선.hwp
    성 강화 o (회원 DB 재설계 및 구축) 데이터 표준관리 체계에 적합한 회원 DB 재설계 결과를 기반으로 시스템 개발을 통한 데이터 품질 향상 6. 정보시스템 현황 1. 추진 목표 o 내부 구조 및 기능 개선으로 효율적인 업무 수행과 데이터 기반 의사결정 환경 조성 o (데이터기반 의사결정체계 구축) 효율적인 데이터기반 분석을 위한 DM(데이터 마트) 설계 및 구축하여 직관적인 대시보드를 제공 o (데이터 표준관리 체계 구축) 전체 데이터베이스에 데이터 표준 적용과 구조 반영 변경을 통해 운영 효율화 및 생산성 향상 o (회원 시스템 구조 개선) 업무 규정 및 환경변화로 인한 프로세스 개선 및 시스템 고도화

--------------------------------------------------------------------------------------------------------------
CASE: eval_batch_04.csv / Q078 | type=D | difficulty=중 | gt_doc_count=1
QUESTION: 나노종합기술원이 발주한 23.4억여 원의 '스마트 팹 서비스 설비온라인 사업' 관련 제안서에 규정된 개발진의 야근 및 연장 근무 수당의 일별 최대 인정 한도액은 얼마입니까?
GT_DOCS:
  - 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp

[R0] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 한국청소년활동진흥원_KYWA 내부행정시스템 이중화 사업 용역.hwp
  - 한국청소년활동진흥원_KYWA 내부행정시스템 이중화 용역.hwp
  - 한영대학_한영대학교 특성화 맞춤형 교육환경 구축 - 트랙운영 학사정보.hwp
  - 세종특별자치시시설관리공단_공공임대주택 종합관리시스템 구축용역.hwp
  - 가톨릭대학교 성심교정_[대학혁신지원사업] 가톨릭대학교 CUK 혁신허브 .hwp
missing_gold_docs:
  - 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp
contexts:
  #1 score=0.4510 type=text file=한국청소년활동진흥원_KYWA 내부행정시스템 이중화 사업 용역.hwp
    | D B: 2 | 네트워크: 1 | 기타: 4 | 누계: 14 ※ ( )는 임대장비 보유 대수 ○ 1년 365일 24시간 상시 유지관리 지원체계 제공 - Hot Line 개설을 통한 전담 유지관리 지원체계 구축 - 보안사고 발생에 대한 지원체계 구축 4. 기대효과 ○ 정기점검 및 상시 시스템 분석을 통해 위탁장비에 대한 최적의 운영환경을 유지함으로써 양질의 정보서비스를 제공 - 전문기관의 위탁 관리로 보안성 확보 및 최적의 장비운영 상태 유지 ○ 장애발생 시, 신속하고 체계적인 정보 보수체계를 구축함으로써 경영정보시스템 및 기관 통합WEB 이용자에 대한 서비스 중단 최소화 - 정보시스템 운영의 안정화로 24시간 365일 장애 없는 업무 ...
  #2 score=0.4510 type=text file=한국청소년활동진흥원_KYWA 내부행정시스템 이중화 용역.hwp
    | D B: 2 | 네트워크: 1 | 기타: 4 | 누계: 14 ※ ( )는 임대장비 보유 대수 ○ 1년 365일 24시간 상시 유지관리 지원체계 제공 - Hot Line 개설을 통한 전담 유지관리 지원체계 구축 - 보안사고 발생에 대한 지원체계 구축 4. 기대효과 ○ 정기점검 및 상시 시스템 분석을 통해 위탁장비에 대한 최적의 운영환경을 유지함으로써 양질의 정보서비스를 제공 - 전문기관의 위탁 관리로 보안성 확보 및 최적의 장비운영 상태 유지 ○ 장애발생 시, 신속하고 체계적인 정보 보수체계를 구축함으로써 경영정보시스템 및 기관 통합WEB 이용자에 대한 서비스 중단 최소화 - 정보시스템 운영의 안정화로 24시간 365일 장애 없는 업무 ...
  #3 score=0.3944 type=text file=한영대학_한영대학교 특성화 맞춤형 교육환경 구축 - 트랙운영 학사정보.hwp
    업환경은 상호 협의하여 결정하되, 관련비용은 제안사 부담으로 함 ○ 본 사업의 수행에 필요한 모든 비용은 가격입찰금액에 포함시켜야 함 ○ 본 사업은 용역에 해당하는 사업임으로 지체 상금율은 기성고 인정 금액을 제외하고 당해 연도 계약금액의 1,000분의 1.25로 함 ○ 본 사업의 하자담보책임기간은 사업을 종료한 날(사업에 대한 시험 및 검사를 수행하여 최종산출물을 인도한 날을 말함)부터 1년으로 함 ○ 제안 핵심인력은 자사 핵심인력으로 구성하여야 함 - 채용 예정 핵심인력인 경우에는 별도로 이를 명기하고, 계약체결 전까지 채용을 완료하여야 함 - 적법한 파견근로자는 자사인력으로 간주하나, 원 소속사를 반드시 명기하여야 함 - 단, 상용 ...
  #4 score=0.3920 type=text file=세종특별자치시시설관리공단_공공임대주택 종합관리시스템 구축용역.hwp
    확정하였음. [붙임19] “과업 종합심의 결과서 및 적정기간 종합산정서” 참고 ❍ 사 업 비 : 금150,000,000원(VAT포함) ❍ 계약방법 : 제한경쟁입찰(협상에 의한 계약) ※ (법적근거) 「지방자치단체를 당사자로 하는 계약에 관한 법률」시행령 제43, 44 ※ 본 사업은「소프트웨어사업 계약 및 관리감독에 관한 지침」 제36조제4호1항에 따른 “단일기관 내부사용 목적의 사업”으로 소프트웨어사업 영향평가 제외대상 사업임 ※ 본 사업은「소프트웨어 진흥법」제50조에 따른 과업내용 확정을 위하여 과업 심의위원회를 개최 한 사업임 4. 사업과제 ❍ 대민 서비스, 내부 행정업무의 최신기술을 통한 경쟁력을 확보하고 서비스 개선을 통한 만족도 ...
  #5 score=0.3913 type=text file=가톨릭대학교 성심교정_[대학혁신지원사업] 가톨릭대학교 CUK 혁신허브 .hwp
    않으며 본 제안과 관련된 일체의 소요비용은 입찰참가자의 부담으로 함 ※ 본 사업은 사업예산 20억 미만의 소프트웨어 사업으로, 「소프트웨어사업의 제안서 보상기준 등에 관한 운영규정」(과학기술정보통신부고시 제2016-108호) 제2조에 의거 제안서 보상은 실시하지 않음 ❍ 입찰공고문, 제안안내서, 제안요청서 및 이에 근거한 붙임 등에 명시되지 않은 사항은 지방자치단체를 당사자로 하는 계약에 관한 법률, 소프트웨어 진흥법, 기획재정부 계약예규, 국제표준규격 등 관련 규정 및 발주기관의 계약 요령에 따름 ❍ 제안내용에 대한 확인을 위하여 추가자료 요청 또는 현지실사를 할 수 있으며 입찰참가자는 이에 응하여야 함 ❍ 제안서 인력은 자사인력으로 ...

[R1] hit=1 recall=1.0000 precision=1.0000 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp
contexts:
  #1 score=0.7975 type=text file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp
    [문서: 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp | 사업명: 스마트 팹 서비스 활용체계 구축관련 설비온라인 시스 | 발주기관: 나노종합기술원 | 섹션: 문서 시작 | 유형: text] 1. 사업 개요 1.1. 개 요 1.2. 추진배경 및 필요성 1.3. 사업범위 1.4. 주요사업내용 1.5. 시스템 구성현황 1.6. 기대효과 2. 사업 추진계획 2.1. 추진목표 2.2. 추진전략 2.3. 추진체계 2.4. 추진일정 3. 제안안내 3.1. 일반사항 3.2. 기타사항 4. 제안요청 내용 4.1. 목표시스템 개념도 4.2. 기술원 Work process 현황 비교 4.3. 세부 제안내용 4.4. 상세 요구사항 ...

[R2] hit=1 recall=1.0000 precision=1.0000 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp
contexts:
  #1 score=0.7975 type=text file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp
    [문서: 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp | 사업명: 스마트 팹 서비스 활용체계 구축관련 설비온라인 시스 | 발주기관: 나노종합기술원 | 섹션: 문서 시작 | 유형: text] 1. 사업 개요 1.1. 개 요 1.2. 추진배경 및 필요성 1.3. 사업범위 1.4. 주요사업내용 1.5. 시스템 구성현황 1.6. 기대효과 2. 사업 추진계획 2.1. 추진목표 2.2. 추진전략 2.3. 추진체계 2.4. 추진일정 3. 제안안내 3.1. 일반사항 3.2. 기타사항 4. 제안요청 내용 4.1. 목표시스템 개념도 4.2. 기술원 Work process 현황 비교 4.3. 세부 제안내용 4.4. 상세 요구사항 ...

--------------------------------------------------------------------------------------------------------------
CASE: eval_batch_04.csv / Q079 | type=E | difficulty=하 | gt_doc_count=1
QUESTION: 쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?
GT_DOCS:
  - 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp

[R0] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
  - 한국농어촌공사_라오스 댐안전관리 시스템 구축사업 PMC용역.hwp
  - 국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
  - KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
missing_gold_docs:
  - 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp
contexts:
  #1 score=0.3298 type=text file=수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
    자 : (직인) / 수산업협동조합중앙회 귀중 ※ 제안금액은 한글로 기재하고 아라비아 숫자를 병기 ※ 인감날인 후 입찰보증금, 가격산출내역서 및 기타 증빙과 같이 밀봉하여 제출 〈서식 제11호〉 가 격 산 출 내 역 서 □ 총사업비 : 일금 원 (￦ ) (단위 : 원) [표 | 섹션: 별지서식 | rows: 20 | cols: 8] 컬럼: 항 목 | col_2 | col_3 | 단 위 | 산출 내역 | col_6 | 구 성 비 | 비 고 그룹: 수 량 / 금 액 row_group: 수 량 / 금 액 | 항 목: 순 / 용 / 역 / 원 / 가 | col_2: ① / 노 / 무 / 비 | 단 위: 식 | 구 성 비: %
  #2 score=0.3113 type=text file=한국농어촌공사_라오스 댐안전관리 시스템 구축사업 PMC용역.hwp
    Management System Project in Lao P.D.R 나. 용역기간 : 2024년 ~ 2028년(5개년) ○ 1차년도 : 계약체결일로부터 2024.12.20일까지 다. 용역금액 : 4,555,441,000원 (영세율, 손해배상보험(공제)료 포함) 라. 대상지 : (마스터 플랜) 라오스 전역 농업용 댐 비엔티안 캐피탈 싸이타니구 동막카이마을 * 용역 수행 시 수원국 및 발주처의 요청에 따라 변동될 수 있음 마. 용역범위 [표 | 섹션: 문서 시작 | rows: 9 | cols: 2] 컬럼: 구 분 | 사업내용 구 분: 사업관리 | 사업내용: ㅇ사업총괄 관리 / - 사업진도보고(착수신고, 월간공정보고, 연차별 실적보고, 최종 ...
  #3 score=0.3081 type=text file=국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
    함): 69,090,909 | 수량: 1 품 목: HPE nimble HF20 dual contraller storage raw 126T, usable 101, 11.52Tb cache -> 100테라 | 제품단가(부가세 미포함): 131,818,182 | 수량: 1 구분: L2 스위치 - 암데이터 관리기반 2차 | 품 목: Catalyst 2960-X 48 GigE, 2 x 10G SFP+, LAN Base | 제품단가(부가세 미포함): 7,727,273 | 수량: 2 구분: L4 스위치 - 암데이터 관리기반 2차 | 품 목: PAS-K 3200X | 제품단가(부가세 미포함): 57,727,273 | 수량: 2 구분: 스토리지 유지보수 ...
  #4 score=0.2942 type=text file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
    [문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] 약어: WAS | 영어 표기: Web Application Server | 한글 명칭: 웹 어플리케이션 서버 약어: WEB | 영어 표기: World Wide Web | 한글 명칭: 월드와이드웹(인터넷) 약어: WUA | 영어 표기: Water User Association | 한글 명칭: 물 사용자 협의체 약어: XML | 영어 표기: eXtensible Markup Language | 한 ...
  #5 score=0.2849 type=text file=사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
    [문서: 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp | 사업명: 우즈벡-키르기즈스탄 기후변화대응 스 | 발주기관: 사단법인아시아물위원회사무국 | 섹션: Ⅵ. 서식 | 유형: text] 1. 용역 개요 가. 용역명 ❍ (국문) 우즈벡-키르기즈스탄 기후변화대응 스마트 관개시스템 구축사업 ❍ (영문) Strengthening Climate Resilience through Introduction of Innovative Smart Techniques in Flood and Drought Management in Ozbekistan-Kyrgyzstan 나. 용역기간 : 계약체결일로부터 2027년 12월 31일 까지 다 ...

[R1] hit=1 recall=1.0000 precision=1.0000 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp
contexts:
  #1 score=0.1307 type=text file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp
    [문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: text] 1.19 과업수행자의 실명화 1.19.1 용역감독원의 실명화 감독원은 책임있는 용역감독을 위해 계약상대자가 제출하는 최종보고서에 감독을 수행한 감독원의 업무내용을 수록케 하고 계약상대자는 이에 따라야 한다.(별지 제5호서식) 1.19.2 용역참여기술자 실명화 계약상대자는 건설기술진흥법 제43조에 의거 보고서 및 제계산서 등 최종성과물에 참여한 기술자의 업무내용을 구체적으로 기재하여야 한다.(별지 제6호서식) 1.20 중점검 ...

[R2] hit=1 recall=1.0000 precision=1.0000 first_gold_rank=1 missing_gold=0 dup_doc_rate=0.0000
retrieved_docs:
  - 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp
contexts:
  #1 score=0.1307 type=text file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp
    [문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: text] 1.19 과업수행자의 실명화 1.19.1 용역감독원의 실명화 감독원은 책임있는 용역감독을 위해 계약상대자가 제출하는 최종보고서에 감독을 수행한 감독원의 업무내용을 수록케 하고 계약상대자는 이에 따라야 한다.(별지 제5호서식) 1.19.2 용역참여기술자 실명화 계약상대자는 건설기술진흥법 제43조에 의거 보고서 및 제계산서 등 최종성과물에 참여한 기술자의 업무내용을 구체적으로 기재하여야 한다.(별지 제6호서식) 1.20 중점검 ...

--------------------------------------------------------------------------------------------------------------
CASE: eval_batch_04.csv / Q080 | type=E | difficulty=하 | gt_doc_count=1
QUESTION: 그래드코뤼아레져가 올해 스톼트하는 그룹વે어 메신져 통함 쁠젝의 젼체 뻐젯은 정확히 어떻게 잡혔능가요.
GT_DOCS:
  - 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp

[R0] hit=0 recall=0.0000 precision=0.0000 first_gold_rank=None missing_gold=1 dup_doc_rate=0.0000
retrieved_docs:
  - 국가철도공단_철도산업정보센터 정보시스템 G-클라우드 1차 전환 용역.hwp
  - 전북특별자치도 정읍시_정읍체육트레이닝센터 통합운영관리시스템 구.hwp
  - 서울에너지공사_그룹웨어시스템 고도화 용역.hwp
  - 국립공원공단_2024년 자원통합관리시스템 운영관리.hwp
  - 한국수자원공사_수도사업장 통합 사고분석솔루션 시범구축 용역.hwp
missing_gold_docs:
  - 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
contexts:

In [37]:
# ===== Improvement direction memo from observed patterns =====
_diag_title("F) Improvement direction memo")
final_rows = failure_df[failure_df["experiment_id"] == _DIAG_FINAL_EXP].copy()
all_missed_count = len(final_rows[final_rows["hit_at_5"] == 0])
multi_loss_count = len(final_rows[(final_rows["gt_doc_count"] > 1) & (final_rows["doc_recall_at_5"] < 1)])

print(f"final_experiment={_DIAG_FINAL_EXP}")
print(f"all_missed_count={all_missed_count}")
print(f"multi_doc_partial_loss_count={multi_loss_count}")
print()
print("Recommended next checks:")
print("1. If all-missed questions contain noisy spellings or phonetic Korean, add query normalization/rewrite before retrieval.")
print("2. If multi-doc partial loss remains, evaluate top_k=8 or top_k=10 for final contexts, or use doc-level grouping before final selection.")
print("3. If table chunks dominate wrong hits, reduce noisy table fields such as repeated row_group labels or add table_type filtering.")
print("4. Compare whether the gold document is present in dense_top30 or BM25_top30 before reranking. This separates candidate-generation failure from reranker failure.")
print("5. Keep R1 as a practical default if latency matters; use R2 as fallback for low-confidence or multi-doc queries.")

==============================================================================================================
F) Improvement direction memo
==============================================================================================================
final_experiment=R2_p4_hwpx_690_v2_hybrid_rrf_rerank_top5
all_missed_count=1
multi_doc_partial_loss_count=21

Recommended next checks:
1. If all-missed questions contain noisy spellings or phonetic Korean, add query normalization/rewrite before retrieval.
2. If multi-doc partial loss remains, evaluate top_k=8 or top_k=10 for final contexts, or use doc-level grouping before final selection.
3. If table chunks dominate wrong hits, reduce noisy table fields such as repeated row_group labels or add table_type filtering.
4. Compare whether the gold document is present in dense_top30 or BM25_top30 before reranking. This separates candidate-generation failure from reranker failure.
5. Keep R1 as a practical default if latency matters; use R2 as fallback for low-confidence or multi-doc queries.

## Candidate Stage Analysis

Checks where gold documents disappear for final failures and multi-doc partial losses. This does not rebuild embeddings or Chroma; it reuses the current runtime collections/BM25 objects.

In [32]:
# ===== Candidate-stage analysis: dense top30 vs BM25 top30 vs RRF vs final top5 =====
# Run after cells 17-24. Expected time on live runtime: usually 1-7 minutes for sample100.

CANDIDATE_CASE_LIMIT = 40
CANDIDATE_DENSE_TOP_K = 30
CANDIDATE_BM25_TOP_K = 30
CANDIDATE_RRF_TOP_K = 30


def _candidate_gold_stats(items, gt_docs, k):
    docs = _context_doc_names(items[:k])
    gt_norm = set(_norm_docs(gt_docs))
    pred_norm = _norm_docs(docs)
    hit_docs = [doc for doc in gt_docs if _normalize_doc_name_for_analysis(doc) in set(pred_norm)]
    missing_docs = [doc for doc in gt_docs if _normalize_doc_name_for_analysis(doc) not in set(pred_norm)]
    first_rank = None
    for idx, doc in enumerate(pred_norm, start=1):
        if doc in gt_norm:
            first_rank = idx
            break
    recall = len(hit_docs) / len(gt_docs) if gt_docs else 0.0
    return {
        "hit_any": int(bool(hit_docs)),
        "recall": recall,
        "first_rank": first_rank,
        "hit_docs": hit_docs,
        "missing_docs": missing_docs,
    }


def _candidate_docs(items, k=5):
    docs = _context_doc_names(items[:k])
    types = _context_chunk_types(items[:k])
    return [f"[{t}] {d}" for d, t in zip(docs, types)]


def _analyze_candidate_stage_for_case(source_eval_file, qid):
    case = _eval_case_lookup(source_eval_file, qid)
    if case is None:
        return None
    question = case["question"]
    gt_docs = case["gt_docs"]

    dense_items, _, dense_ms = dense_candidates(collection_v2, question, n_results=CANDIDATE_DENSE_TOP_K)
    bm25_items = bm25_v2.search(question, top_k=CANDIDATE_BM25_TOP_K) if "bm25_v2" in globals() and bm25_v2 is not None else []
    rrf_items = rrf_fuse([dense_items, bm25_items], rrf_k=RRF_K, top_k=CANDIDATE_RRF_TOP_K)

    final_rec = _get_pred_record(_DIAG_FINAL_EXP, source_eval_file, qid)
    final_items = _safe_contexts(final_rec.get("retrieved_contexts", [])) if final_rec else []

    return {
        "case": case,
        "dense_ms": dense_ms,
        "dense": _candidate_gold_stats(dense_items, gt_docs, CANDIDATE_DENSE_TOP_K),
        "bm25": _candidate_gold_stats(bm25_items, gt_docs, CANDIDATE_BM25_TOP_K),
        "rrf": _candidate_gold_stats(rrf_items, gt_docs, CANDIDATE_RRF_TOP_K),
        "final": _candidate_gold_stats(final_items, gt_docs, FINAL_TOP_K),
        "dense_docs": _candidate_docs(dense_items, 5),
        "bm25_docs": _candidate_docs(bm25_items, 5),
        "rrf_docs": _candidate_docs(rrf_items, 5),
        "final_docs": _candidate_docs(final_items, 5),
    }


def _candidate_failure_reason(result):
    if result is None:
        return "analysis_lookup_failed"
    dense_hit = result["dense"]["hit_any"]
    bm25_hit = result["bm25"]["hit_any"]
    rrf_hit = result["rrf"]["hit_any"]
    final_hit = result["final"]["hit_any"]
    if not dense_hit and not bm25_hit:
        return "candidate_generation_failed"
    if (dense_hit or bm25_hit) and not rrf_hit:
        return "rrf_fusion_lost_gold"
    if rrf_hit and not final_hit:
        return "rerank_or_final_selection_lost_gold"
    if final_hit and result["final"]["recall"] < 1:
        return "partial_multi_doc_loss"
    return "ok"


def _print_candidate_stage_result(result, max_docs=5):
    case = result["case"]
    print("\n" + "=" * 120)
    print(f"CASE: {case['source_eval_file']} / {case['id']} | type={case['type']} | difficulty={case['difficulty']} | gt_doc_count={case['gt_doc_count']}")
    print("QUESTION:", _clean_text(case["question"], 240))
    _print_docs("GT_DOCS:", case["gt_docs"], 8)
    print("reason:", _candidate_failure_reason(result))
    print()
    header = f"{'stage':<8} {'hit':>3} {'recall':>7} {'first_rank':>10} {'missing_gold':>12}"
    print(header)
    print("-" * len(header))
    for stage in ["dense", "bm25", "rrf", "final"]:
        stat = result[stage]
        print(f"{stage:<8} {stat['hit_any']:>3} {stat['recall']:>7.3f} {str(stat['first_rank']):>10} {len(stat['missing_docs']):>12}")
    for stage in ["dense", "bm25", "rrf", "final"]:
        print(f"\n{stage.upper()} top docs:")
        docs = result[f"{stage}_docs"]
        if not docs:
            print("  - none")
        for doc in docs[:max_docs]:
            print("  -", doc)


_diag_title("G) Candidate-stage summary for final misses and multi-doc partial losses")
if "hit_pivot" not in globals() or "failure_df" not in globals():
    raise RuntimeError("Run failure analysis cells first: 17, 18, 22, 23, 24.")

final_missed_keys = []
if "hit_pivot" in globals():
    final_missed = hit_pivot[hit_pivot[_DIAG_FINAL_EXP] == 0].copy()
    final_missed_keys = [(str(r["source_eval_file"]), str(r["id"])) for _, r in final_missed.iterrows()]

final_rows = failure_df[failure_df["experiment_id"] == _DIAG_FINAL_EXP].copy()
multi_loss = final_rows[(final_rows["gt_doc_count"] > 1) & (final_rows["doc_recall_at_5"] < 1)].copy()
multi_loss_keys = [(str(r["source_eval_file"]), str(r["id"])) for _, r in multi_loss.iterrows()]

candidate_keys = []
for key in final_missed_keys + multi_loss_keys:
    if key not in candidate_keys:
        candidate_keys.append(key)
candidate_keys = candidate_keys[:CANDIDATE_CASE_LIMIT]
print("final_missed_cases:", len(final_missed_keys))
print("multi_doc_partial_loss_cases:", len(multi_loss_keys))
print("candidate_stage_cases_to_check:", len(candidate_keys))

candidate_results = []
for source_eval_file, qid in candidate_keys:
    result = _analyze_candidate_stage_for_case(source_eval_file, qid)
    if result is None:
        continue
    reason = _candidate_failure_reason(result)
    row = {
        "source_eval_file": source_eval_file,
        "id": qid,
        "type": result["case"]["type"],
        "difficulty": result["case"]["difficulty"],
        "gt_doc_count": result["case"]["gt_doc_count"],
        "question_short": _clean_text(result["case"]["question"], 80),
        "reason": reason,
    }
    for stage in ["dense", "bm25", "rrf", "final"]:
        row[f"{stage}_hit"] = result[stage]["hit_any"]
        row[f"{stage}_recall"] = result[stage]["recall"]
        row[f"{stage}_first_rank"] = result[stage]["first_rank"]
        row[f"{stage}_missing_count"] = len(result[stage]["missing_docs"])
    candidate_results.append((row, result))

candidate_stage_df = pd.DataFrame([x[0] for x in candidate_results])
candidate_stage_path = OUTPUT_DIR / "analysis" / f"candidate_stage_p4_hwpx_{CORPUS_LIMIT}_sample{EVAL_SAMPLE_SIZE or 'all'}.csv"
candidate_stage_df.to_csv(candidate_stage_path, index=False, encoding="utf-8-sig")
print("saved candidate stage csv:", candidate_stage_path)

print("\nReason counts:")
if not candidate_stage_df.empty:
    print(candidate_stage_df["reason"].value_counts().to_string())
else:
    print("none")

print("\nCompact cases:")
if not candidate_stage_df.empty:
    for _, row in candidate_stage_df.head(20).iterrows():
        print(
            f"- {row['source_eval_file']} / {row['id']} | reason={row['reason']} | "
            f"dense={row['dense_recall']:.2f} bm25={row['bm25_recall']:.2f} rrf={row['rrf_recall']:.2f} final={row['final_recall']:.2f} | "
            f"{row['question_short']}"
        )

_diag_title("H) Candidate-stage detailed examples")
for row, result in candidate_results[: min(8, len(candidate_results))]:
    _print_candidate_stage_result(result, max_docs=5)

==============================================================================================================
G) Candidate-stage summary for final misses and multi-doc partial losses
==============================================================================================================
final_missed_cases: 1
multi_doc_partial_loss_cases: 21
candidate_stage_cases_to_check: 22
saved candidate stage csv: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/analysis/candidate_stage_p4_hwpx_690_sample100.csv

Reason counts:
reason
partial_multi_doc_loss         21
candidate_generation_failed     1

Compact cases:
- eval_batch_12.csv / Q239 | reason=candidate_generation_failed | dense=0.00 bm25=0.00 rrf=0.00 final=0.00 | 그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
- eval_batch_01.csv / Q010 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | 국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다 ...
- eval_batch_02.csv / Q031 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | 국립중앙의료원의 위탁용역과 그랜드코리아레저(주)의 그룹웨어 구축 용역에서 각각 핵심으로 다루는 정보시스템의 업무 목적과 범위를 비교해 주십시오.
- eval_batch_02.csv / Q034 | reason=partial_multi_doc_loss | dense=1.00 bm25=0.33 rrf=0.67 final=0.67 | 코이카의 '우즈베키스탄 방송시스템 사업', 아시아물위원회의 '우즈벡-키르기즈스탄 관개시스템 사업', 수출입은행의 '모잠비크 ITS 타당성 조사 ...
- eval_batch_04.csv / Q069 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | 국립중앙의료원의 차세대 응급의료 상황관리시스템 예산(14억)과 한국원자력연구원의 선량평가시스템 고도화 예산 사이에 발생하는 차액은 얼마입니까?
- eval_batch_04.csv / Q074 | reason=partial_multi_doc_loss | dense=0.67 bm25=0.33 rrf=0.67 final=0.67 | 고려대학교의 '학사 정보시스템', 한국가스공사의 'ERP 차세대 통합시스템', 국립중앙의료원의 '차세대 응급의료 상황관리시스템' 사업을 통합하여 ...
- eval_batch_05.csv / Q091 | reason=partial_multi_doc_loss | dense=1.00 bm25=0.50 rrf=1.00 final=0.50 | 고려대학교의 '차세대 포털·학사 정보시스템' 사업과 한국가스공사의 '차세대 통합정보시스템(ERP)' 사업이 노후화된 업무 프로세스를 대체하기 위 ...
- eval_batch_07.csv / Q132 | reason=partial_multi_doc_loss | dense=1.00 bm25=1.00 rrf=1.00 final=0.50 | 인천공항운영서비스의 기존 ERP 시스템 고도화 사업과 경희대학교 산학협력단 정보시스템 운영 위탁 사업의 공통된 운영 연속성 향상 목표를 분석해 ...
- eval_batch_08.csv / Q149 | reason=partial_multi_doc_loss | dense=1.00 bm25=1.00 rrf=1.00 final=0.50 | 수자원공사의 사고분석솔루션 시범구축 비용(약 1.95억)과 한국연구재단 기초학문자료센터 DB구축 예산(약 2.12억) 중 어느 쪽에 더 많은 재 ...
- eval_batch_09.csv / Q174 | reason=partial_multi_doc_loss | dense=0.67 bm25=0.67 rrf=1.00 final=0.67 | 한국연구재단의 기초학문 원스톱 포털 사업 예산, 그리고 같은 기관의 UICC 실태조사 시스템 기능개선 사업의 예산을 병합한 다음, 이를 한국수자 ...
- eval_batch_10.csv / Q194 | reason=partial_multi_doc_loss | dense=1.00 bm25=0.25 rrf=1.00 final=0.50 | 한국수출입은행 모잠비크 마푸토 ITS 사업 타당성조사 예산과 인천공항운영서비스 차세대 ERP 시스템 사업 예산을 병합한 다음, 한국철도공사 예약 ...
- eval_batch_11.csv / Q212 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | 한국수자원공사 CMS 고도화 사업과 고려대학교 차세대 포털·학사 정보망 시스템 모두 레거시 플랫폼(기존 옛 시스템)을 완전 개편하려는 목적입니다 ...
- eval_batch_15.csv / Q291 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | (사)보험개발원의 실손보험 청구 전산화 체계와 을지대학교의 비교과시스템 개발 사업 간, 다루는 데이터망 접속자의 인구통계학적 스케일 차이는 어떻 ...
- eval_batch_16.csv / Q313 | reason=partial_multi_doc_loss | dense=0.33 bm25=0.67 rrf=0.67 final=0.67 | 코이카 전자조달 우즈베키스탄 방송망 예산 및 한국철도공사 모바일오피스 시스템, 대한민국 광주과학기술원 RCMS 예산을 비교 가능 범위 내 합산하 ...
- eval_batch_17.csv / Q334 | reason=partial_multi_doc_loss | dense=0.67 bm25=0.33 rrf=0.67 final=0.67 | 케빈랩이 구축하는 AI 기반 영상감시 시스템(3.41억)과 한국원자력연구원 선량평가 고도화(0.46억), 그리고 한국교육과정평가원 NCIC 예산 ...
- eval_batch_18.csv / Q348 | reason=partial_multi_doc_loss | dense=0.50 bm25=0.50 rrf=0.50 final=0.50 | 광주과학기술원의 RCMS 연계 모듈 개발(54,450,000원) 예산과 한국교육과정평가원의 NCIC 시스템 운영(50,000,000원) 예산을 ...
- eval_batch_18.csv / Q353 | reason=partial_multi_doc_loss | dense=0.33 bm25=0.33 rrf=0.67 final=0.33 | 코이카 우즈베키스탄 의정 방송 구축 사업비와 케빈랩 지자체 영상감시 시스템, 대한상공회의소 에너지 개편 과업의 배정 예산을 먼저 포괄 합산해 시 ...
- eval_batch_19.csv / Q372 | reason=partial_multi_doc_loss | dense=1.00 bm25=0.50 rrf=0.50 final=0.50 | 한국원자력연구원이 피폭량을 연산하는 시스템에 투자하는 비중 대비 서울시립대학교가 재학생들의 누적 점수를 종단분석(추적)하는 시스템이 요구하는 데 ...
- eval_batch_21.csv / Q407 | reason=partial_multi_doc_loss | dense=0.50 bm25=1.00 rrf=1.00 final=0.50 | 사단법인아시아물위원회사무국의 스마트 관개시스템 원조 예산(50.31억)과 서울특별시 여성가족재단의 디지털성범죄 지원센터 시스템 통합 예산(약 3 ...
- eval_batch_21.csv / Q411 | reason=partial_multi_doc_loss | dense=1.00 bm25=0.50 rrf=1.00 final=0.50 | 한국철도공사의 운행정보기록 자동분석시스템 개량과 (사)부산국제영화제의 BIFF 온라인서비스 재개발은 양쪽 모두 오프라인 현장의 '실시간 티켓 및 ...

==============================================================================================================
H) Candidate-stage detailed examples
==============================================================================================================

========================================================================================================================
CASE: eval_batch_12.csv / Q239 | type=E | difficulty=하 | gt_doc_count=1
QUESTION: 그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
GT_DOCS:
  - 사단법인 보험개발원_실손보험 청구 전산화 시스템 구축 사업.hwp
reason: candidate_generation_failed

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      0   0.000       None            1
bm25       0   0.000       None            1
rrf        0   0.000       None            1
final      0   0.000       None            1

DENSE top docs:
  - [text] 경기교통공사_2024 경기도 광역이동지원시스템 증설 및 기능개선 용역.hwp
  - [text] 해외건설협회_하노이시 기성시가지의 효율적 정비와 개선을 위한 도시.hwp
  - [text] 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp
  - [text] 경기도 부천시_2024년 부천문화재단 홈페이지 통합 및 대관시스템 구축(.hwp
  - [text] 해외건설협회_에티오피아 부동산 대량평가 시범시스템 구축 및 전국 확.hwp

BM25 top docs:
  - [text] 수협중앙회_정책보험 Web-EDI심사시스템 구축 PMO(사업관리) 입찰 공고.hwp
  - [text] 수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
  - [table] 한국산업은행_글로벌 표준 뱅킹시스템 재구축을 위한 PMO사업.hwp
  - [table] KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp
  - [text] 경상북도 경주시_경주 동궁과 월지 연꽃단지 디지털 야간경관 콘텐츠 제.hwp

RRF top docs:
  - [text] 경기교통공사_2024 경기도 광역이동지원시스템 증설 및 기능개선 용역.hwp
  - [text] 수협중앙회_정책보험 Web-EDI심사시스템 구축 PMO(사업관리) 입찰 공고.hwp
  - [text] 해외건설협회_하노이시 기성시가지의 효율적 정비와 개선을 위한 도시.hwp
  - [text] 수협중앙회_수협중앙회 예산회계시스템 재구축 ISP 수립.hwp
  - [text] 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp

FINAL top docs:
  - [text] 해외건설협회_에티오피아 부동산 대량평가 시범시스템 구축 및 전국 확.hwp
  - [text] 해외건설협회_K-스마트 도로관리시스템 기반 몽골 국가도로 디지털 도로.hwp
  - [table] 충청남도_충청남도 폭력피해자 보호·지원시설 업무관리시스템 구축 용.hwp
  - [text] 해외건설협회_하노이시 기성시가지의 효율적 정비와 개선을 위한 도시.hwp
  - [table] 한국학중앙연구원_한국학진흥사업 성과포털(2024년도분) 시스템 개선 및 .hwp

========================================================================================================================
CASE: eval_batch_01.csv / Q010 | type=B | difficulty=하 | gt_doc_count=2
QUESTION: 국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다. 두 기관 중 어느 곳의 예산이 더 많이 배정되었나요?
GT_DOCS:
  - 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   0.500          1            1
bm25       1   0.500          1            1
rrf        1   0.500          1            1
final      1   0.500          1            1

DENSE top docs:
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

BM25 top docs:
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

RRF top docs:
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

FINAL top docs:
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

========================================================================================================================
CASE: eval_batch_02.csv / Q031 | type=B | difficulty=중 | gt_doc_count=2
QUESTION: 국립중앙의료원의 위탁용역과 그랜드코리아레저(주)의 그룹웨어 구축 용역에서 각각 핵심으로 다루는 정보시스템의 업무 목적과 범위를 비교해 주십시오.
GT_DOCS:
  - 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   0.500          1            1
bm25       1   0.500          1            1
rrf        1   0.500          1            1
final      1   0.500          1            1

DENSE top docs:
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 대·중소기업·농어업협력재단_통합경영정보시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 국립중앙의료원_기부금 협력연구 연구행정통합시스템 구축 용역(재공고.hwp

BM25 top docs:
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [text] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp

RRF top docs:
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 대·중소기업·농어업협력재단_통합경영정보시스템 구축 용역.hwp
  - [text] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp

FINAL top docs:
  - [table] 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp

========================================================================================================================
CASE: eval_batch_02.csv / Q034 | type=B | difficulty=상 | gt_doc_count=3
QUESTION: 코이카의 '우즈베키스탄 방송시스템 사업', 아시아물위원회의 '우즈벡-키르기즈스탄 관개시스템 사업', 수출입은행의 '모잠비크 ITS 타당성 조사 사업'은 모두 중앙 및 해외 기관 원조 형식으로 수행되는 사업입니다. 이 세 사업의 주 대상국과 핵심 인프라 분야를 정리하고, 해당 예산 규모를 큰 금액부터 내림차순으로 나열하십시오.
GT_DOCS:
  - KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp
  - 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   1.000          3            0
bm25       1   0.333          1            2
rrf        1   0.667          1            1
final      1   0.667          1            1

DENSE top docs:
  - [table] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - [table] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - [table] 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp

BM25 top docs:
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [table] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [table] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp

RRF top docs:
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [table] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
  - [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp

FINAL top docs:
  - [table] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
  - [text] 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp
  - [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp

========================================================================================================================
CASE: eval_batch_04.csv / Q069 | type=B | difficulty=하 | gt_doc_count=2
QUESTION: 국립중앙의료원의 차세대 응급의료 상황관리시스템 예산(14억)과 한국원자력연구원의 선량평가시스템 고도화 예산 사이에 발생하는 차액은 얼마입니까?
GT_DOCS:
  - 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   0.500          1            1
bm25       1   0.500          1            1
rrf        1   0.500          1            1
final      1   0.500          1            1

DENSE top docs:
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

BM25 top docs:
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

RRF top docs:
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

FINAL top docs:
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

========================================================================================================================
CASE: eval_batch_04.csv / Q074 | type=B | difficulty=상 | gt_doc_count=3
QUESTION: 고려대학교의 '학사 정보시스템', 한국가스공사의 'ERP 차세대 통합시스템', 국립중앙의료원의 '차세대 응급의료 상황관리시스템' 사업을 통합하여 볼 때, 이 세 기관이 일관되게 기존에 부족하거나 파편화되어 겪던 운영 문제들의 공통된 실질 폐해는 무엇이고, 해당 전체 개선 사업 합산 예산은 얼마입니까?
GT_DOCS:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp
  - 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   0.667          2            1
bm25       1   0.333          1            2
rrf        1   0.667          2            1
final      1   0.667          1            1

DENSE top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 사단법인 대한간호협회_[긴급]『간호인력취업교육센터 통합관리 시스템.hwp
  - [text] 서영대학교 산학협력단_전문대학 혁신지원사업 서영대학교 차세대 교육.hwp
  - [table] 인덕대학 산학협력단_[2024_혁신사업] 차세대종합정보시스템 추가 개발(.hwp

BM25 top docs:
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

RRF top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [table] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp
  - [text] 사단법인 대한간호협회_[긴급]『간호인력취업교육센터 통합관리 시스템.hwp

FINAL top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp

========================================================================================================================
CASE: eval_batch_05.csv / Q091 | type=B | difficulty=중 | gt_doc_count=2
QUESTION: 고려대학교의 '차세대 포털·학사 정보시스템' 사업과 한국가스공사의 '차세대 통합정보시스템(ERP)' 사업이 노후화된 업무 프로세스를 대체하기 위해 공통으로 선택한 기술적 대응 기조는 무엇입니까?
GT_DOCS:
  - 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   1.000          1            0
bm25       1   0.500          1            1
rrf        1   1.000          1            0
final      1   0.500          1            1

DENSE top docs:
  - [text] 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf

BM25 top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 대구경북과학기술원_DGIST 차세대 대학정보시스템 구축 BPRISP 용역.hwp

RRF top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 대구경북과학기술원_DGIST 차세대 대학정보시스템 구축 BPRISP 용역.hwp
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf
  - [text] 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp

FINAL top docs:
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf
  - [text] 고려대학교_차세대 포털·학사 정보시스템 구축 사업 재공고.pdf

========================================================================================================================
CASE: eval_batch_07.csv / Q132 | type=B | difficulty=중 | gt_doc_count=2
QUESTION: 인천공항운영서비스의 기존 ERP 시스템 고도화 사업과 경희대학교 산학협력단 정보시스템 운영 위탁 사업의 공통된 운영 연속성 향상 목표를 분석해 보시오.
GT_DOCS:
  - 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp
  - 경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
reason: partial_multi_doc_loss

stage    hit  recall first_rank missing_gold
--------------------------------------------
dense      1   1.000          1            0
bm25       1   1.000          2            0
rrf        1   1.000          3            0
final      1   0.500          1            1

DENSE top docs:
  - [table] 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp
  - [text] 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp
  - [text] 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp
  - [text] 경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp
  - [text] 경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp

BM25 top docs:
  - [table] 경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [table] 경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [table] 경희대학교산학협력단_산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [table] 경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp
  - [table] 경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp

RRF top docs:
  - [text] 경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [text] 경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp
  - [text] 경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [text] 경희대학교산학협력단_산학협력단 정보시스템 운영 용역업체 선정.hwp
  - [table] 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp

FINAL top docs:
  - [table] 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp
  - [text] 경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp