# P4 HWPX 250 KoE5 Embedding + Retrieval Quick Check

이 노트북은 P4 HWPX 250 retrieval-ready corpus의 파일 크기와 retrieval 성능을 빠르게 확인하기 위한 Colab/GCV L4용 노트북입니다.

```text
1. 환경 확인
   ├─ Google Drive mount
   ├─ requirements.txt 설치
   └─ CUDA/GPU 라벨 기록

2. P4 HWPX 250 corpus 로드
   ├─ outputs/parsing_p3_690/chunks_v1_690.jsonl  # R0 clean text baseline
   └─ outputs/parsing_p3_690/chunks_v2_690.jsonl  # 구조화 corpus

3. Chroma 적재
   ├─ v1: clean text chunk만 임베딩
   └─ v2: text/table/fact_candidates chunk 임베딩, toc 제외

4. Retrieval quick check
   ├─ R0: v1 + KoE5 dense top5
   ├─ R1: v2 + KoE5 dense top30 -> reranker top5  # 이전 R4
   └─ R2: v2 + KoE5 dense top30 + BM25 top30 -> RRF top30 -> reranker top5  # 이전 R6

5. 평가
   ├─ eval_batch_01.csv ~ eval_batch_25.csv만 사용
   ├─ 기본 EVAL_SAMPLE_SIZE=100
   └─ outputs/retrieval_eval_p3/experiment_logs/retrieval_experiments.csv에 누적 기록
```

주의:

- 이 노트북 output은 크기가 커질 수 있으므로 GitHub push 전 필요하면 output clear를 권장합니다.
- 원본 RFP, source_store, Chroma DB, embedding cache는 GitHub 업로드 대상이 아닙니다.
- 임베딩 중복 저장을 피하기 위해 `.npy` embedding cache는 기본적으로 만들지 않습니다.

In [ ]:
# ===== Install dependencies in the active kernel =====
# VS Code connected to Colab must install packages inside the Colab runtime.

from pathlib import Path
import importlib.util
import os
import subprocess
import sys


def find_project_root_for_install() -> Path:
    candidates = [
        Path(os.environ.get('RFP_PROJECT_ROOT', '')) if os.environ.get('RFP_PROJECT_ROOT') else None,
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/Colab Notebooks/DB_RAG_Codeit_Project'),
        Path.cwd(),
        *Path.cwd().parents,
    ]
    for base in candidates:
        if base and (base / 'requirements.txt').exists():
            return base.resolve()

    try:
        from google.colab import drive
        drive.mount('/content/drive', force_remount=False)
    except Exception as exc:
        print('Google Drive mount skipped:', exc)

    search_roots = [Path('/content/drive/MyDrive'), Path('/content/drive/Shareddrives'), Path('/content/drive')]
    matches = []
    for root in search_roots:
        if root.exists():
            try:
                matches.extend(root.rglob('requirements.txt'))
            except Exception as exc:
                print(f'skip search root: {root} | {exc}')
    matches = sorted(set(matches), key=lambda p: (0 if 'DB_RAG_Codeit_Project' in str(p) else 1, len(str(p))))
    if matches:
        print('found requirements candidates:')
        for i, p in enumerate(matches[:10]):
            print(f'  [{i}] {p}')
        return matches[0].parent.resolve()

    raise FileNotFoundError('requirements.txt? /content/drive ???? ?? ?????.')


PROJECT_ROOT_FOR_INSTALL = find_project_root_for_install()
REQUIREMENTS_PATH = PROJECT_ROOT_FOR_INSTALL / 'requirements.txt'
print('PROJECT_ROOT_FOR_INSTALL:', PROJECT_ROOT_FOR_INSTALL)
print('REQUIREMENTS_PATH:', REQUIREMENTS_PATH)

REQUIRED_IMPORTS = {
    'chromadb': 'chromadb',
    'rank-bm25': 'rank_bm25',
    'sentence-transformers': 'sentence_transformers',
    'transformers': 'transformers',
    'openpyxl': 'openpyxl',
}
missing = [name for name, module in REQUIRED_IMPORTS.items() if importlib.util.find_spec(module) is None]

if missing:
    print('missing packages:', missing)
    print('installing:', REQUIREMENTS_PATH)
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', '-r', str(REQUIREMENTS_PATH)])
    print('dependency install complete. If imports still fail, restart the Colab runtime once and rerun from the top.')
else:
    print('required packages already installed')

PROJECT_ROOT_FOR_INSTALL: /content/drive/MyDrive/DB_RAG_Codeit_Project
REQUIREMENTS_PATH: /content/drive/MyDrive/DB_RAG_Codeit_Project/requirements.txt
required packages already installed

In [ ]:
from __future__ import annotations

import ast
import json
import math
import os
import random
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
import chromadb
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 180)

print("python:", sys.version.split()[0])
print("torch:", torch.__version__)
print("cuda_available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))

python: 3.12.13
torch: 2.10.0+cu128
cuda_available: True
gpu: NVIDIA L4

In [ ]:
# ===== User parameters =====
# Quick check default: P4 HWPX 250 corpus + 100 eval questions.

CORPUS_LIMIT = 250
EVAL_SAMPLE_SIZE = 100
EVAL_SAMPLE_SEED = 42

CORPUS_NAME = f"p4_hwpx_{CORPUS_LIMIT}"
CORPUS_COVERAGE = f"p4_hwpx_pilot_{CORPUS_LIMIT}_same_as_p3_sample"
CORPUS_VERSION_V1 = "v1_clean_text"
CORPUS_VERSION_V2 = "v2_hwpx_table_aware"

EMBEDDING_MODEL = "nlpai-lab/KoE5"
RERANKER_MODEL = "BAAI/bge-reranker-v2-m3"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150

EMBEDDING_BATCH_SIZE = 64
CHROMA_ADD_BATCH_SIZE = 512
RERANK_BATCH_SIZE = 32

FINAL_TOP_K = 5
DENSE_TOP_K = 30
BM25_TOP_K = 30
RRF_K = 60

RUN_RERANKER_EXPERIMENTS = True
RECREATE_CHROMA_COLLECTIONS = True
SAVE_EMBEDDING_CACHE = False  # ??: ?? ??? .npy cache? ??? ??

ENABLE_COVERAGE_GATE = True
MIN_TOP1_SCORE_FOR_WEAK_SIGNAL = 0.20
UNVERIFIED_ANSWER = "??? ???? ???? ????."

# Google Drive / Colab default. ?? ??? ??? ?? ?? ?? ???? RFP_PROJECT_ROOT env? ?????.
PROJECT_ROOT_OVERRIDE = "/content/drive/MyDrive/DB_RAG_Codeit_Project"
# GCV VM example. Uncomment on GCV and comment out the Google Drive line above.
# PROJECT_ROOT_OVERRIDE = "/home/USER/DB_RAG_Codeit_Project"

# Chroma? Google Drive? ?? ??/??? ??? ?? ? ???? Colab ?? ???? ????? ?????.
# predictions/csv? OUTPUT_DIR? ?? Google Drive? ?????.
LOCAL_CHROMA_ROOT_OVERRIDE = "/content/chroma_retrieval_eval_p4_hwpx"
# GCV VM example:
# LOCAL_CHROMA_ROOT_OVERRIDE = "/tmp/chroma_retrieval_eval_p4_hwpx"


def _project_root_score(path: Path) -> tuple:
    text = str(path).replace('\\', '/')
    return (
        0 if 'DB_RAG_Codeit_Project' in text else 1,
        0 if (path / 'outputs' / f'parsing_p4_hwpx_{CORPUS_LIMIT}').exists() else 1,
        len(text),
    )


def detect_project_root() -> Path:
    candidates = []
    env_root = os.environ.get('RFP_PROJECT_ROOT')
    if env_root:
        candidates.append(Path(env_root))
    if PROJECT_ROOT_OVERRIDE:
        candidates.append(Path(PROJECT_ROOT_OVERRIDE))
    candidates.extend([
        Path.cwd(),
        *Path.cwd().parents,
        Path('/content/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/DB_RAG_Codeit_Project/DB_RAG_Codeit_Project'),
        Path('/content/drive/MyDrive/Colab Notebooks/DB_RAG_Codeit_Project'),
        Path(r'C:/Users/yoosy/Desktop/codeit/project_2nd'),
    ])
    seen = set()
    for base in candidates:
        key = str(base)
        if key in seen:
            continue
        seen.add(key)
        if (base / 'outputs' / f'parsing_p4_hwpx_{CORPUS_LIMIT}' / f'chunks_v2_{CORPUS_LIMIT}.jsonl').exists():
            return base.resolve()
        if (base / 'notebooks' / 'rag').exists() and (base / 'requirements.txt').exists():
            return base.resolve()

    search_roots = [Path('/content/drive/MyDrive'), Path('/content/drive/Shareddrives'), Path('/content/drive')]
    matches = []
    target = Path('outputs') / f'parsing_p4_hwpx_{CORPUS_LIMIT}' / f'chunks_v2_{CORPUS_LIMIT}.jsonl'
    for root in search_roots:
        if root.exists():
            try:
                matches.extend(root.rglob(str(target)))
            except Exception as exc:
                print(f'skip search root: {root} | {exc}')
    matches = sorted(set(matches), key=lambda p: _project_root_score(p.parents[2]))
    if matches:
        print('found P4 chunks candidates:')
        for i, p in enumerate(matches[:10]):
            print(f'  [{i}] {p}')
        return matches[0].parents[2].resolve()

    return Path.cwd().resolve()


def gpu_label() -> str:
    if not torch.cuda.is_available():
        return "CPU"
    name = torch.cuda.get_device_name(0)
    if "L4" in name.upper():
        return "L4"
    if "4060" in name:
        return "RTX4060"
    return "CUDA"

PROJECT_ROOT = detect_project_root()
P4_DIR = PROJECT_ROOT / "outputs" / f"parsing_p4_hwpx_{CORPUS_LIMIT}"
V1_CHUNKS_PATH = P4_DIR / f"chunks_v1_{CORPUS_LIMIT}.jsonl"
V2_CHUNKS_PATH = P4_DIR / f"chunks_v2_{CORPUS_LIMIT}.jsonl"
EVAL_DIR = PROJECT_ROOT / "data" / "eval"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "retrieval_eval_p4_hwpx"
PREDICTION_DIR = OUTPUT_DIR / "predictions"
if LOCAL_CHROMA_ROOT_OVERRIDE:
    CHROMA_DIR = Path(LOCAL_CHROMA_ROOT_OVERRIDE) / f"p4_hwpx_{CORPUS_LIMIT}"
else:
    CHROMA_DIR = OUTPUT_DIR / "chroma"
EXTENDED_EVAL_SCRIPT = PROJECT_ROOT / "notebooks" / "eval" / "evaluation" / "scripts" / "run_retrieval_eval_extended.py"

EMBEDDING_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
EMBEDDING_DEVICE_LABEL = gpu_label()

for path in [OUTPUT_DIR, PREDICTION_DIR, CHROMA_DIR]:
    path.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("EMBEDDING_DEVICE:", EMBEDDING_DEVICE)
print("EMBEDDING_DEVICE_LABEL:", EMBEDDING_DEVICE_LABEL)
print("V1_CHUNKS_PATH exists:", V1_CHUNKS_PATH.exists(), V1_CHUNKS_PATH)
print("V2_CHUNKS_PATH exists:", V2_CHUNKS_PATH.exists(), V2_CHUNKS_PATH)
print("EVAL_DIR exists:", EVAL_DIR.exists(), EVAL_DIR)
print("EXTENDED_EVAL_SCRIPT exists:", EXTENDED_EVAL_SCRIPT.exists(), EXTENDED_EVAL_SCRIPT)
print("CHROMA_DIR local:", CHROMA_DIR)

PROJECT_ROOT: /content/drive/MyDrive/DB_RAG_Codeit_Project
EMBEDDING_DEVICE: cuda
EMBEDDING_DEVICE_LABEL: L4
V1_CHUNKS_PATH exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_250/chunks_v1_250.jsonl
V2_CHUNKS_PATH exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_250/chunks_v2_250.jsonl
EVAL_DIR exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval
EXTENDED_EVAL_SCRIPT exists: True /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py
CHROMA_DIR local: /content/chroma_retrieval_eval_p4_hwpx/p4_hwpx_250

In [ ]:
def file_mib(path: Path) -> float:
    return round(path.stat().st_size / 1024 / 1024, 2) if path.exists() else 0.0

file_check_df = pd.DataFrame([
    {"file": "chunks_v1", "path": str(V1_CHUNKS_PATH), "exists": V1_CHUNKS_PATH.exists(), "mib": file_mib(V1_CHUNKS_PATH)},
    {"file": "chunks_v2", "path": str(V2_CHUNKS_PATH), "exists": V2_CHUNKS_PATH.exists(), "mib": file_mib(V2_CHUNKS_PATH)},
])
display(file_check_df)

if not V1_CHUNKS_PATH.exists() or not V2_CHUNKS_PATH.exists():
    raise FileNotFoundError("P4 HWPX chunks_v1/chunks_v2 files are required before running retrieval quick check.")

,file,path,exists,mib
0,chunks_v1,/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_250/chunks_v1_250.jsonl,True,67.18
1,chunks_v2,/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/parsing_p4_hwpx_250/chunks_v2_250.jsonl,True,86.46

In [ ]:
def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_chunks(path: Path) -> pd.DataFrame:
    df = pd.DataFrame(read_jsonl(path))
    if "content" not in df.columns:
        raise ValueError("chunks JSONL must include content")
    if "embed_enabled" not in df.columns:
        df["embed_enabled"] = True
    if "chunk_type" not in df.columns:
        df["chunk_type"] = "text"
    df = df.copy()
    df["content"] = df["content"].fillna("").astype(str)
    return df


def select_embedding_chunks(df: pd.DataFrame) -> pd.DataFrame:
    selected = df[df["embed_enabled"].fillna(True).astype(bool)].copy()
    selected = selected[selected["chunk_type"].astype(str).ne("toc")].copy()
    selected = selected[selected["content"].str.strip().ne("")].copy()
    selected = selected.drop_duplicates(subset=["chunk_id"]).reset_index(drop=True)
    return selected

chunks_v1_raw = load_chunks(V1_CHUNKS_PATH)
chunks_v2_raw = load_chunks(V2_CHUNKS_PATH)
chunks_v1 = select_embedding_chunks(chunks_v1_raw)
chunks_v2 = select_embedding_chunks(chunks_v2_raw)

summary = pd.DataFrame([
    {"version": "v1", "raw_rows": len(chunks_v1_raw), "selected_rows": len(chunks_v1), "unique_docs": chunks_v1["doc_key"].nunique(), "duplicate_chunk_id": int(chunks_v1["chunk_id"].duplicated().sum()), "chunk_types": dict(chunks_v1_raw["chunk_type"].value_counts())},
    {"version": "v2", "raw_rows": len(chunks_v2_raw), "selected_rows": len(chunks_v2), "unique_docs": chunks_v2["doc_key"].nunique(), "duplicate_chunk_id": int(chunks_v2["chunk_id"].duplicated().sum()), "chunk_types": dict(chunks_v2_raw["chunk_type"].value_counts())},
])
display(summary)
display(chunks_v1[["chunk_id", "source_file", "chunk_type", "content"]].head(2))
display(chunks_v2[["chunk_id", "source_file", "chunk_type", "content"]].head(2))

,version,raw_rows,selected_rows,unique_docs,duplicate_chunk_id,chunk_types
0,v1,26664,26554,250,0,"{'text': 26554, 'toc': 110}"
1,v2,41653,41546,250,0,"{'table': 30154, 'text': 11144, 'fact_candidates': 250, 'toc': 105}"

,chunk_id,source_file,chunk_type,content
0,doc_c6761a6fb2b7_text_text_0001_part_001_9972157211c2,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n-1-\n제 안 요 청 서\n고려대학교\n차세대 포털·학사 정보시스템 구축 사업
1,doc_c6761a6fb2b7_text_text_0002_part_001_468c8342bef7,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,"[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n※ 본 자료는 제안내용의 설명을 위한 배포자료로, 이외 목적으로 무단복제, 전달 및 사용하는 행위를 금함.\n-2-"

,chunk_id,source_file,chunk_type,content
0,doc_c6761a6fb2b7_text_text_0001_part_001_9972157211c2,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n-1-\n제 안 요 청 서\n고려대학교\n차세대 포털·학사 정보시스템 구축 사업
1,doc_c6761a6fb2b7_text_text_0002_part_001_468c8342bef7,고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf,text,"[문서: 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf | 사업명: 차세대 포털·학사 정보시스템 구축사업 | 발주기관: 고려대학교 | 섹션: 문서 시작 | 유형: text]\n※ 본 자료는 제안내용의 설명을 위한 배포자료로, 이외 목적으로 무단복제, 전달 및 사용하는 행위를 금함.\n-2-"

In [ ]:
def parse_list_cell(value) -> list[str]:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return []
    if isinstance(value, list):
        return value
    text = str(value).strip()
    if not text:
        return []
    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return [str(x) for x in parsed]
        return [str(parsed)]
    except Exception:
        if "|" in text:
            return [x.strip() for x in text.split("|") if x.strip()]
        return [text]


def load_eval_questions(eval_dir: Path, canonical_only: bool = True) -> pd.DataFrame:
    if canonical_only:
        csv_paths = [eval_dir / f"eval_batch_{idx:02d}.csv" for idx in range(1, 26)]
        missing = [str(path) for path in csv_paths if not path.exists()]
        if missing:
            raise FileNotFoundError(f"Missing canonical eval CSV files: {missing}")
    else:
        csv_paths = sorted(eval_dir.glob("eval_batch_*.csv"))
        if not csv_paths:
            raise FileNotFoundError(f"No eval CSV files under {eval_dir}")
    frames = []
    for csv_path in csv_paths:
        frame = pd.read_csv(csv_path)
        frame["source_eval_file"] = csv_path.name
        frames.append(frame)
    df = pd.concat(frames, ignore_index=True)
    required = ["id", "type", "difficulty", "question", "ground_truth_answer", "ground_truth_docs"]
    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(f"Missing eval columns: {missing}")
    df["ground_truth_doc_list"] = df["ground_truth_docs"].apply(parse_list_cell)
    df["gt_doc_count"] = df["ground_truth_doc_list"].apply(len)
    return df

eval_df_all = load_eval_questions(EVAL_DIR, canonical_only=True)
if EVAL_SAMPLE_SIZE and EVAL_SAMPLE_SIZE > 0:
    eval_df = eval_df_all.sample(n=min(EVAL_SAMPLE_SIZE, len(eval_df_all)), random_state=EVAL_SAMPLE_SEED).sort_values(["source_eval_file", "id"]).reset_index(drop=True)
else:
    eval_df = eval_df_all.reset_index(drop=True)

print("eval all rows:", len(eval_df_all))
print("eval selected rows:", len(eval_df))
display(eval_df["gt_doc_count"].value_counts().sort_index().rename_axis("gt_doc_count").reset_index(name="rows"))
display(eval_df[["source_eval_file", "id", "question", "gt_doc_count", "ground_truth_doc_list"]].head(5))

eval all rows: 500
eval selected rows: 100

   gt_doc_count  rows
0             1    61
1             2    31
2             3     7
3             4     1

,source_eval_file,id,question,gt_doc_count,ground_truth_doc_list
0,eval_batch_01.csv,Q001,한국가스공사의 '차세대 통합정보시스템(ERP) 구축' 사업 예산 규모는 얼마입니까?,1,[한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp]
1,eval_batch_01.csv,Q003,코이카(KOICA) 전자조달의 '우즈베키스탄 열린 의정활동 상하원 국회 방송시스템 구축 및 지역의회 연계 개선 PMC 용역' 예산 규모는 어떻게 됩니까?,1,[KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp]
2,eval_batch_01.csv,Q010,국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다. 두 기관 중 어느 곳의 예산이 더 많이 배정되었나요?,2,"[국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp, 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp]"
3,eval_batch_01.csv,Q012,나노종합기술원의 스마트 팹 서비스 관련 설비온라인 사업과 부산국제영화제의 BIFF & ACFM 온라인서비스 재개발 사업의 추진 목적 및 예상되는 기대효과를 대비해서 요약해 주세요.,2,"[나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp, (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp]"
4,eval_batch_01.csv,Q016,"그렇다면 1단계와 2단계로 진행되는 이 용수공급사업의 전체 예산 중에서, 약 30%를 올해 기초 조사 및 기반 설계에 사용한다고 가정할 때 해당 금액은 총 얼마입니까?",1,[한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp]

In [ ]:
embedding_model = SentenceTransformer(EMBEDDING_MODEL, device=EMBEDDING_DEVICE)
print("loaded embedding model:", EMBEDDING_MODEL)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/165 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/741 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

loaded embedding model: nlpai-lab/KoE5

In [ ]:
def prefixed_passages(texts: list[str]) -> list[str]:
    return [f"passage: {text}" for text in texts]


def prefixed_queries(texts: list[str]) -> list[str]:
    return [f"query: {text}" for text in texts]


def encode_passages(texts: list[str], batch_size: int = EMBEDDING_BATCH_SIZE) -> np.ndarray:
    return embedding_model.encode(prefixed_passages(texts), batch_size=batch_size, normalize_embeddings=True, show_progress_bar=True, convert_to_numpy=True)


def encode_queries(texts: list[str], batch_size: int = EMBEDDING_BATCH_SIZE) -> np.ndarray:
    return embedding_model.encode(prefixed_queries(texts), batch_size=batch_size, normalize_embeddings=True, show_progress_bar=False, convert_to_numpy=True)


def metadata_value(value):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return ""
    if isinstance(value, (list, tuple, set)):
        return " > ".join(map(str, value))
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def make_chroma_metadata(row: pd.Series) -> dict[str, str]:
    base = {}
    meta = row.get("metadata", {})
    if isinstance(meta, dict):
        base.update(meta)
    source_ref = row.get("source_ref", {})
    if isinstance(source_ref, dict):
        for key in ["source_store_id", "block_id", "part_index", "content_hash"]:
            if key in source_ref:
                base[key] = source_ref.get(key, "")
    for key in ["doc_id", "doc_key", "source_file", "source_format", "chunk_id", "chunk_type", "fact_type", "fact_status", "fact_confidence"]:
        if key in row.index:
            base[key] = row.get(key, "")
    return {key: metadata_value(value) for key, value in base.items()}


def reset_collection(client, collection_name: str):
    if RECREATE_CHROMA_COLLECTIONS:
        try:
            client.delete_collection(collection_name)
            print("deleted existing collection:", collection_name)
        except Exception:
            pass
    return client.get_or_create_collection(name=collection_name, metadata={"hnsw:space": "cosine"})


def build_or_load_collection_streaming(df: pd.DataFrame, collection_name: str):
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    collection = reset_collection(client, collection_name)
    if collection.count() == len(df) and not RECREATE_CHROMA_COLLECTIONS:
        print("reuse existing collection:", collection_name, collection.count())
        return collection
    ids = df["chunk_id"].astype(str).tolist()
    docs = df["content"].astype(str).tolist()
    total = len(ids)
    for start in tqdm(range(0, total, CHROMA_ADD_BATCH_SIZE), desc=f"encode+chroma add {collection_name}"):
        end = min(start + CHROMA_ADD_BATCH_SIZE, total)
        batch_df = df.iloc[start:end]
        batch_docs = docs[start:end]
        batch_embeddings = encode_passages(batch_docs, batch_size=EMBEDDING_BATCH_SIZE)
        batch_metadatas = [make_chroma_metadata(row) for _, row in batch_df.iterrows()]
        collection.add(ids=ids[start:end], documents=batch_docs, embeddings=batch_embeddings.tolist(), metadatas=batch_metadatas)
    print("collection count:", collection_name, collection.count())
    return collection

collection_v1_name = f"rfp_p4_hwpx_{CORPUS_LIMIT}_v1_koe5"
collection_v2_name = f"rfp_p4_hwpx_{CORPUS_LIMIT}_v2_koe5"
collection_v1 = build_or_load_collection_streaming(chunks_v1, collection_v1_name)
collection_v2 = build_or_load_collection_streaming(chunks_v2, collection_v2_name)

encode+chroma add rfp_p4_hwpx_250_v1_koe5:   0%|          | 0/52 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

collection count: rfp_p4_hwpx_250_v1_koe5 26554

encode+chroma add rfp_p4_hwpx_250_v2_koe5:   0%|          | 0/82 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

collection count: rfp_p4_hwpx_250_v2_koe5 41546

In [ ]:
def normalize_doc_name(value: str) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"\.(hwp|hwpx|pdf|json)$", "", text)
    text = re.sub(r"\s+", "", text)
    return text


def result_from_chroma_item(rank: int, doc: str, metadata: dict, distance: float, embedding=None) -> dict[str, Any]:
    score = 1.0 - float(distance) if distance is not None else math.nan
    return {"rank": rank, "filename": metadata.get("source_file", ""), "doc_id": metadata.get("doc_id", ""), "chunk_id": metadata.get("chunk_id", ""), "score": score, "text": doc, "metadata": metadata, "_embedding": embedding}


def dense_candidates(collection, question: str, n_results: int) -> tuple[list[dict[str, Any]], np.ndarray, float]:
    t0 = time.perf_counter()
    q_emb = encode_queries([question])[0]
    res = collection.query(query_embeddings=[q_emb.tolist()], n_results=n_results, include=["documents", "metadatas", "distances"])
    docs = res.get("documents", [[]])[0]
    metadatas = res.get("metadatas", [[]])[0]
    distances = res.get("distances", [[]])[0]
    embs = []
    items = []
    for idx, (doc, meta, dist) in enumerate(zip(docs, metadatas, distances), start=1):
        emb = embs[idx - 1] if len(embs) >= idx else None
        items.append(result_from_chroma_item(idx, doc, meta or {}, dist, emb))
    elapsed_ms = (time.perf_counter() - t0) * 1000
    return items, q_emb, elapsed_ms


def dedupe_by_doc(candidates: list[dict[str, Any]], k: int = FINAL_TOP_K) -> list[dict[str, Any]]:
    selected = []
    seen = set()
    for item in candidates:
        doc_key = normalize_doc_name(item.get("filename") or item.get("doc_id"))
        if not doc_key:
            doc_key = str(item.get("doc_id") or item.get("chunk_id"))
        if doc_key in seen:
            continue
        seen.add(doc_key)
        item = dict(item)
        item["rank"] = len(selected) + 1
        selected.append(item)
        if len(selected) >= k:
            break
    return selected


def bm25_tokenize(text: str) -> list[str]:
    terms = re.findall(r"[가-힣A-Za-z0-9]+", str(text).lower())
    tokens = []
    for term in terms:
        tokens.append(term)
        if re.search(r"[가-힣]", term) and len(term) >= 2:
            tokens.extend(term[i:i+2] for i in range(len(term)-1))
    return tokens


class BM25Index:
    def __init__(self, df: pd.DataFrame):
        self.df = df.reset_index(drop=True)
        tokenized = [bm25_tokenize(text) for text in tqdm(self.df["content"].astype(str).tolist(), desc="bm25 tokenize")]
        self.index = BM25Okapi(tokenized)

    def search(self, question: str, top_k: int) -> list[dict[str, Any]]:
        scores = self.index.get_scores(bm25_tokenize(question))
        order = np.argsort(scores)[::-1][:top_k]
        items = []
        for rank, idx in enumerate(order, start=1):
            row = self.df.iloc[int(idx)]
            items.append({"rank": rank, "filename": row.get("source_file", ""), "doc_id": row.get("doc_id", ""), "chunk_id": row.get("chunk_id", ""), "score": float(scores[idx]), "text": row.get("content", ""), "metadata": make_chroma_metadata(row)})
        return items


def rrf_fuse(result_lists: list[list[dict[str, Any]]], rrf_k: int = RRF_K, top_k: int = FINAL_TOP_K) -> list[dict[str, Any]]:
    by_chunk = {}
    for result_list in result_lists:
        for rank, item in enumerate(result_list, start=1):
            chunk_id = item.get("chunk_id")
            if not chunk_id:
                continue
            if chunk_id not in by_chunk:
                by_chunk[chunk_id] = dict(item)
                by_chunk[chunk_id]["rrf_score"] = 0.0
            by_chunk[chunk_id]["rrf_score"] += 1.0 / (rrf_k + rank)
    fused = sorted(by_chunk.values(), key=lambda item: item.get("rrf_score", 0.0), reverse=True)[:top_k]
    for rank, item in enumerate(fused, start=1):
        item["rank"] = rank
        item["score"] = float(item.get("rrf_score", item.get("score", 0.0)))
    return fused


def clean_contexts_for_json(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    clean = []
    for rank, item in enumerate(items, start=1):
        clean.append({"rank": rank, "filename": item.get("filename", ""), "doc_id": item.get("doc_id", ""), "chunk_id": item.get("chunk_id", ""), "score": float(item.get("score", 0.0)) if item.get("score") is not None else None, "text": item.get("text", ""), "metadata": item.get("metadata", {})})
    return clean


def context_signal_summary(contexts: list[dict[str, Any]]) -> dict[str, Any]:
    clean_contexts = clean_contexts_for_json(contexts)
    unique_docs = {normalize_doc_name(item.get("filename") or item.get("doc_id")) for item in clean_contexts if item.get("filename") or item.get("doc_id")}
    top1_score = clean_contexts[0].get("score") if clean_contexts else None
    return {"top1_score": top1_score, "top5_doc_count": len(unique_docs)}


def infer_retrieval_status(signal: dict[str, Any]) -> tuple[str, str]:
    if signal.get("top5_doc_count", 0) == 0:
        return "insufficient_context", "no_retrieved_context"
    top1_score = signal.get("top1_score")
    if ENABLE_COVERAGE_GATE and top1_score is not None and top1_score < MIN_TOP1_SCORE_FOR_WEAK_SIGNAL:
        return "weak_signal", "top1_score_below_threshold"
    return "sufficient_context", "retrieval_signal_passed"

bm25_v2 = BM25Index(chunks_v2)

bm25 tokenize:   0%|          | 0/41546 [00:00<?, ?it/s]

In [ ]:
reranker = None
if RUN_RERANKER_EXPERIMENTS:
    reranker = CrossEncoder(RERANKER_MODEL, device=EMBEDDING_DEVICE)
    print("loaded reranker:", RERANKER_MODEL)
else:
    print("reranker disabled")


def rerank(question: str, candidates: list[dict[str, Any]], top_k: int = FINAL_TOP_K) -> tuple[list[dict[str, Any]], float]:
    if reranker is None:
        return candidates[:top_k], 0.0
    if not candidates:
        return [], 0.0
    t0 = time.perf_counter()
    pairs = [(question, item.get("text", "")) for item in candidates]
    scores = reranker.predict(pairs, batch_size=RERANK_BATCH_SIZE, show_progress_bar=False)
    reranked = []
    for item, score in zip(candidates, scores):
        updated = dict(item)
        updated["score"] = float(score)
        updated["rerank_score"] = float(score)
        reranked.append(updated)
    reranked = sorted(reranked, key=lambda item: item.get("rerank_score", 0.0), reverse=True)
    elapsed_ms = (time.perf_counter() - t0) * 1000
    for rank, item in enumerate(reranked[:top_k], start=1):
        item["rank"] = rank
    return reranked[:top_k], elapsed_ms

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

loaded reranker: BAAI/bge-reranker-v2-m3

In [ ]:
@dataclass
class RetrievalExperiment:
    experiment_id: str
    corpus_name: str
    corpus_version: str
    retrieval_method: str
    collection: Any
    chunks_df: pd.DataFrame
    bm25: Any = None
    collection_name: str = ""
    dense_top_k: int = DENSE_TOP_K
    bm25_top_k: int = 0
    fetch_k: int = FINAL_TOP_K
    rrf_k: int = RRF_K
    reranker_model: str = ""
    rerank_top_k: int = 0
    final_top_k: int = FINAL_TOP_K
    use_hybrid: bool = False
    use_reranker: bool = False

experiments = [
    RetrievalExperiment(f"R0_p4_hwpx_{CORPUS_LIMIT}_v1_dense_top5", CORPUS_NAME, CORPUS_VERSION_V1, "dense", collection_v1, chunks_v1, collection_name=collection_v1_name, dense_top_k=FINAL_TOP_K, fetch_k=FINAL_TOP_K),
    RetrievalExperiment(f"R1_p4_hwpx_{CORPUS_LIMIT}_v2_dense_rerank_top5", CORPUS_NAME, CORPUS_VERSION_V2, "dense_rerank", collection_v2, chunks_v2, bm25=bm25_v2, collection_name=collection_v2_name, dense_top_k=DENSE_TOP_K, fetch_k=DENSE_TOP_K, use_reranker=True, reranker_model=RERANKER_MODEL, rerank_top_k=FINAL_TOP_K),
    RetrievalExperiment(f"R2_p4_hwpx_{CORPUS_LIMIT}_v2_hybrid_rrf_rerank_top5", CORPUS_NAME, CORPUS_VERSION_V2, "hybrid_rrf_rerank", collection_v2, chunks_v2, bm25=bm25_v2, collection_name=collection_v2_name, dense_top_k=DENSE_TOP_K, bm25_top_k=BM25_TOP_K, fetch_k=DENSE_TOP_K, use_hybrid=True, use_reranker=True, reranker_model=RERANKER_MODEL, rerank_top_k=FINAL_TOP_K),
]
if not RUN_RERANKER_EXPERIMENTS:
    experiments = [exp for exp in experiments if not exp.use_reranker]

pd.DataFrame([{"experiment_id": exp.experiment_id, "corpus_version": exp.corpus_version, "retrieval_method": exp.retrieval_method, "collection": exp.collection_name, "chunks": len(exp.chunks_df), "dense_top_k": exp.dense_top_k, "bm25_top_k": exp.bm25_top_k, "reranker": exp.use_reranker} for exp in experiments])

,experiment_id,corpus_version,retrieval_method,collection,chunks,dense_top_k,bm25_top_k,reranker
0,R0_p4_hwpx_250_v1_dense_top5,v1_clean_text,dense,rfp_p4_hwpx_250_v1_koe5,26554,5,0,False
1,R1_p4_hwpx_250_v2_dense_rerank_top5,v2_hwpx_table_aware,dense_rerank,rfp_p4_hwpx_250_v2_koe5,41546,30,0,True
2,R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5,v2_hwpx_table_aware,hybrid_rrf_rerank,rfp_p4_hwpx_250_v2_koe5,41546,30,30,True

In [ ]:
def retrieve_one(question: str, exp: RetrievalExperiment) -> tuple[list[dict[str, Any]], float, float, float]:
    retrieval_start = time.perf_counter()
    rerank_ms = 0.0
    dense_items, q_emb, dense_ms = dense_candidates(exp.collection, question, n_results=exp.fetch_k)
    if exp.use_hybrid:
        bm25_items = exp.bm25.search(question, top_k=exp.bm25_top_k) if exp.bm25 is not None else []
        rrf_top_k = exp.fetch_k if exp.use_reranker else exp.final_top_k
        candidates = rrf_fuse([dense_items, bm25_items], rrf_k=exp.rrf_k, top_k=rrf_top_k)
    else:
        candidates = dense_items[:exp.fetch_k]
    if exp.use_reranker:
        candidates, rerank_ms = rerank(question, candidates, top_k=exp.final_top_k)
    final_contexts = dedupe_by_doc(candidates, k=exp.final_top_k)
    total_ms = (time.perf_counter() - retrieval_start) * 1000
    retrieval_ms = total_ms - rerank_ms
    return final_contexts, retrieval_ms, rerank_ms, total_ms


def retriever_config(exp: RetrievalExperiment) -> dict[str, Any]:
    return {
        "experiment_id": exp.experiment_id, "corpus_name": exp.corpus_name, "corpus_version": exp.corpus_version, "corpus_coverage": CORPUS_COVERAGE,
        "embedding_model": EMBEDDING_MODEL, "embedding_device": EMBEDDING_DEVICE_LABEL, "vector_db": "chroma", "collection_name": exp.collection_name,
        "retrieval_method": exp.retrieval_method, "retriever_type": exp.retrieval_method, "dense_top_k": exp.dense_top_k, "bm25_top_k": exp.bm25_top_k,
        "fetch_k": exp.fetch_k, "rrf_k": exp.rrf_k if exp.use_hybrid else "", "reranker": bool(exp.use_reranker), "reranker_model": exp.reranker_model,
        "rerank_top_k": exp.rerank_top_k, "final_top_k": exp.final_top_k, "chunk_size": CHUNK_SIZE, "chunk_overlap": CHUNK_OVERLAP,
        "toc_policy": "excluded_from_embedding", "metadata_boost": False, "doc_dedup": True, "coverage_gate_enabled": ENABLE_COVERAGE_GATE,
        "min_top1_score_for_weak_signal": MIN_TOP1_SCORE_FOR_WEAK_SIGNAL, "unverified_answer": UNVERIFIED_ANSWER,
        "eval_sample_size": EVAL_SAMPLE_SIZE, "eval_sample_seed": EVAL_SAMPLE_SEED, "save_embedding_cache": SAVE_EMBEDDING_CACHE,
    }


def write_predictions(exp: RetrievalExperiment, eval_df: pd.DataFrame) -> Path:
    pred_path = PREDICTION_DIR / f"{exp.experiment_id}_predictions.jsonl"
    config = retriever_config(exp)
    with pred_path.open("w", encoding="utf-8") as f:
        for _, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc=exp.experiment_id):
            contexts, retrieval_ms, rerank_ms, total_ms = retrieve_one(row["question"], exp)
            signal = context_signal_summary(contexts)
            retrieval_status, coverage_reason = infer_retrieval_status(signal)
            record = {"id": row["id"], "source_eval_file": row.get("source_eval_file", ""), "question": row["question"], "answer": "", "retrieved_contexts": clean_contexts_for_json(contexts), "corpus_coverage": CORPUS_COVERAGE, "retrieval_status": retrieval_status, "coverage_reason": coverage_reason, "top1_score": signal["top1_score"], "top5_doc_count": signal["top5_doc_count"], "latency_ms": total_ms, "retrieval_ms": retrieval_ms, "rerank_ms": rerank_ms, "model_name": "retrieval_only", "embedding_model": EMBEDDING_MODEL, "retriever_config": config}
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    return pred_path

prediction_paths = []
for exp in experiments:
    path = write_predictions(exp, eval_df)
    prediction_paths.append((exp, path))
    print(exp.experiment_id, path)

R0_p4_hwpx_250_v1_dense_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R0_p4_hwpx_250_v1_dense_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_250_v1_dense_top5_predictions.jsonl

R1_p4_hwpx_250_v2_dense_rerank_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R1_p4_hwpx_250_v2_dense_rerank_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_250_v2_dense_rerank_top5_predictions.jsonl

R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5:   0%|          | 0/100 [00:00<?, ?it/s]

R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5_predictions.jsonl

In [ ]:
def run_extended_eval(exp: RetrievalExperiment, pred_path: Path):
    if not EXTENDED_EVAL_SCRIPT.exists():
        raise FileNotFoundError(EXTENDED_EVAL_SCRIPT)
    cmd = [sys.executable, str(EXTENDED_EVAL_SCRIPT), "--project-root", str(PROJECT_ROOT), "--eval-dir", str(EVAL_DIR), "--predictions", str(pred_path), "--output-dir", str(OUTPUT_DIR), "--prediction-ids-only", "--top-k", str(exp.final_top_k), "--experiment-id", exp.experiment_id, "--experiment-name", exp.retrieval_method, "--eval-scope", "sample" if EVAL_SAMPLE_SIZE else "canonical_01_25", "--notes", f"P4 HWPX quickcheck; corpus={exp.corpus_name}/{exp.corpus_version}; eval_batch_01_25; sample_size={EVAL_SAMPLE_SIZE}"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(" ".join(cmd))
    print(result.stdout[-2500:])
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(f"extended eval failed: {exp.experiment_id}")

for exp, pred_path in prediction_paths:
    run_extended_eval(exp, pred_path)

summary_log = OUTPUT_DIR / "experiment_logs" / "retrieval_experiments.csv"
summary_df = pd.read_csv(summary_log)
current = summary_df[summary_df["experiment_id"].isin([exp.experiment_id for exp in experiments])].tail(len(experiments))
metric_cols = ["experiment_id", "num_eval_questions", "hit_at_5_any", "mrr_at_5", "ndcg_at_5", "doc_recall_at_5", "single_doc_mrr_at_5", "multi_doc_ndcg_at_5", "retrieval_ms_p95", "rerank_ms_avg", "total_retrieval_ms_avg"]
display(current[metric_cols])

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_250_v1_dense_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R0_p4_hwpx_250_v1_dense_top5 --experiment-name dense --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_250/v1_clean_text; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R0_p4_hwpx_250_v1_dense_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R0_p4_hwpx_250_v1_dense_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R0_p4_hwpx_250_v1_dense_top5",
  "experiment_name": "dense",
  "run_datetime": "2026-05-19T09:49:34",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_250/v1_clean_text; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R0_p4_hwpx_250_v1_dense_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 99,
  "num_weak_signal": 1,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_250",
  "corpus_version": "v1_clean_text",
  "corpus_coverage": "p4_hwpx_pilot_250_same_as_p3_sample",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_250_v1_koe5",
  "retrieval_method": "dense",
  "dense_top_k": 5,
  "bm25_top_k": 0,
  "fetch_k": 5,
  "rrf_k": "",
  "reranker": false,
  "reranker_model": "",
  "rerank_top_k": 0,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.92,
  "all_gold_docs_hit_at_5": 0.71,
  "mrr_at_5": 0.8553333333333333,
  "ndcg_at_5": 0.7863702338521433,
  "doc_recall_at_5": 0.8091666666666666,
  "single_doc_mrr_at_5": 0.8256830601092895,
  "multi_doc_ndcg_at_5": 0.7022773708162311,
  "multi_doc_recall_at_5": 0.6901709401709402,
  "retrieval_ms_avg": 26.429942719987594,
  "retrieval_ms_p95": 28.142880949985738,
  "rerank_ms_avg": 0.0,
  "total_retrieval_ms_avg": 26.429942719987594
}

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_250_v2_dense_rerank_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R1_p4_hwpx_250_v2_dense_rerank_top5 --experiment-name dense_rerank --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_250/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R1_p4_hwpx_250_v2_dense_rerank_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R1_p4_hwpx_250_v2_dense_rerank_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R1_p4_hwpx_250_v2_dense_rerank_top5",
  "experiment_name": "dense_rerank",
  "run_datetime": "2026-05-19T09:49:35",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_250/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R1_p4_hwpx_250_v2_dense_rerank_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 94,
  "num_weak_signal": 6,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_250",
  "corpus_version": "v2_hwpx_table_aware",
  "corpus_coverage": "p4_hwpx_pilot_250_same_as_p3_sample",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_250_v2_koe5",
  "retrieval_method": "dense_rerank",
  "dense_top_k": 30,
  "bm25_top_k": 0,
  "fetch_k": 30,
  "rrf_k": "",
  "reranker": true,
  "reranker_model": "BAAI/bge-reranker-v2-m3",
  "rerank_top_k": 5,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.98,
  "all_gold_docs_hit_at_5": 0.77,
  "mrr_at_5": 0.9733333333333333,
  "ndcg_at_5": 0.8890336070885754,
  "doc_recall_at_5": 0.8708333333333332,
  "single_doc_mrr_at_5": 0.9562841530054644,
  "multi_doc_ndcg_at_5": 0.7795733515091677,
  "multi_doc_recall_at_5": 0.7200854700854701,
  "retrieval_ms_avg": 31.48031498995806,
  "retrieval_ms_p95": 34.1212898999629,
  "rerank_ms_avg": 1651.3506451300236,
  "total_retrieval_ms_avg": 1682.8309601199817
}

/usr/bin/python3 /content/drive/MyDrive/DB_RAG_Codeit_Project/notebooks/eval/evaluation/scripts/run_retrieval_eval_extended.py --project-root /content/drive/MyDrive/DB_RAG_Codeit_Project --eval-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/data/eval --predictions /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5_predictions.jsonl --output-dir /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx --prediction-ids-only --top-k 5 --experiment-id R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 --experiment-name hybrid_rrf_rerank --eval-scope sample --notes P4 HWPX quickcheck; corpus=p4_hwpx_250/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100
eval_results: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5_eval_results_extended.csv
summary: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5_summary_extended.json
summary_log: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/experiment_logs/retrieval_experiments.csv
{
  "experiment_id": "R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5",
  "experiment_name": "hybrid_rrf_rerank",
  "run_datetime": "2026-05-19T09:49:36",
  "notes": "P4 HWPX quickcheck; corpus=p4_hwpx_250/v2_hwpx_table_aware; eval_batch_01_25; sample_size=100",
  "predictions_path": "/content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/predictions/R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5_predictions.jsonl",
  "eval_scope": "sample",
  "num_eval_questions": 100,
  "num_scored_questions": 100,
  "num_single_doc_questions": 61,
  "num_multi_doc_questions": 39,
  "num_sufficient_context": 94,
  "num_weak_signal": 6,
  "num_insufficient_context": 0,
  "corpus_name": "p4_hwpx_250",
  "corpus_version": "v2_hwpx_table_aware",
  "corpus_coverage": "p4_hwpx_pilot_250_same_as_p3_sample",
  "embedding_model": "nlpai-lab/KoE5",
  "embedding_device": "L4",
  "vector_db": "chroma",
  "collection_name": "rfp_p4_hwpx_250_v2_koe5",
  "retrieval_method": "hybrid_rrf_rerank",
  "dense_top_k": 30,
  "bm25_top_k": 30,
  "fetch_k": 30,
  "rrf_k": 60,
  "reranker": true,
  "reranker_model": "BAAI/bge-reranker-v2-m3",
  "rerank_top_k": 5,
  "final_top_k": 5,
  "chunk_size": 1000,
  "chunk_overlap": 150,
  "toc_policy": "excluded_from_embedding",
  "metadata_boost": false,
  "doc_dedup": true,
  "hit_at_5_any": 0.99,
  "all_gold_docs_hit_at_5": 0.78,
  "mrr_at_5": 0.9775,
  "ndcg_at_5": 0.9033212897131924,
  "doc_recall_at_5": 0.8891666666666665,
  "single_doc_mrr_at_5": 0.9631147540983607,
  "multi_doc_ndcg_at_5": 0.8018082733249842,
  "multi_doc_recall_at_5": 0.7414529914529914,
  "retrieval_ms_avg": 1492.2875167200482,
  "retrieval_ms_p95": 2654.5805117505097,
  "rerank_ms_avg": 1629.5872413199777,
  "total_retrieval_ms_avg": 3121.874758040026
}

,experiment_id,num_eval_questions,hit_at_5_any,mrr_at_5,ndcg_at_5,doc_recall_at_5,single_doc_mrr_at_5,multi_doc_ndcg_at_5,retrieval_ms_p95,rerank_ms_avg,total_retrieval_ms_avg
0,R0_p4_hwpx_250_v1_dense_top5,100,0.92,0.855333,0.786370,0.809167,0.825683,0.702277,28.142881,0.000000,26.429943
1,R1_p4_hwpx_250_v2_dense_rerank_top5,100,0.98,0.973333,0.889034,0.870833,0.956284,0.779573,34.121290,1651.350645,1682.830960
2,R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5,100,0.99,0.977500,0.903321,0.889167,0.963115,0.801808,2654.580512,1629.587241,3121.874758

In [ ]:
# ===== Qualitative preview: 5 questions x R0/R1/R2 =====
PREVIEW_N_QUESTIONS = 5
MAX_TEXT_CHARS = 500

pred_cache = {}
for exp, pred_path in prediction_paths:
    with pred_path.open("r", encoding="utf-8") as f:
        pred_cache[exp.experiment_id] = [json.loads(line) for line in f if line.strip()]
selected_keys = []
for row in pred_cache[experiments[0].experiment_id][:PREVIEW_N_QUESTIONS]:
    selected_keys.append((row.get("source_eval_file", ""), str(row.get("id", ""))))
for source_eval_file, qid in selected_keys:
    base_row = next((r for r in pred_cache[experiments[0].experiment_id] if r.get("source_eval_file", "") == source_eval_file and str(r.get("id", "")) == qid), None)
    if not base_row:
        continue
    print("\n" + "=" * 100)
    print(f"[{source_eval_file} / {qid}] {base_row.get('question')}")
    gt = eval_df[(eval_df["source_eval_file"].astype(str) == source_eval_file) & (eval_df["id"].astype(str) == qid)]
    if not gt.empty:
        print("GT docs:", gt.iloc[0].get("ground_truth_doc_list"))
    for exp in experiments:
        rows = [r for r in pred_cache[exp.experiment_id] if r.get("source_eval_file", "") == source_eval_file and str(r.get("id", "")) == qid]
        if not rows:
            continue
        rec = rows[0]
        print("\n---", exp.experiment_id, "---")
        for ctx in rec.get("retrieved_contexts", [])[:FINAL_TOP_K]:
            text = str(ctx.get("text", "")).replace("\n", " ")
            if len(text) > MAX_TEXT_CHARS:
                text = text[:MAX_TEXT_CHARS].rstrip() + " ..."
            print(f"#{ctx.get('rank')} score={ctx.get('score'):.4f} file={ctx.get('filename')} chunk={ctx.get('chunk_id')}")
            print(text)

====================================================================================================
[eval_batch_01.csv / Q001] 한국가스공사의 '차세대 통합정보시스템(ERP) 구축' 사업 예산 규모는 얼마입니까?
GT docs: ['한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp']

--- R0_p4_hwpx_250_v1_dense_top5 ---
#1 score=0.7065 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_35ceab976987
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 [표 | 섹션: Ⅲ. 일반사항 | rows: 1 | cols: 3] 컬럼: Ⅰ | col_2 | 개요 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐 ...

--- R1_p4_hwpx_250_v2_dense_rerank_top5 ---
#1 score=0.9116 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_48fffb407f32
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐색‧활용 간소화로 사용자 편의 및 데이터 기반의 업무환경 마련 * KOGAS 디지털 전환 전략 수립 설 ...

--- R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9116 file=한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp chunk=doc_f1c6cddebe51_text_text_0004_part_001_48fffb407f32
[문서: 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp | 사업명: [재공고]차세대 통합정보시스템(ERP) 구축 | 발주기관: 한국가스공사 | 섹션: Ⅲ. 일반사항 | 유형: text] Ⅲ. 일반사항 1. 사 업 명 : 차세대 통합정보시스템(ERP) 구축 2. 사업목적 ○ 기술지원 종료(‘27년)에 대비한 ERP 업그레이드 - 제조사(SAP社)의 기술지원 종료 이후 세법 개정, 보안취약점 발생시 원활한 대응이 불가 등 기술지원 종료 대비한 선제적 대응으로 안정적 서비스 제공 ○ 정보시스템 복잡도 해소 및 접근‧활용 간소화로 업무생산성 향상 - ‘09년 도입 이후 종합적인 개선 없이 단편적 수정으로 복잡도 증가 및 대사·검증 등 수작업에 따른 비효율 해소 * 원가결산, 급여정산 등 검증을 위한 수작업 및 대용량 데이터 처리시 속도지연 발생 - 시스템 접근, 데이터 탐색‧활용 간소화로 사용자 편의 및 데이터 기반의 업무환경 마련 * KOGAS 디지털 전환 전략 수립 설 ...

====================================================================================================
[eval_batch_01.csv / Q003] 코이카(KOICA) 전자조달의 '우즈베키스탄 열린 의정활동 상하원 국회 방송시스템 구축 및 지역의회 연계 개선 PMC 용역' 예산 규모는 어떻게 됩니까?
GT docs: ['KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp']

--- R0_p4_hwpx_250_v1_dense_top5 ---
#1 score=0.7420 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0002_part_003_1999c2e64aef
위한 정보시스템 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 열린 의정활동을 위한 상하원 국회 방송시스템 구축 및 지역의회와의 연계 기반 개선사업 PMC 용역 ㅇ (영문명) PMC Service for the System for the Project on Increasing the Openness of the Senate and LCOM in Uzbekistan through the Implementation of Parliament Broadcasting System and Improvement of Connection with Regional and Local Councils 나. 용역기간 : 계약체결일로부터 2027년 9월 30일까지 다. 대 상 지 : 우즈베키스탄 타슈켄트시, 12개 주(州) 및 카라칼팍스탄 공화국
#2 score=0.6447 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp chunk=doc_bf8e796b625c_text_text_0004_part_001_7181a9affcb0
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] 약어: WAS | 영어 표기: Web Application Server | 한글 명칭: 웹 어플리케이션 서버 약어: WEB | 영어 표기: World Wide Web | 한글 명칭: 월드와이드웹(인터넷) 약어: WUA | 영어 표기: Water User Association | 한글 명칭: 물 사용자 협의체 약어: XML | 영어 표기: eXtensible Markup Language | 한글 명칭: W3C에서 개발된 이기종 데이터 연동 마크업 언어 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 ...

--- R1_p4_hwpx_250_v2_dense_rerank_top5 ---
#1 score=0.9997 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0003_part_001_9fa9ea7f65e7
[문서: KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp | 사업명: [긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] - 2025년: 3,189,242,057원($2,453,263/1$=1,300원, 2024년 기준환율) - 2026년: 1,784,664,718원($1,372,819/1$=1,300원, 2024년 기준환율) ※ 부가가치세 등 제반 비용 포함하는 사업임. 마. 용역범위 ㅇ 국회 방송시스템 및 지역의회간 연계 기반 구축을 위한 기자재 조달업체 선정 및 운영지원 ㅇ 대국민 국회방송을 위한 응용시스템 개발 ㅇ 시스템 구축을 위한 기반 설비 구축(수원기관 분담) 지원 ㅇ 국회 구성원에 대한 역량강화 ㅇ 사업관리 및 성과관리 2. 기본방향 가. 사업목표 ㅇ (장기) 우즈베키스탄 국회의 투명성 강화 및 참여 민주주의 구현 ㅇ (중기) 우즈베키스탄 국회 ...
#2 score=0.9057 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp chunk=doc_bf8e796b625c_table_table_0001_part_001_ae9cafc976da
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 2 | cols: 1] 컬럼: col_1 그룹: 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 수립 및 시설기반강화 시범사업 사후관리 PMC 용역 / (2023-2024/64만불) 그룹: 제안요청서

--- R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9997 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp chunk=doc_afba17272e87_text_text_0003_part_001_9fa9ea7f65e7
[문서: KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp | 사업명: [긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] - 2025년: 3,189,242,057원($2,453,263/1$=1,300원, 2024년 기준환율) - 2026년: 1,784,664,718원($1,372,819/1$=1,300원, 2024년 기준환율) ※ 부가가치세 등 제반 비용 포함하는 사업임. 마. 용역범위 ㅇ 국회 방송시스템 및 지역의회간 연계 기반 구축을 위한 기자재 조달업체 선정 및 운영지원 ㅇ 대국민 국회방송을 위한 응용시스템 개발 ㅇ 시스템 구축을 위한 기반 설비 구축(수원기관 분담) 지원 ㅇ 국회 구성원에 대한 역량강화 ㅇ 사업관리 및 성과관리 2. 기본방향 가. 사업목표 ㅇ (장기) 우즈베키스탄 국회의 투명성 강화 및 참여 민주주의 구현 ㅇ (중기) 우즈베키스탄 국회 ...

====================================================================================================
[eval_batch_01.csv / Q010] 국립중앙의료원의 차세대 응급의료 상황관리시스템 사업과 한국원자력연구원의 선량평가시스템 고도화 사업 모두 시스템 고도화 및 구축을 목적으로 합니다. 두 기관 중 어느 곳의 예산이 더 많이 배정되었나요?
GT docs: ['국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp', '한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp']

--- R0_p4_hwpx_250_v1_dense_top5 ---
#1 score=0.6247 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_caa26f6adb1a
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 [표 | 섹션: Ⅰ. 사업 개요 | rows: 1 | cols: 4] 컬럼: 1 | col_2 | 사업 안내 | col_4 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 [표 | 섹션: Ⅰ. 사업 개요 | rows: 1 | cols: 4] 컬럼: 2 | col_2 | 추진배경 및 필요성 | col_4 가. 응급의료는 국민의 생명과 직결되는 대표적인 필 ...

--- R1_p4_hwpx_250_v2_dense_rerank_top5 ---
#1 score=0.6838 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_a0203e4c12a5
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 가. 응급의료는 국민의 생명과 직결되는 대표적인 필수의료 분야이나 최근 응급실 뺑뺑이 사건 등 병원 전 단계에서 치료 가능한 응급실 섭외 지연 문제 발생 나. 병원간 이송(이하 “전원”)이 현 응급의료에서 가장 취약한 영역 - 응급실로 내원 중증환자(KTAS 1,2)의 13.5%(‘22년 기준)가 전원을 ...

--- R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.6838 file=국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp chunk=doc_a43e5952d388_text_text_0002_part_001_a0203e4c12a5
[문서: 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp | 사업명: (긴급)「2024년도 차세대 응급의료 상황관리시스템 구축 | 발주기관: 국립중앙의료원 | 섹션: Ⅰ. 사업 개요 | 유형: text] Ⅰ. 사업 개요 가. 사 업 명 : 2024년도 차세대 응급의료 상황관리시스템 구축 나. 사업기간 : 계약일로부터 2024년 12월 31일까지 다. 사업예산 : 금일십사억원정 (￦1,400,000,000원, VAT포함) 라. 예산코드 : 29. 중앙응급의료센터 운영지원-관리운영비-외주용역비-광역상황실 마. 추진방법 : 제한경쟁입찰 / 협상에 의한 계약 가. 응급의료는 국민의 생명과 직결되는 대표적인 필수의료 분야이나 최근 응급실 뺑뺑이 사건 등 병원 전 단계에서 치료 가능한 응급실 섭외 지연 문제 발생 나. 병원간 이송(이하 “전원”)이 현 응급의료에서 가장 취약한 영역 - 응급실로 내원 중증환자(KTAS 1,2)의 13.5%(‘22년 기준)가 전원을 ...

====================================================================================================
[eval_batch_01.csv / Q012] 나노종합기술원의 스마트 팹 서비스 관련 설비온라인 사업과 부산국제영화제의 BIFF & ACFM 온라인서비스 재개발 사업의 추진 목적 및 예상되는 기대효과를 대비해서 요약해 주세요.
GT docs: ['나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp', '(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp']

--- R0_p4_hwpx_250_v1_dense_top5 ---
#1 score=0.6013 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0002_part_001_674f23b54cb6
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] ○ 행사 지원시스템에 대하여, 행사 진행 공간의 유동성을 위해 요청에 따라 모바일 웹 또는 앱 형태로 제공하여 휴대성과 편의성을 제고한다. ○ 영화제 임박기간 전문 인력을 파견하여, 생성되는 각종 콘텐츠와 페이지 제작 업무를 진행하며, 발생하는 다양한 변수를 신속하고 안정적으로 해결한다. ○ 개발 및 제공하는 모든 사이트의 사용자 수, 이벤트 수, 페이지뷰 수 등의 접속 통계 자료를 제공한다. ○ 각종 웹사이트와 시스템 기획 및 개발, 디자인 요청 등의 다양한 전산요청을 위해 상태 체크(전체, 접수, 진행, 완료) 및 파일 첨부가 가능한 온라인 헬프데스크를 공급, 운영하여 부서별 발생하는 요청사항을 빠르고 효과적으로 처리한다. 3 ...
#2 score=0.5686 file=나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp chunk=doc_7ce4da44d9e9_text_text_0003_part_003_d1f05205c2d8
신뢰성 및 양산 적합성 검증·인정 등 제 [표 | 섹션: 문서 시작 | rows: 1 | cols: 1] 컬럼: col_1 그룹: 출처 : 제5기 나노기술종합발전계획 [ 나노융합 현장수요기반 실증지원 ] [표 | 섹션: 문서 시작 | rows: 3 | cols: 1] 컬럼: col_1 그룹: 2 그룹: 사업 추진계획 2.1. 추진목표 [표 | 섹션: 문서 시작 | rows: 1 | cols: 1] 컬럼: col_1 col_1: ○ 기술원 FAB 스마트 팹 서비스 활용체계 구축관련 설비 온라인 시스템 구축 용역으로 설비 데이터 수집체계 마련 및 LoT Tracking 구현을 통해 Lot 관리의 정보화 수준 향상

--- R1_p4_hwpx_250_v2_dense_rerank_top5 ---
#1 score=0.9478 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0001_part_001_46acae61579e
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] 2024. 6. 1. 사업개요 가. 사 업 명 : BIFF&ACFM 온라인서비스 재개발 및 행사지원시스템 공급 사업 나. 기 간 : 계약체결일 ~ 2025. 05. 31. 다. 사업예산 : 금243,000,000원(금이억사천삼백만 원) (VAT 포함) 라. 입찰방식 : 제한 경쟁입찰(지역 제한) 마. 계약방법 : 협상에 의한 계약 2. 사업목표 ○ 웹 표준, 웹 접근성 및 웹 UI에 대한 기능개선으로 사용자 중심의 웹서비스를 제공한다. ○ BIFF, ACFM에서 운영 중인 웹사이트에 대하여, 당해 연도의 독창적인 디자인 UI 적용, 최신 트렌트를 반영하여 브랜드 가치 제고. ○ BIFF, ACFM 각종 접수 및 참가 시스템을 당해 ...

--- R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.9478 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp chunk=doc_59211e6008a9_text_text_0001_part_001_46acae61579e
[문서: (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp | 사업명: 2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시 | 발주기관: (사)부산국제영화제 | 섹션: 문서 시작 | 유형: text] 2024. 6. 1. 사업개요 가. 사 업 명 : BIFF&ACFM 온라인서비스 재개발 및 행사지원시스템 공급 사업 나. 기 간 : 계약체결일 ~ 2025. 05. 31. 다. 사업예산 : 금243,000,000원(금이억사천삼백만 원) (VAT 포함) 라. 입찰방식 : 제한 경쟁입찰(지역 제한) 마. 계약방법 : 협상에 의한 계약 2. 사업목표 ○ 웹 표준, 웹 접근성 및 웹 UI에 대한 기능개선으로 사용자 중심의 웹서비스를 제공한다. ○ BIFF, ACFM에서 운영 중인 웹사이트에 대하여, 당해 연도의 독창적인 디자인 UI 적용, 최신 트렌트를 반영하여 브랜드 가치 제고. ○ BIFF, ACFM 각종 접수 및 참가 시스템을 당해 ...

====================================================================================================
[eval_batch_01.csv / Q016] 그렇다면 1단계와 2단계로 진행되는 이 용수공급사업의 전체 예산 중에서, 약 30%를 올해 기초 조사 및 기반 설계에 사용한다고 가정할 때 해당 금액은 총 얼마입니까?
GT docs: ['한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp']

--- R0_p4_hwpx_250_v1_dense_top5 ---
#1 score=0.5346 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_text_text_0023_part_001_63ec5dd86128
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: text] (4) 기본계획(안) 수립 ① 계약상대자는 동 과업과 관련된 관계 법령에서 정하는 기본계획 작성을 위한 기초 조사를 수행하여 기본계획 협의자료 및 협의에 필요한 각종 인․허가 자료를 감독원과 사전 협의하여 작성․제출하여야 하며, 용인 첨단 시스템반도체 국가산단 용수공급사업 추진관련 된 타 조사 및 용역의 검토 내용을 충실히 반영하여 종합적인 검토가 될 수 있도록 하여야 한다. ② 기본계획 작성 시는 관련규정에 의거 시행하여야 하는 제반 검토 사항에 대하여 감독원과 협의하여 검토 반영하고 관련기관 및 지역주민 등과의 협의과정에서 제시된 사항에 대하여도 추가 검토하여 반영하여야 하며, 다음 각 호의 사항은 반드시 포함되어야 한다. 가. 사업의 목표 및 기본 방향 나. 사업 ...

--- R1_p4_hwpx_250_v2_dense_rerank_top5 ---
#1 score=0.2690 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_table_table_0004_part_001_de2e2d9e8830
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 6 | cols: 6] 컬럼: 구 분 | col_2 | 전 체 | 1단계 | 2단계 | 비 고 구 분: 공 급 량 | 전 체: 80만㎥/일 | 1단계: 20만㎥/일 | 2단계: 60만㎥/일 | 비 고: - 구 분: 사업기간 | 전 체: ’24년~`34년 | 1단계: ’24년~’30년 | 2단계: ’24년~`34년 구 분: 시설 | col_2: 취수장 | 전 체: 취수장 1개소 | 1단계: - | 2단계: 취수장 1개소 col_2: 가압장 | 전 체: 가압장 4개소 | 1단계: 가압장 2개소 | 2단계: 가압장 2개소 col_2: 관 로 | 전 체: D1,500mm, L=34.5km / / D2,200mm, L=48.4km | ...

--- R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5 ---
#1 score=0.2690 file=한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp chunk=doc_6a4eb959610e_table_table_0004_part_001_de2e2d9e8830
[문서: 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp | 사업명: 용인 첨단 시스템반도체 국가산단 용수공급사업 타당성 | 발주기관: 한국수자원공사 | 섹션: 문서 시작 | 유형: table] [표 | 섹션: 문서 시작 | rows: 6 | cols: 6] 컬럼: 구 분 | col_2 | 전 체 | 1단계 | 2단계 | 비 고 구 분: 공 급 량 | 전 체: 80만㎥/일 | 1단계: 20만㎥/일 | 2단계: 60만㎥/일 | 비 고: - 구 분: 사업기간 | 전 체: ’24년~`34년 | 1단계: ’24년~’30년 | 2단계: ’24년~`34년 구 분: 시설 | col_2: 취수장 | 전 체: 취수장 1개소 | 1단계: - | 2단계: 취수장 1개소 col_2: 가압장 | 전 체: 가압장 4개소 | 1단계: 가압장 2개소 | 2단계: 가압장 2개소 col_2: 관 로 | 전 체: D1,500mm, L=34.5km / / D2,200mm, L=48.4km | ...

## 해석 기준

- `R0`: 구조화하지 않은 clean text baseline입니다. v2가 의미 있는지 비교하는 기준선입니다.
- `R1`: dense 검색 결과 30개를 reranker로 재정렬합니다. 이전 실험의 R4 조건입니다.
- `R2`: dense + BM25를 RRF로 합친 뒤 reranker를 적용합니다. 이전 실험의 R6 조건입니다.
- eval은 기본 100개 sample입니다. 전체 500문항을 보려면 `EVAL_SAMPLE_SIZE = 0`으로 바꿔서 다시 실행하면 됩니다.

## Failure Analysis

? DataFrame? ??? ??? ??, `summary ? compact case list ? CASE_ID ?? ??` ??? ?????. ?? ?? ??? CSV? ?????.

In [ ]:
# ===== Failure Analysis: build data and compact summaries =====
from pathlib import Path
import json
import re
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 12)
pd.set_option("display.max_colwidth", 70)
pd.set_option("display.width", 140)


def _normalize_doc_name_for_analysis(value: str) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"\.(hwp|hwpx|pdf|json)$", "", text)
    text = re.sub(r"\s+", "", text)
    return text


def _load_prediction_jsonl(path: Path) -> pd.DataFrame:
    rows = []
    with Path(path).open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return pd.DataFrame(rows)


def _safe_contexts(value):
    return value if isinstance(value, list) else []


def _context_doc_names(contexts):
    docs = []
    for ctx in _safe_contexts(contexts):
        filename = ctx.get("filename") or ctx.get("metadata", {}).get("source_file") or ctx.get("doc_id", "")
        docs.append(str(filename))
    return docs


def _context_chunk_types(contexts):
    chunk_types = []
    for ctx in _safe_contexts(contexts):
        meta = ctx.get("metadata") or {}
        chunk_types.append(str(meta.get("chunk_type", ctx.get("chunk_type", ""))))
    return chunk_types


def _hit_any_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    return int(bool(pred_norm & gt_norm))


def _all_gold_docs_hit_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    if not gt_norm:
        return 0
    return int(gt_norm.issubset(pred_norm))


def _doc_recall_at_k(pred_docs, gt_docs, k=5):
    pred_norm = {_normalize_doc_name_for_analysis(x) for x in pred_docs[:k] if str(x).strip()}
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    if not gt_norm:
        return np.nan
    return len(pred_norm & gt_norm) / len(gt_norm)


def _rank_first_gold(pred_docs, gt_docs, k=5):
    gt_norm = {_normalize_doc_name_for_analysis(x) for x in gt_docs if str(x).strip()}
    for idx, doc in enumerate(pred_docs[:k], start=1):
        if _normalize_doc_name_for_analysis(doc) in gt_norm:
            return idx
    return None


def _short(value, max_chars=70):
    if isinstance(value, (list, tuple, set)):
        text = " | ".join(map(str, value))
    else:
        text = str(value)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= max_chars else text[:max_chars].rstrip() + " ..."


def _display_title(title):
    print()
    print("=" * 100)
    print(title)

try:
    _prediction_paths = prediction_paths
except NameError:
    _prediction_paths = []

if not _prediction_paths:
    pred_dir = PREDICTION_DIR if "PREDICTION_DIR" in globals() else Path(PROJECT_ROOT) / "outputs" / "retrieval_eval_p4_hwpx" / "predictions"
    pred_files = sorted(Path(pred_dir).glob("R*_p4_hwpx_*_predictions.jsonl"))
    _prediction_paths = []
    for pred_path in pred_files:
        exp_id = pred_path.name.replace("_predictions.jsonl", "")
        dummy_exp = type("ExperimentRef", (), {"experiment_id": exp_id, "retrieval_method": exp_id})()
        _prediction_paths.append((dummy_exp, pred_path))

if not _prediction_paths:
    raise FileNotFoundError("prediction_paths is missing and no predictions JSONL files were found.")

_eval_lookup = eval_df.copy()
_eval_lookup["_source_eval_file_str"] = _eval_lookup["source_eval_file"].astype(str)
_eval_lookup["_id_str"] = _eval_lookup["id"].astype(str)

analysis_rows = []
for exp, pred_path in _prediction_paths:
    pred_df = _load_prediction_jsonl(Path(pred_path))
    for _, row in pred_df.iterrows():
        source_eval_file = str(row.get("source_eval_file", ""))
        qid = str(row.get("id", ""))
        gt_match = _eval_lookup[(_eval_lookup["_source_eval_file_str"] == source_eval_file) & (_eval_lookup["_id_str"] == qid)]
        if gt_match.empty:
            continue
        gt_row = gt_match.iloc[0]
        gt_docs = gt_row.get("ground_truth_doc_list", [])
        contexts = _safe_contexts(row.get("retrieved_contexts", []))
        pred_docs = _context_doc_names(contexts)
        chunk_types = _context_chunk_types(contexts)
        first_rank = _rank_first_gold(pred_docs, gt_docs, k=FINAL_TOP_K)
        top1_score = row.get("top1_score", None)
        if top1_score is None and contexts:
            top1_score = contexts[0].get("score")
        analysis_rows.append({
            "experiment_id": getattr(exp, "experiment_id", str(exp)),
            "retrieval_method": getattr(exp, "retrieval_method", ""),
            "source_eval_file": source_eval_file,
            "id": qid,
            "question": row.get("question", ""),
            "type": gt_row.get("type", ""),
            "difficulty": gt_row.get("difficulty", ""),
            "gt_doc_count": len(gt_docs),
            "hit_at_5": _hit_any_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "all_gold_docs_hit_at_5": _all_gold_docs_hit_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "doc_recall_at_5": _doc_recall_at_k(pred_docs, gt_docs, FINAL_TOP_K),
            "first_gold_rank": first_rank,
            "gt_docs": gt_docs,
            "retrieved_docs": pred_docs[:FINAL_TOP_K],
            "retrieved_chunk_types": chunk_types[:FINAL_TOP_K],
            "top1_score": top1_score,
            "retrieval_status": row.get("retrieval_status", ""),
            "coverage_reason": row.get("coverage_reason", ""),
        })

failure_df = pd.DataFrame(analysis_rows)
failure_df["question_short"] = failure_df["question"].apply(lambda x: _short(x, 70))
failure_df["gt_docs_short"] = failure_df["gt_docs"].apply(lambda x: _short(x, 80))
failure_df["retrieved_docs_short"] = failure_df["retrieved_docs"].apply(lambda x: _short(x, 95))
failure_df["retrieved_chunk_types_short"] = failure_df["retrieved_chunk_types"].apply(lambda x: _short(x, 70))
failure_df["top1_score_round"] = pd.to_numeric(failure_df["top1_score"], errors="coerce").round(4)

analysis_dir = OUTPUT_DIR / "analysis"
analysis_dir.mkdir(parents=True, exist_ok=True)
failure_csv_path = analysis_dir / f"failure_analysis_p4_hwpx_{CORPUS_LIMIT}_sample{EVAL_SAMPLE_SIZE or 'all'}.csv"
failure_export = failure_df.copy()
for col in ["gt_docs", "retrieved_docs", "retrieved_chunk_types"]:
    failure_export[col] = failure_export[col].apply(lambda x: json.dumps(x, ensure_ascii=False))
failure_export.to_csv(failure_csv_path, index=False, encoding="utf-8-sig")

print("analysis rows:", len(failure_df))
print("experiments:", sorted(failure_df["experiment_id"].unique()))
print("saved full failure analysis:", failure_csv_path)

_display_title("1) Hit/Miss count by experiment")
display(
    failure_df
    .groupby(["experiment_id", "hit_at_5"])
    .size()
    .reset_index(name="count")
    .sort_values(["experiment_id", "hit_at_5"])
)

_display_title("2) Miss count by type/difficulty/gt_doc_count")
display(
    failure_df[failure_df["hit_at_5"] == 0]
    .groupby(["experiment_id", "type", "difficulty", "gt_doc_count"])
    .size()
    .reset_index(name="miss_count")
    .sort_values(["experiment_id", "miss_count"], ascending=[True, False])
    .head(40)
)

_display_title("3) Miss count by retrieved chunk type mix")
chunk_mix = failure_df[failure_df["hit_at_5"] == 0].copy()
chunk_mix["retrieved_chunk_type_mix"] = chunk_mix["retrieved_chunk_types"].apply(lambda xs: " | ".join([x for x in xs if x]))
display(
    chunk_mix
    .groupby(["experiment_id", "retrieved_chunk_type_mix"])
    .size()
    .reset_index(name="miss_count")
    .sort_values(["experiment_id", "miss_count"], ascending=[True, False])
    .head(20)
)

analysis rows: 300
experiments: ['R0_p4_hwpx_250_v1_dense_top5', 'R1_p4_hwpx_250_v2_dense_rerank_top5', 'R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5']
saved full failure analysis: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/analysis/failure_analysis_p4_hwpx_250_sample100.csv

====================================================================================================
1) Hit/Miss count by experiment

                              experiment_id  hit_at_5  count
0              R0_p4_hwpx_250_v1_dense_top5         0      8
1              R0_p4_hwpx_250_v1_dense_top5         1     92
2       R1_p4_hwpx_250_v2_dense_rerank_top5         0      2
3       R1_p4_hwpx_250_v2_dense_rerank_top5         1     98
4  R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5         0      1
5  R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5         1     99

====================================================================================================
2) Miss count by type/difficulty/gt_doc_count

                              experiment_id type difficulty  gt_doc_count  miss_count
6              R0_p4_hwpx_250_v1_dense_top5    E          하             1           2
0              R0_p4_hwpx_250_v1_dense_top5    A          중             1           1
1              R0_p4_hwpx_250_v1_dense_top5    B          중             2           1
2              R0_p4_hwpx_250_v1_dense_top5    C          중             1           1
3              R0_p4_hwpx_250_v1_dense_top5    D          중             1           1
4              R0_p4_hwpx_250_v1_dense_top5    D          하             1           1
5              R0_p4_hwpx_250_v1_dense_top5    E          중             1           1
7       R1_p4_hwpx_250_v2_dense_rerank_top5    E          중             1           1
8       R1_p4_hwpx_250_v2_dense_rerank_top5    E          하             1           1
9  R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5    E          하             1           1

====================================================================================================
3) Miss count by retrieved chunk type mix

                              experiment_id               retrieved_chunk_type_mix  miss_count
2              R0_p4_hwpx_250_v1_dense_top5       text | text | text | text | text           4
1              R0_p4_hwpx_250_v1_dense_top5              text | text | text | text           3
0              R0_p4_hwpx_250_v1_dense_top5                     text | text | text           1
3       R1_p4_hwpx_250_v2_dense_rerank_top5             text | text | table | text           1
4       R1_p4_hwpx_250_v2_dense_rerank_top5      text | text | text | text | table           1
5  R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5  table | table | table | table | table           1

In [ ]:
# ===== Compact R0/R1/R2 hit pattern summary =====
pivot_cols = ["source_eval_file", "id", "question", "type", "difficulty", "gt_doc_count"]
hit_pivot = failure_df.pivot_table(
    index=pivot_cols,
    columns="experiment_id",
    values="hit_at_5",
    aggfunc="max",
    fill_value=0,
).reset_index()

experiment_cols = [c for c in hit_pivot.columns if str(c).startswith("R")]
alias_map = {col: str(col).split("_", 1)[0] for col in experiment_cols}
print("experiment aliases:")
for col in experiment_cols:
    print(f"  {alias_map[col]} = {col}")

hit_pivot["question_short"] = hit_pivot["question"].apply(lambda x: _short(x, 70))

if len(experiment_cols) >= 2:
    base_col = experiment_cols[0]
    best_col = experiment_cols[-1]
    hit_pivot["pattern"] = hit_pivot[experiment_cols].astype(str).agg("".join, axis=1)
    view_cols = ["source_eval_file", "id", "type", "difficulty", "gt_doc_count", "question_short"] + experiment_cols

    _display_title("4) Hit pattern summary")
    display(hit_pivot["pattern"].value_counts().rename_axis("hit_pattern").reset_index(name="questions"))

    def _compact_pattern_view(df, max_rows=12):
        out = df[view_cols].copy().rename(columns=alias_map)
        return out.head(max_rows)

    _display_title("5) Final experiment improved over baseline")
    improved = hit_pivot[(hit_pivot[base_col] == 0) & (hit_pivot[best_col] == 1)]
    display(_compact_pattern_view(improved, 12))

    _display_title("6) Baseline hit but final experiment missed")
    regressed = hit_pivot[(hit_pivot[base_col] == 1) & (hit_pivot[best_col] == 0)]
    display(_compact_pattern_view(regressed, 12))

    _display_title("7) All experiments missed")
    all_missed = hit_pivot[hit_pivot[experiment_cols].sum(axis=1) == 0]
    display(_compact_pattern_view(all_missed, 12))
else:
    print("Not enough experiment columns to compare.")

experiment aliases:
  R0 = R0_p4_hwpx_250_v1_dense_top5
  R1 = R1_p4_hwpx_250_v2_dense_rerank_top5
  R2 = R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5

====================================================================================================
4) Hit pattern summary

  hit_pattern  questions
0         111         92
1         011          6
2         001          1
3         000          1

====================================================================================================
5) Final experiment improved over baseline

experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,question_short,R0,R1,R2
9,eval_batch_02.csv,Q040,E,중,1,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...,0,0,1
11,eval_batch_03.csv,Q056,C,중,1,"그렇다면 이 예산 하에서, 언급하신 주요 대학 구축 시스템 중 내부 기초 데이터 기반의 경영 구조 관련 부분은 어느 부...",0,1,1
21,eval_batch_04.csv,Q079,E,하,1,쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?,0,1,1
48,eval_batch_14.csv,Q278,D,중,1,"을지대학교 비교과시스템 개발 용역 지침에서, 학생 심리상담 예약 연동 모듈을 개발할 때 우울증 고위험군 재학생들에게 대...",0,1,1
58,eval_batch_17.csv,Q325,A,중,1,"한국원자력연구원이 선량평가시스템 고도화 과업을 통해 극적으로 단축하고자 하는, 기존 직원들의 불만 사항 중 하나인 '데...",0,1,1
65,eval_batch_18.csv,Q357,D,하,1,"을지대학교 비교과시스템 개발 지시서에서, 마일리지 성적이 우수한 상위 동아리 학생 대표 5명에게 지급해야 하는 해외 유...",0,1,1
74,eval_batch_20.csv,Q392,B,중,2,케빈랩 평택시 관내 AI 영상감시망과 한국교육과정평가원의 국가교육과정 NCIC 운영망은 모두 '비상시(재난 및 장애시)...,0,1,1

====================================================================================================
6) Baseline hit but final experiment missed

Empty DataFrame
Columns: [source_eval_file, id, type, difficulty, gt_doc_count, question_short, R0, R1, R2]
Index: []

====================================================================================================
7) All experiments missed

experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,question_short,R0,R1,R2
45,eval_batch_12.csv,Q239,E,하,1,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?,0,0,0

In [ ]:
# ===== Compact failure case list =====
# Pick a CASE_ID from this compact table, then run the next cell to inspect it in plain text.

DETAIL_ROWS = 25
FAIL_CASES = failure_df[failure_df["hit_at_5"] == 0].copy().reset_index(drop=True)
FAIL_CASES["case_id"] = FAIL_CASES.index
FAIL_CASES = FAIL_CASES.sort_values(["experiment_id", "top1_score_round"], ascending=[True, True], na_position="last").reset_index(drop=True)
FAIL_CASES["case_id"] = FAIL_CASES.index

compact_case_cols = [
    "case_id",
    "experiment_id",
    "source_eval_file",
    "id",
    "type",
    "difficulty",
    "gt_doc_count",
    "top1_score_round",
    "question_short",
]

print("full detail csv:", failure_csv_path)
print("total miss cases:", len(FAIL_CASES))
display(FAIL_CASES[compact_case_cols].head(DETAIL_ROWS))

full detail csv: /content/drive/MyDrive/DB_RAG_Codeit_Project/outputs/retrieval_eval_p4_hwpx/analysis/failure_analysis_p4_hwpx_250_sample100.csv
total miss cases: 11

,case_id,experiment_id,source_eval_file,id,type,difficulty,gt_doc_count,top1_score_round,question_short
0,0,R0_p4_hwpx_250_v1_dense_top5,eval_batch_04.csv,Q079,E,하,1,0.3081,쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?
1,1,R0_p4_hwpx_250_v1_dense_top5,eval_batch_12.csv,Q239,E,하,1,0.3376,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
2,2,R0_p4_hwpx_250_v1_dense_top5,eval_batch_02.csv,Q040,E,중,1,0.3682,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...
3,3,R0_p4_hwpx_250_v1_dense_top5,eval_batch_17.csv,Q325,A,중,1,0.4245,"한국원자력연구원이 선량평가시스템 고도화 과업을 통해 극적으로 단축하고자 하는, 기존 직원들의 불만 사항 중 하나인 '데..."
4,4,R0_p4_hwpx_250_v1_dense_top5,eval_batch_14.csv,Q278,D,중,1,0.4256,"을지대학교 비교과시스템 개발 용역 지침에서, 학생 심리상담 예약 연동 모듈을 개발할 때 우울증 고위험군 재학생들에게 대..."
5,5,R0_p4_hwpx_250_v1_dense_top5,eval_batch_20.csv,Q392,B,중,2,0.4393,케빈랩 평택시 관내 AI 영상감시망과 한국교육과정평가원의 국가교육과정 NCIC 운영망은 모두 '비상시(재난 및 장애시)...
6,6,R0_p4_hwpx_250_v1_dense_top5,eval_batch_18.csv,Q357,D,하,1,0.4528,"을지대학교 비교과시스템 개발 지시서에서, 마일리지 성적이 우수한 상위 동아리 학생 대표 5명에게 지급해야 하는 해외 유..."
7,7,R0_p4_hwpx_250_v1_dense_top5,eval_batch_03.csv,Q056,C,중,1,0.5652,"그렇다면 이 예산 하에서, 언급하신 주요 대학 구축 시스템 중 내부 기초 데이터 기반의 경영 구조 관련 부분은 어느 부..."
8,8,R1_p4_hwpx_250_v2_dense_rerank_top5,eval_batch_12.csv,Q239,E,하,1,0.0016,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?
9,9,R1_p4_hwpx_250_v2_dense_rerank_top5,eval_batch_02.csv,Q040,E,중,1,0.0542,고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해...
10,10,R2_p4_hwpx_250_v2_hybrid_rrf_rerank_top5,eval_batch_12.csv,Q239,E,하,1,0.0023,그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?

In [ ]:
# ===== Failure CASE_ID detail viewer =====
# Change CASE_IDS and rerun only this cell.
# Examples: CASE_IDS = [0] or CASE_IDS = [0, 1, 2, 3, 4]

CASE_IDS = [0, 1, 2, 3, 4]
MAX_TEXT_CHARS = 900


def show_failure_case(case_id: int):
    if "FAIL_CASES" not in globals() or FAIL_CASES.empty:
        print("FAIL_CASES is empty. Run the compact failure case list cell first.")
        return
    matches = FAIL_CASES[FAIL_CASES["case_id"] == case_id]
    if matches.empty:
        print("Unknown CASE_ID:", case_id)
        return
    miss = matches.iloc[0]
    print("=" * 120)
    print(f"CASE_ID: {case_id}")
    print(f"EXPERIMENT: {miss['experiment_id']}")
    print(f"EVAL: {miss['source_eval_file']} / {miss['id']}")
    print(f"TYPE: {miss['type']} | DIFFICULTY: {miss['difficulty']} | GT_DOC_COUNT: {miss['gt_doc_count']} | TOP1: {miss.get('top1_score_round')}")
    print()
    print("QUESTION:")
    print(miss["question"])
    print()
    print("GT_DOCS:")
    for doc in miss["gt_docs"]:
        print("-", doc)
    print()
    print("RETRIEVED_DOCS:")
    for doc, chunk_type in zip(miss["retrieved_docs"], miss["retrieved_chunk_types"]):
        print(f"- [{chunk_type}] {doc}")

    pred_path = None
    for exp, path in _prediction_paths:
        if getattr(exp, "experiment_id", str(exp)) == miss["experiment_id"]:
            pred_path = Path(path)
            break
    if pred_path is None:
        return

    pred_df = _load_prediction_jsonl(pred_path)
    recs = pred_df[(pred_df["source_eval_file"].astype(str) == str(miss["source_eval_file"])) & (pred_df["id"].astype(str) == str(miss["id"]))]
    if recs.empty:
        return

    print()
    print("RETRIEVED CONTEXTS:")
    contexts = recs.iloc[0].get("retrieved_contexts", [])
    for ctx in _safe_contexts(contexts)[:FINAL_TOP_K]:
        text = str(ctx.get("text", "")).replace("\n", " ")
        if len(text) > MAX_TEXT_CHARS:
            text = text[:MAX_TEXT_CHARS].rstrip() + " ..."
        meta = ctx.get("metadata") or {}
        print("-" * 100)
        print(f"rank={ctx.get('rank')} score={ctx.get('score')} file={ctx.get('filename')}")
        print(f"chunk_type={meta.get('chunk_type')} chunk_id={ctx.get('chunk_id')}")
        print(text)


for case_id in CASE_IDS:
    show_failure_case(case_id)

========================================================================================================================
CASE_ID: 0
EXPERIMENT: R0_p4_hwpx_250_v1_dense_top5
EVAL: eval_batch_04.csv / Q079
TYPE: E | DIFFICULTY: 하 | GT_DOC_COUNT: 1 | TOP1: 0.3081

QUESTION:
쑤자원공샤에서 용인 첨단 빤도체 구까산단으루 용수 공갑하는 씨스템 F/S 사옵으이 토탈 에샤는 얼마입니꺄?

GT_DOCS:
- 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp

RETRIEVED_DOCS:
- [text] 국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
- [text] KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
- [text] 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
- [text] 국가과학기술지식정보서비스_국가암데이터센터 운영시스템 관리용역 .hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.3081318140029907 file=국립암센터_국가암데이터센터 운영시스템 관리용역.hwp
chunk_type=text chunk_id=doc_e06c24ba624f_text_text_0041_part_003_aeb102686739
함): 69,090,909 | 수량: 1 품 목: HPE nimble HF20 dual contraller storage raw 126T, usable 101, 11.52Tb cache -> 100테라 | 제품단가(부가세 미포함): 131,818,182 | 수량: 1 구분: L2 스위치 - 암데이터 관리기반 2차 | 품 목: Catalyst 2960-X 48 GigE, 2 x 10G SFP+, LAN Base | 제품단가(부가세 미포함): 7,727,273 | 수량: 2 구분: L4 스위치 - 암데이터 관리기반 2차 | 품 목: PAS-K 3200X | 제품단가(부가세 미포함): 57,727,273 | 수량: 2 구분: 스토리지 유지보수 - 암데이터 관리기반 3차 | 품 목: NetApp FAS8300 | 제품단가(부가세 미포함): 410,727,273 | 수량: 1
----------------------------------------------------------------------------------------------------
rank=2 score=0.2941545248031616 file=KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp
chunk_type=text chunk_id=doc_bf8e796b625c_text_text_0004_part_001_7181a9affcb0
[문서: KOICA 전자조달_[지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보.hwp | 사업명: [지문] [국제] (재공고)우즈베키스탄 ICT기반의 수자원정보 | 발주기관: KOICA 전자조달 | 섹션: 문서 시작 | 유형: text] 약어: WAS | 영어 표기: Web Application Server | 한글 명칭: 웹 어플리케이션 서버 약어: WEB | 영어 표기: World Wide Web | 한글 명칭: 월드와이드웹(인터넷) 약어: WUA | 영어 표기: Water User Association | 한글 명칭: 물 사용자 협의체 약어: XML | 영어 표기: eXtensible Markup Language | 한글 명칭: W3C에서 개발된 이기종 데이터 연동 마크업 언어 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: I | col_2 | 제안 요청내용 1. 용역개요 가. 용 역 명 : 우즈베키스탄 ICT기반의 수자원정보화 마스터플랜 수립 및 시설기반강화 시범사업 사후관리 PMC 용역 나. 용역기간 : 계약체결일로부터 2024.12.31.까지 다. 대 상 지 : 우즈베키스탄 라. 집행 한도액 : 830,301,769원($643,645/1$=1,290원, 2023년 기준환율) (부가가치세 등 제반 비용 포함) ㅇ 1차연도(2024) : 830,301,769원 마. 용역범위 ㅇ 우즈베키스탄 수자원정보시스템 시스템 개선 - 기초정보 관리시스템 개선 - 실시간 모니터링 시스템 개선 - 장비관리 시스템 개선 - 물관리 의사결정지원 시스템 개선 * 시스템 개선 방안은 우즈벡 수자원부에서 시스템 상세사항을 준비하여 제공 예정(시스템 각 세부 메뉴 제공) ㅇ KOICA 구축 미수신 수위관측소 기자재 설치 및 유지보수 - 미수신 수위관측소의 유지관리를 ...
----------------------------------------------------------------------------------------------------
rank=3 score=0.2848691940307617 file=사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp
chunk_type=text chunk_id=doc_5b75765779be_text_text_0007_part_001_06931c010a3d
[문서: 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp | 사업명: 우즈벡-키르기즈스탄 기후변화대응 스 | 발주기관: 사단법인아시아물위원회사무국 | 섹션: Ⅵ. 서식 | 유형: text] 1. 용역 개요 가. 용역명 ❍ (국문) 우즈벡-키르기즈스탄 기후변화대응 스마트 관개시스템 구축사업 ❍ (영문) Strengthening Climate Resilience through Introduction of Innovative Smart Techniques in Flood and Drought Management in Ozbekistan-Kyrgyzstan 나. 용역기간 : 계약체결일로부터 2027년 12월 31일 까지 다. 용역금액 : 5,031,000,000원 (손해배상보험(공제)료 포함) 라. 대 상 지 : 키르기스스탄(Talas-Alatau 및 Ferghana 산맥), 우즈베키스탄(Ferghana) 마. 용역범위 [표 | 섹션: Ⅵ. 서식 | rows: 5 | cols: 2] 컬럼: 구 분 | 주 요 내 용 구 분: 시설구축 | 주 요 내 용: ◦ 양수장 1개소 설치 1식, 부대공 등 / ◦ 수문 1개소 설치 1식, 부대공 등 구 분: 기자재 지원 | 주 요 내 용: ◦ 차량 : SUV 1대 / ◦ 사무용품 : 데스크탑, 노트북, 프린터 등 구 분: 전문가 파견 | 주 요 내 용: ◦ 9개 분야 총 61개월(국내 9개월, 국외 52개월) : PM, 수자원1(DPM), 수자원2, 토질, 구조, 토목, 기계, 전기, 건축 구 분: 사업관리 | 주 요 내 용: ◦ 사업 총괄관리 / - 사업 진도보고(착수신고, 월간공정보고, 연차별 실적보고, 최종결과 보고 등) / - 사업수행계획서, 액션플랜 수립 및 관리 / ◦ 전문가 파견관리 / - 전문가 파견계획서 및 귀국 보고서 ...
----------------------------------------------------------------------------------------------------
rank=4 score=0.28254663944244385 file=국가과학기술지식정보서비스_국가암데이터센터 운영시스템 관리용역 .hwp
chunk_type=text chunk_id=doc_2327bbf064bc_text_text_0040_part_003_5195363de65b
제품단가: 410,727,273 | 수량: 1 구분: 원격분석관련 H/W - 암데이터 관리기반 4차 | 품 목: CISCO MDS 9148S | 제품단가: 44,000,000 | 수량: 2 □ 국가암데이터센터/암빅데이터센터 SW 도입 장비 [표 | 섹션: 서식 12. | rows: 43 | cols: 4] 컬럼: 구분 | 품 목 | 제품단가 | 수량 구분: VMWare | 품 목: Basic Support/Subscription VMware vSphere 6 Standard for 1 processor for 1 year | 제품단가: 897,000 | 수량: 10 품 목: Basic Support/Subscription for vCenter Server 7 Standard for 1 Year | 제품단가: 3,891,000 | 수량: 1
========================================================================================================================
CASE_ID: 1
EXPERIMENT: R0_p4_hwpx_250_v1_dense_top5
EVAL: eval_batch_12.csv / Q239
TYPE: E | DIFFICULTY: 하 | GT_DOC_COUNT: 1 | TOP1: 0.3376

QUESTION:
그뎌기요 보홈개뱔원애서 하는 실쏜보홈 쳥구 전싼화 사옵 그 예산 쳥액이 맹시적으로 어뜨케 표시대어 잇서요?

GT_DOCS:
- 사단법인 보험개발원_실손보험 청구 전산화 시스템 구축 사업.hwp

RETRIEVED_DOCS:
- [text] 경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
- [text] 경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
- [text] 경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp
- [text] 경희대학교산학협력단_산학협력단 정보시스템 운영 용역업체 선정.hwp
- [text] 한국연구재단_2024년 대학산학협력활동 실태조사 시스템(UICC) 기능개선.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.33761167526245117 file=경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
chunk_type=text chunk_id=doc_329ad26d9c86_text_text_0029_part_003_a416a277d771
cols: 5] 컬럼: 재정상황 / (2023년도) / (단위 : 천원) | 자 본 금 | 매 출 액 | 순 이 익 | 비 고 그룹: 주 요 연 혁 [서식8] 주요사업 실적 및 내용 실적현황 [표 | 섹션: Ⅵ. 제안서 관련서식 | rows: 11 | cols: 6] 컬럼: 연번 | 용역명 | 용역 개요 | 계약기간 | 계약금액 | 발주처 그룹: 합 계 ※ 유의사항 ⦁실적현황을 시간 순으로 작성 ⦁발주기관이 직접 확인한 원본 또는 조달청 실적증명원만 인정하나, 부득이 실적증명원 발급이 어려울 경우 실적증빙자료(계약서, 세금계산서)로 실적증명서 갈음 가능 (모두 제출, 원본대조필 필수)
----------------------------------------------------------------------------------------------------
rank=2 score=0.33761167526245117 file=경희대학교_[재공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp
chunk_type=text chunk_id=doc_d6f6cd097de9_text_text_0029_part_003_a416a277d771
cols: 5] 컬럼: 재정상황 / (2023년도) / (단위 : 천원) | 자 본 금 | 매 출 액 | 순 이 익 | 비 고 그룹: 주 요 연 혁 [서식8] 주요사업 실적 및 내용 실적현황 [표 | 섹션: Ⅵ. 제안서 관련서식 | rows: 11 | cols: 6] 컬럼: 연번 | 용역명 | 용역 개요 | 계약기간 | 계약금액 | 발주처 그룹: 합 계 ※ 유의사항 ⦁실적현황을 시간 순으로 작성 ⦁발주기관이 직접 확인한 원본 또는 조달청 실적증명원만 인정하나, 부득이 실적증명원 발급이 어려울 경우 실적증빙자료(계약서, 세금계산서)로 실적증명서 갈음 가능 (모두 제출, 원본대조필 필수)
----------------------------------------------------------------------------------------------------
rank=3 score=0.33761167526245117 file=경희대학교산학협력단_[재공고] 산학협력단 정보시스템 운영 용역업체 .hwp
chunk_type=text chunk_id=doc_dcf4ff2202e1_text_text_0029_part_003_a416a277d771
cols: 5] 컬럼: 재정상황 / (2023년도) / (단위 : 천원) | 자 본 금 | 매 출 액 | 순 이 익 | 비 고 그룹: 주 요 연 혁 [서식8] 주요사업 실적 및 내용 실적현황 [표 | 섹션: Ⅵ. 제안서 관련서식 | rows: 11 | cols: 6] 컬럼: 연번 | 용역명 | 용역 개요 | 계약기간 | 계약금액 | 발주처 그룹: 합 계 ※ 유의사항 ⦁실적현황을 시간 순으로 작성 ⦁발주기관이 직접 확인한 원본 또는 조달청 실적증명원만 인정하나, 부득이 실적증명원 발급이 어려울 경우 실적증빙자료(계약서, 세금계산서)로 실적증명서 갈음 가능 (모두 제출, 원본대조필 필수)
----------------------------------------------------------------------------------------------------
rank=4 score=0.33761167526245117 file=경희대학교산학협력단_산학협력단 정보시스템 운영 용역업체 선정.hwp
chunk_type=text chunk_id=doc_b3423b7721a3_text_text_0029_part_003_a416a277d771
cols: 5] 컬럼: 재정상황 / (2023년도) / (단위 : 천원) | 자 본 금 | 매 출 액 | 순 이 익 | 비 고 그룹: 주 요 연 혁 [서식8] 주요사업 실적 및 내용 실적현황 [표 | 섹션: Ⅵ. 제안서 관련서식 | rows: 11 | cols: 6] 컬럼: 연번 | 용역명 | 용역 개요 | 계약기간 | 계약금액 | 발주처 그룹: 합 계 ※ 유의사항 ⦁실적현황을 시간 순으로 작성 ⦁발주기관이 직접 확인한 원본 또는 조달청 실적증명원만 인정하나, 부득이 실적증명원 발급이 어려울 경우 실적증빙자료(계약서, 세금계산서)로 실적증명서 갈음 가능 (모두 제출, 원본대조필 필수)
----------------------------------------------------------------------------------------------------
rank=5 score=0.3328283429145813 file=한국연구재단_2024년 대학산학협력활동 실태조사 시스템(UICC) 기능개선.hwp
chunk_type=text chunk_id=doc_48ae201c5bc1_text_text_0035_part_003_567cd07475ec
적 (단위 : 천원) [표 | 섹션: 문서 시작 | rows: 2 | cols: 5] 컬럼: 사 업 명 | 사 업 기 간 | 계 약 금 액 | 발 주 처 | 비 고 - 현재 수행중인 사업도 포함하여 연도순으로 기재하며, 제안과제와 직접적으로 관련 있는 것만 기재한다. - 하도급은 발주처가 승인한 경우에 한하여 작성하며 비고란에 원도급회사를 기재한다. - 공동도급계약일 경우에는 계약금액란에 제안사의 지분만을 기재한다. [서식 제5호] 용역이행 실적증명서 [표 | 섹션: 문서 시작 | rows: 14 | cols: 11] 컬럼: 신청인 | 업 체 명 (상호) | col_3 | col_4 | col_5 | col_6 | col_7 | 대 표 자 | col_9 | col_10 | col_11
========================================================================================================================
CASE_ID: 2
EXPERIMENT: R0_p4_hwpx_250_v1_dense_top5
EVAL: eval_batch_02.csv / Q040
TYPE: E | DIFFICULTY: 중 | GT_DOC_COUNT: 1 | TOP1: 0.3682

QUESTION:
고대 차세대 ERP 말고 이번 학사 포털 플젝에서 메인으로 잡고 있는 레인지랑 타겟 베네핏이 어케 되는지 RFP 랩업해서 간략히 요약좀 해줄래?

GT_DOCS:
- 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf

RETRIEVED_DOCS:
- [text] 국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
- [text] 국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
- [text] (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp
- [text] 국민연금공단_2024년 이러닝시스템 운영 용역.hwp
- [text] 서울대학교_서울대학교 발전기금 TEPS 모의시험 · 보충학습 시스템 고도.pdf

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.3681602478027344 file=국제사이버대학교_(재공고) 국제사이버대학교 차세대 학사·행정 시스템.hwp
chunk_type=text chunk_id=doc_06c3935c7388_text_text_0002_part_003_8b4fcd6cd565
기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3, JavaScript)을 기반으로 시스템 전면 재구축 - 교수, 직원 등 다양한 사용자 그룹의 요구를 반영한 사용자 친화적 인터페이스를 구현하여, 사용자가 시스템을 쉽게 접근하고 학사·행정 업무를 처리
----------------------------------------------------------------------------------------------------
rank=2 score=0.3681602478027344 file=국제사이버대학교_국제사이버대학교 차세대 학사·행정 시스템 구축 사.hwp
chunk_type=text chunk_id=doc_3210483c98d2_text_text_0002_part_003_8b4fcd6cd565
기대 ○ 웹 표준 및 웹 접근성에 근거한 처리로 다양한 브라우저 지원 및 모바일 환경 지원 ○ 업무 프로세서의 정립을 통해 보다 전문적이고 안정적인 업무처리 가능 ○ 다중 시스템 연계를 통해 상호 유기적 행정 업무체제를 구현하여 업무의 생산성을 향상 시킬 것으로 기대 ○ 체계적인 자료관리를 기반으로 표준화와 정형화된 학사·행정 시스템 구축 및 유기적 통합으로 입학 및 대학 관리의 효율성, 투명성을 제고한 서비스 실현 [표 | 섹션: 문서 시작 | rows: 1 | cols: 3] 컬럼: 2 | col_2 | 대학 현황 가. 일반현황 ○ 핵심 추진전략 - 기존 액티브엑스 기반 시스템의 한계를 극복하기 위해, 웹표준기술(HTML5, CSS3, JavaScript)을 기반으로 시스템 전면 재구축 - 교수, 직원 등 다양한 사용자 그룹의 요구를 반영한 사용자 친화적 인터페이스를 구현하여, 사용자가 시스템을 쉽게 접근하고 학사·행정 업무를 처리
----------------------------------------------------------------------------------------------------
rank=3 score=0.3565986156463623 file=(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp
chunk_type=text chunk_id=doc_59211e6008a9_text_text_0002_part_003_b0aa1cf64629
바일 앱 공급/ 관리자, 사용자) 그룹: 온라인 스크리닝 시스템 공급 (비디오라이브러리, 심사 시스템 등) 그룹: 레드카펫 시스템 공급 (입력폼, 출력폼, 서버, 현장투입) 그룹: 커뮤니티비프 행사지원시스템 공급 (스트리밍, VOD / 채팅 시스템) 4. 사업추진계획 [표 | 섹션: 문서 시작 | rows: 80 | cols: 13] 컬럼: 기간 / 구분 내용 | col_2 | 2024년 | col_4 | col_5 | col_6 | col_7 | col_8 | 2025년 | col_10 | col_11 | col_12 | col_13 2024년: 7 | col_4: 8 | col_5: 9 | col_6: 10 | col_7: 11 | col_8: 12 | 2025년: 1 | col_10: 2 | col_11: 3 | col_12: 4 | col_13: 5
----------------------------------------------------------------------------------------------------
rank=4 score=0.35524070262908936 file=국민연금공단_2024년 이러닝시스템 운영 용역.hwp
chunk_type=text chunk_id=doc_ca7a084838ab_text_text_0003_part_003_a81403a9cf8e
바일 콘텐츠(마이크로러닝 포함) 최적화 지속 추진 ○ 빅데이터를 활용하여 관심분야 및 인기 콘텐츠를 추천해주는 “큐레이팅 서비스” 상시 운영 ○ 학습자의 학습 데이터를 바탕으로 직무·자기개발 맞춤형 콘텐츠 추천 ○ 이러닝 역량진단 운영을 통한 ‘맞춤형 직무체계’ 구축 * 역량진단 결과에 따른 수준별 맞춤 직무과정 제시(통계관리 포함), 교육과정 제시 기준ㆍ세부 과정 등은 공단과 협의 ○ 영상 및 사진 업로드, Q&A 등을 통해 학습자 상호 간 직무지식ㆍ노하우 등 암묵적 지식을 콘텐츠화하여 공유하는 소셜러닝 고도화 운영
----------------------------------------------------------------------------------------------------
rank=5 score=0.33705031871795654 file=서울대학교_서울대학교 발전기금 TEPS 모의시험 · 보충학습 시스템 고도.pdf
chunk_type=text chunk_id=doc_adeadc965b62_text_text_0003_part_002_0f03048b5f07
온라인 플랫폼을 기반으로 기출문제를 분석 가능한 수준별 학습도구 개발을 위한 빅데이터 저장 및 분석 플랫폼 구축 - 사용자의 진단 모의평가 결과 다양한 학습 콘텐츠 활용 히스토리에 기반한 추가 연습문제·학습 내용 추천 서비스 시스템 선택 구축 I. 사업개요 - 2 - ○ 기존 지필 영어시험과 병행해서 운영할 수 있는 CBT/IBT(혹은 온라인 시험) 시행 체제 개발을 위한 경험 축적 및 사전 준비 - 밀려오는 제4차 산업혁명의 물결과 최근 2019신종코로나 바이러스 사태를 계기로 대두되고 있는 CBT/IBT/모바일 기반 영어능력평가 시스템 필요성과 사회적 요구에 대한 능동적 대응 - 온라인 커뮤니케이션에 익숙한 수험자의 변화된 학습 방식에 대응하기 위한 도구 필요2. 사업범위 ○ 연도별 사업범위‘19년사업추진을 위한 계획 수립 및 기반 조성계획수립(완료) lNewTEPS 모의고사/보충학습 iBT 시스템 구축 TF 구성 및 운영liBT 시스템 구축 3개년 계획 수립‘20년(1단계)TEPS 모의고사/보충학습 시스템 구축(1단계)1단계시스템 구축lTEPS 모의고사/보충학습 시스템 구축(분석, 설계, 구현, 시험)l관리 운영시스템 개발lDB 데이터 표준화 및 모델링l클라우드 인프라 아키텍쳐 설계 및 구축l상용SW 도입 및 커스터마이징l문항관리시스템/시험지틀/시험지 개발l모의고사 베타 시행‘21년(2단계)TEPS 모의고사/보충학습 시스템 구축(2단계)2단계시스템 구축
========================================================================================================================
CASE_ID: 3
EXPERIMENT: R0_p4_hwpx_250_v1_dense_top5
EVAL: eval_batch_17.csv / Q325
TYPE: A | DIFFICULTY: 중 | GT_DOC_COUNT: 1 | TOP1: 0.4245

QUESTION:
한국원자력연구원이 선량평가시스템 고도화 과업을 통해 극적으로 단축하고자 하는, 기존 직원들의 불만 사항 중 하나인 '데이터 연산 처리 지연(Timeout) 요인'은 아키텍처 관점에서 어떻게 해결하려 합니까?

GT_DOCS:
- 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp

RETRIEVED_DOCS:
- [text] 국방과학연구소_e-감사시스템 웹 호환성 및 기능보완.hwp
- [text] 한국수출입은행_(긴급) 국가결산체계 개편에 따른 국가회계시스템 고도.pdf
- [text] 국가과학기술지식정보서비스_국가암데이터센터 운영시스템 관리용역 .hwp
- [text] 경기연구원_2024년 통합정보시스템 기능개선 사업(근무성적평정 제도 개.hwp
- [text] 한국수출입은행_(긴급) SCP 중심의 AML 시스템 구축.pdf

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.4245327115058899 file=국방과학연구소_e-감사시스템 웹 호환성 및 기능보완.hwp
chunk_type=text chunk_id=doc_c0ae07107af1_text_text_0004_part_003_865ec2ec80e6
03 | 요구사항명: 실행 주기 row_group: PER-002 / 응답시간 | 요구사항ID: INR-004 | 요구사항명: 기관 내 표준연계모듈 사용 row_group: PER-002 / 응답시간 | 요구사항ID: INR-005 | 요구사항명: 통합정보시스템 연계 row_group: PER-002 / 응답시간 | 요구사항ID: INR-006 | 요구사항명: 연구지원정보시스템 연계 row_group: PER-002 / 응답시간 | 구 분: 4. 데이터 요구사항 | 요구사항ID: DAR-001 | 요구사항명: 데이터 구조 설계 row_group: PER-002 / 응답시간 | 요구사항ID: DAR-002 | 요구사항명: 초기 데이터 구축
----------------------------------------------------------------------------------------------------
rank=2 score=0.41945964097976685 file=한국수출입은행_(긴급) 국가결산체계 개편에 따른 국가회계시스템 고도.pdf
chunk_type=text chunk_id=doc_facb686e34e6_text_text_0007_part_002_47c2f97e369b
케이션성능튜닝과DB튜닝을단계별(개발/테스트/이행등)로실시하여어플리케이션및DB성능개선활동을전개해야함산출정보◾ 성능시험결과서관련요구사항 -22- 요구사항분류성능요구사항요구사항고유번호PER-003요구사항명칭응답시간및처리성능 요구사항상세설명 정의응답시간및처리성능요건 세부내용 ◾ 모든기능은사용자요청시간으로부터평균1초(최대3초)이내에결과제공-단,대용량첨부파일의업로드/다운로드,대량데이터의질의가있는경우등은당행과협의-3초이상의응답시간이필요한경우해당사유표시(사전경고)-응답시간이길게소요되는화면에대해서는응답대기시간중사용자가반복해서명령을실행(버튼클릭)할수없도록조치하여야함◾ 사용자가입력한정보에서발생할수있는모든오류에대한메시지정보를정보입력후3초이내에제시하여야함-오류메시지는사용자가인지하여즉시조치할수있도록작성◾ 성능시험도구등을활용하여동시사용자수에따라성능이저하되지않음을제시하여야하며,이에따르는운영장비에대한부하테스트및성능진단을실시하고,대응책을수립하여응답속도를만족해야함◾ 일일배치업무는기존수행시간보다증가하지아니하여야함※업무관점에서실시간/즉시조회되어야하는업무기능에대해서는데이터양과관계없이목표치를달성해야함.상세내역은당행과협의하여결정함산출정보◾ 성능시험결과서관련요구사항 -23- 마.인터페이스요구사항요구사항분류인터페이스요구사항요구사항고유번호INR-001요구사항명칭UI/UX설계 요구사항상세설명 정의UI/UX설계기준정의 세부내용
----------------------------------------------------------------------------------------------------
rank=3 score=0.41918063163757324 file=국가과학기술지식정보서비스_국가암데이터센터 운영시스템 관리용역 .hwp
chunk_type=text chunk_id=doc_2327bbf064bc_text_text_0001_part_003_717cf73c076d
. 제안요구내용 ○ 소프트웨어 개발·운영 - 소프트웨어의 365일 24시간 무정지 서비스 환경 제공 - 현업 요구사항의 체계적 접수 및 신속 대응 - 프로세스 개선 및 사용자 중심의 효율적 업무시스템 구현 - 정보시스템 기능 확장을 위한 각종 최신 기술 및 자료 지원 - 인력 활용의 비용적 손실을 배제하기 위한 자원 및 품질관리 실시 - 근무 인력의 주인 의식과 책임감 고취를 위한 전사적 교육 지원 ○ 하드웨어 운영·유지보수 - 하드웨어 주요 부품 및 담당 기술인력 확보로 주요 장비 및 정보시스템 무정지 운영 - 장애 발생을 최소화하기 위한 정기 및 수시/전문업체 점검 실시 - 장애 발생 시 무중단 시스템 운영을 위한 우회경로 및 임시대응방안 수립 - 장애 사전탐지 기술 및 최단 시간 대응방안 제시 - 도입 기간 경과에 따른 현재 또는 최신 기술로의 기능 확장 「‘24년도 국가암데이터센터 운영시스템 관리용역」사업 제안요청서
----------------------------------------------------------------------------------------------------
rank=4 score=0.4135575294494629 file=경기연구원_2024년 통합정보시스템 기능개선 사업(근무성적평정 제도 개.hwp
chunk_type=text chunk_id=doc_7287150aeab1_text_text_0002_part_002_da090c182d2f
3호에 따른 과업 내용 변경 및 그에 따른 계약 금액·계약기간 조정이 필요한 경우, 계약상대자는 국가기관 등의 장에게 소프트웨어사업 과업변경요청서를 제출하여야 함 / ※ 본 사업은 ‘소프트웨어 개발사업 적정 사업 기간 산정 기준에 따른 사업’임. 추진 배경 및 필요성 ○ 경기연구원의 전략적 목표 달성 및 성과향상을 위하여 개선한 근무성적평정 제도에 따라 시스템 개발 및 통합정보시스템 반영 필요 관리직 및 공무직 개인성과 평가, 역량평가 신설, 부서평가 도입 등 ○ 이에 연구원은 정보시스템의 안정적·효율적 운영 체계를 지원하고 통합정보시스템의 개선 사항 반영을 위해 기능개선 사업의 추진이 필요함 기대효과 ○ 업무 효율성 증대 수기로 처리하던 평정 결과를 전산화함으로써 평가 입력, 계산, 분석 등 관리자의 반복적인 수작업을 줄여 업무 효율성 증대 시스템을 통해 평가자료를 빠르고 정확하게 수집하고, 즉각적으로 결과를 산출해 평가 프로세스에 걸리는 시간 단축 ○ 평가 신뢰성 및 투명성 제고 수기 방식에서 발생할 수 있는 입력 오류나 실수를 전산화시켜 평가 과정과 결과가 시스템을 통해 공정하게 처리되어 평가 투명성 확보 ○ 법적 및 규정 준수 관리 강화 평가 과정 및 결과가 전산화되어 기록됨에 따라, 평가가 법적 요구사항이나 내부규정을 준수하였는지 여부 확인 가능 이를 통해, 감사나 외부 평가 시에 적법성 입증 가능 ○ 개인 및 조직 성과 비교 용이 전산시스템을 통해 개인별 성과뿐만 아니라 부서 및 조직 전체의 성과도 비교·분석이 가능해 이를 통해 조직 내 성과 차이를 파악하고, 문제점을 개선하거나 우수 사례 확산에 기여 가능 ○ 문서관리 및 보안성 향상 전자 데이터로 저장되기 때문에, 문서의 분실이나 훼손 우려 감소, 데이터 관리 및 검색 용이 접근제어, 암호화를 통해 평가자료의 보안을 강화 ...
----------------------------------------------------------------------------------------------------
rank=5 score=0.41161882877349854 file=한국수출입은행_(긴급) SCP 중심의 AML 시스템 구축.pdf
chunk_type=text chunk_id=doc_8f2c0b1ad260_text_text_0016_part_003_d5678f1f0416
데이터를가지고있는시스템부하를최소화할수있도록성능최적화◾ 운영장비에대한부하테스트및성능진단을실시하고,대응책을수립하여목표성능을만족해야함◾ 어플리케이션성능튜닝과DB튜닝을단계별(개발/테스트/이행등)로실시하여어플리케이션및DB성능개선활동을전개해야함산출정보◾ 성능시험결과서관련요구사항 박마리나 | 2024-04-16 16:32We Finance Global Korea청렴, 모두를 지키는 또 하나의 백신 -48- 요구사항분류성능요구사항요구사항고유번호PER-003요구사항명칭응답시간및처리성능 요구사항상세설명 정의응답시간및처리성능요건 세부내용 ◾ 모든기능은사용자요청시간으로부터평균1초(최대3초)이내에결과제공-단,대용량첨부파일의업로드/다운로드,대량데이터의질의가있는경우등은당행과협의-3초이상의응답시간이필요한경우해당사유표시(사전경고)-응답시간이길게소요되는화면에대해서는응답대기시간중사용자가반복해서명령을실행(버튼클릭)할수없도록조치하여야함◾ 사용자가입력한정보에서발생할수있는모든오류에대한메시지정보를정보입력후3초이내에제시하여야함-오류메시지는사용자가인지하여즉시조치할수있도록작성◾ 성능시험도구등을활용하여동시사용자수에따라성능이저하되지않음을제시하여야하며,이에따르는운영장비에대한부하테스트및성능진단을실시하고,대응책을수립하여응답속도를만족해야함◾ 일일배치업무는기존수행시간보다증가하지아니하여야함※업무관점에서실시간/즉시조회되어야하는업무기능에대해서는데이터양과관계없이목표치를달성해야함.상세내역은당행과협의하여결정함산출정보◾ 성능시험결과서관련요구사항
========================================================================================================================
CASE_ID: 4
EXPERIMENT: R0_p4_hwpx_250_v1_dense_top5
EVAL: eval_batch_14.csv / Q278
TYPE: D | DIFFICULTY: 중 | GT_DOC_COUNT: 1 | TOP1: 0.4256

QUESTION:
을지대학교 비교과시스템 개발 용역 지침에서, 학생 심리상담 예약 연동 모듈을 개발할 때 우울증 고위험군 재학생들에게 대학 지정 병원까지 연결 전송해 주는 응급 콜택시 배차비 국고 지원 한도는 얼마로 잡혀 있습니까?

GT_DOCS:
- 을지대학교_을지대학교 비교과시스템 개발.hwp

RETRIEVED_DOCS:
- [text] KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp
- [text] 경기도교육청_2025년 경기에듀콜센터 시스템 ASP임대 용역.hwp
- [text] KOICA_가나 북부 2개주 포괄적 일차보건의료체계강화사업 수원국시스템활.hwp
- [text] 국립중앙의료원_(긴급)「2024년도 스마트의료지도시스템 고도화」.hwp
- [text] KOICA 전자조달_[지문] 에콰도르 국가 유전자원 데이터 은행 설립 및 역량.hwp

RETRIEVED CONTEXTS:
----------------------------------------------------------------------------------------------------
rank=1 score=0.4256472587585449 file=KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp
chunk_type=text chunk_id=doc_afba17272e87_text_text_0045_part_003_a4edc86ee1d6
용 보상한도 : 10,000,000원 4. 질병/상해 의료비 담보비용 : 20,000,000원 이상 권장 ㅇ (긴급 의료 및 보안지원서비스) 현지파견인력에 대해 해당 서비스 KOICA 파트너인 주식회사 비즈인사이트와 해외파견자 긴급 의료 및 보안 지원 서비스 가입 1. 해당비용 전문가파견-직접경비-파견경비-보험료에 반영 (고정투찰 항목) 2. KOICA는 SOS와의 모계약에 따라 주식회사 비즈인사이트 담당자 및 업무 절차 정보만을 제공하며, 서비스 가입 신청, 비용 지급, 정산 등의 의무는 낙찰자에게 있음 ㅇ 기타경비(실비정산) : 자문위원회, 현지인력고용, 비자료, 예방접종비, 통역료, 차량임차료 등 ㅇ 예비비(고정투찰) : 전체 용역비의 10%를 고정투찰하며, 사전에 협력단의 승인을 받은 후 집행
----------------------------------------------------------------------------------------------------
rank=2 score=0.4210105538368225 file=경기도교육청_2025년 경기에듀콜센터 시스템 ASP임대 용역.hwp
chunk_type=text chunk_id=doc_fca1991da4b3_text_text_0001_part_002_2676051fbafa